simonsobs/sotodlib

.travis.yml
README.md
docs/dev.rst
docs/rtd_requirements.txt
tests/test_hardware.py

Add files to enable travis tests and readthedocs.

Begin travis test file and rtd setup.

---

sotodlib/hardware/config.py

Small change to LAT tube spacing in the example config.

Change LAT tube spacing in example config.

---

sotodlib/data/toast.py
tests/test_toast_export.py

This branch implements basic toast data export to so3g format.  It includes a small serial unit test.  Do not merge until larger tests have been run.

Toast export to so3g format.

---

pipelines/toast_so_example.py
sotodlib/data/toast_export.py
sotodlib/data/toast_frame_utils.py
sotodlib/data/toast_load.py
tests/test_toast_load.py

This PR includes classes needed to load so3g data into toast distributed cache.  It also has an example script.  Since this code only adds optional code that is not imported by default, I'll merge it after tests pass.

Toast data loading

---

pipelines/toast_so_example.py
sotodlib/data/toast_export.py
sotodlib/data/toast_frame_utils.py
sotodlib/data/toast_load.py
tests/test_hardware.py

Several small (but important) bugfixes, as well as many smaller changes to make it easier to transition to the upcoming toast version where MPI is optional.

Toast load fixes

---

pipelines/toast_so_sim.py

Allow user to limit the detectors to just one optical tube. I'll self-merge this since the only affected file is toast_so_sim.py

Tube select

---

sotodlib/hardware/config.py

Updated the top hat bandpass parameters

updated tophat bandpass values

---

pipelines/toast_so_sim.py
sotodlib/pipeline_tools/__init__.py
sotodlib/pipeline_tools/atm.py
sotodlib/pipeline_tools/export.py
sotodlib/pipeline_tools/hardware.py
sotodlib/pipeline_tools/noise.py
sotodlib/pipeline_tools/observation.py
sotodlib/pipeline_tools/pysm.py

Self-merging to maintain compatibility with TOAST refactor

Pipeline tools v2

---

docs/conf.py
setup.cfg
sotodlib/_version.py

Use tags of the form vX.Y.Z.  Set the docs version code through
`__version__`.

Fix versioneer configuration.

---

sotodlib/pipeline_tools/atm.py
sotodlib/pipeline_tools/export.py
sotodlib/pipeline_tools/observation.py
sotodlib/pipeline_tools/pysm.py

Time critical. sotodlib.pipeline_tools are out-of-date.

Upgrade to the latest TOAST

---

pipelines/toast_bin_so3g.py
setup.py

This PR adds a simple new pipeline to visualize so3g files.

add simple map binning pipeline to visualize so3g data dumps

---

sotodlib/hardware/vis.py

Modify matplotlib backend to PDF inside plot function

---

sotodlib/data/load.py

Sometimes you just want to look at the pointing.  This is not terribly
time efficient, since the whole file has to be read regardless.  But
we could imagine superior data formats where the ancillary data is
stored separately from the bolometers.

load_observation: permit user to request dets=[]

---

sotodlib/core/axisman.py
sotodlib/g3_condition.py
sotodlib/g3_filter.py
sotodlib/g3_sim.py
tests/test_data.py

This includes a bug-fix in axisman that would only activate with old
numpy.

Fix imports so all tests pass

---

tests/test_toast_export.py
tests/test_toast_load.py

Almost trivial fixes to track the latest TOAST master.

fix small issues in TOAST load/export unit tests

---

sotodlib/io/toast_export.py
sotodlib/io/toast_frame_utils.py
sotodlib/io/toast_load.py
sotodlib/utils/pipeline_tools/export.py
sotodlib/utils/pipeline_tools/observation.py

* Simulating atmosphere on top of loaded signal
* writing TOD from a pipeline that begins with loading TOD

Modifications to allow

---

pipelines/toast_so_sim.py
sotodlib/io/toast_load.py
sotodlib/utils/pipeline_tools/observation.py

Modest changes to the TOAST interface to make use of the el-nod facilities.

use the new TOAST el-nod facility

---

docs/reference.rst
sotodlib/coords/__init__.py
sotodlib/coords/helpers.py
sotodlib/coords/pmat.py
sotodlib/core/axisman.py
sotodlib/core/context.py
sotodlib/core/flagman.py

Couple of fixes (and a new "coords") module needed for tod stack tutorial ... tomorrow.  Will merge imminently.

FF2F rush 2020

---

docs/context.rst
sotodlib/core/metadata/common.py
sotodlib/core/metadata/obsdb.py
tests/test_obsdb.py

Completes the API for ObsDb, including a "tag" feature.  Documentation.
This is part 1 of a 4-5 part series that will explain the Context system fully and properly...

Improve obsdb

---

sotodlib/io/toast_export.py
sotodlib/utils/pipeline_tools/hardware.py
sotodlib/utils/pipeline_tools/noise.py
sotodlib/utils/pipeline_tools/observation.py

* Add support for multiple common modes and randomized coupling strengths.
* Fix a recent bug preventing simulation of common modes.

Make common mode noise more versatile

---

setup.py

I think this should do the trick.

When running setup.py test, propagate the exit status back to the shell.

---

docs/index.rst
sotodlib/core/axisman.py
tests/test_core.py

Addresses #54 
Also creates docs for AxisManager -- these aren't complete but it's a good start.
@kmharrington or @guanyilun please feel free to review / test / check that this fix doesn't ruin your code.
Does anyone know which of "in_place" vs. "inplace" is more idiomatic?  I think in_place is more compliant with variable naming conventions, but inplace but have more history.

AxisManager: fix in_place=False bug, add a bunch of documentation.

---

.github/workflows/install_deps.sh
sotodlib/coords/helpers.py
sotodlib/coords/pmat.py
sotodlib/tod_ops/gapfill.py
tests/test_coords.py

This brings in some changes to the coords system to support the unbiased mapmaker work.
The coords module is not broadly used, so I will merge in 24 hours unless there are build problems or interesting discussions!

coords module upgrades for mapmaker work

---

sotodlib/vis_hardware.py

When using the `--labels` option to `so_hardware_plot`, the wafer_slot is plotted at a location that is the average of all detectors in that wafer on the plot.  Here is an example:

When drawing plot labels, include labels on the wafer slots.

---

docs/axisman.rst
docs/coords.rst
docs/dev.rst
docs/index.rst
docs/tod_ops.rst
sotodlib/__init__.py
sotodlib/coords/helpers.py
sotodlib/coords/pmat.py
sotodlib/core/axisman.py
sotodlib/core/metadata/resultset.py
sotodlib/tod_ops/filters.py
tests/test_coords.py
tests/test_core.py
tests/test_detdb.py

This is mostly documentation, including:
- AxisManager sphinx docs (accidentally left out of original work)
- coords module sphinx docs and docstrings
Also has bugfixes:
- Allow ResultSet to be indexed with an np.integer, whatever that is.
- iir_filter argument order is better
New features:
- AxisManager.wrap_new(...) makes building new AxisManagers much easier.
- AxisManager.get(key, default=None) makes AxisManager more dict-like
- Logging system is initialized and docs describe how it should be used.
- coords module internal functioning is adjusted slightly, in preparation for more demanding

Improvements feb21

---

pipelines/toast_so_sim.py

Should not merge until https://github.com/hpc4cmb/toast/pull/379 is merged.

Small tweak to simulation pipeline to track TOAST branch

---

sotodlib/toast/sim_sso.py

Adding the Correct Treatment of Temperatures

---

pipelines/toast_so_sim.py
sotodlib/toast/cadence_map.py
sotodlib/toast/pipeline_tools/__init__.py
sotodlib/toast/pipeline_tools/cadence_map.py

Added a new operator to the `toast_so_sim.py` pipeline. It produces a boolean table, written into a single HDF5 file. The table indicates which sky pixels are hit on which modified Julian dates across the data span. Some further development may be needed in the future to break the file into smaller sections without exhausting memory.

Cadence map

---

sotodlib/tod_ops/fft_ops.py

added signal import from scipy at top of file. And created calc_psd(...) function

Psd calculation

---

pipelines/toast_so_sim.py
sotodlib/toast/demodulation.py

This PR fixes two issues @chinoney discovered when combining demodulation with observation matrix.

Tweak the downsampling in demodulation

---

sotodlib/io/load_smurf.py

going to go ahead and merge this since it's a bug fix.

remove continue that was cutting out tune adds

---

sotodlib/core/axisman.py
tests/test_core.py

Also minor cleanup to some other nearby test code.
See commit log.

Fix axisman restrict

---

.github/workflows/install_deps.sh
docs/coords.rst
docs/tod_ops.rst
sotodlib/coords/__init__.py
sotodlib/coords/helpers.py
sotodlib/coords/planets.py
sotodlib/coords/pmat.py
sotodlib/core/context.py
sotodlib/core/metadata/loader.py
sotodlib/tod_ops/detrend.py
sotodlib/tod_ops/fft_ops.py
sotodlib/tod_ops/filters.py
sotodlib/tod_ops/gapfill.py
tests/test_tod_ops.py

Driver of this work is development of tools for mapmaking of planets (or other bright compact sources)
A few other subsystem fixes along the way.  In summary:
- General improvements to coords code: suppression of low-weight/low-condition when doing “remove_weights”.  Timer context manager to help with profiling.
- Context: help with checking metadata existence.
- tod_ops: Bug-fix polynomial gap filling, change interface (inplace->swap) slightly; now tries to use fast fill code from so3g.  Help with processing Ranges in ways useful for gap-filling bright signal data.  fourier_filter and detrend_data can operate on 1-d arrays, too.  fourier_filter will attempt to use OMP_NUM_THREADS threads.  Bugfix high_pass_sine2.  Test fixtures for detrend and gapfill.
- coords.planets module: …

Omnibus 2108

---

sotodlib/toast/crosslinking.py

This branch fixes an issue in old cross-linking maps and adds support to non-constant elevation scans.

More general crosslinking

---

sotodlib/sim_hardware.py

Largely minor instrument updates

Updates to instrument model to match instrumentation documentation

---

docs/conf.py

docs: mock skyfield and h5py

---

sotodlib/sim_hardware.py

Make the noise elevation scalings consistent with the v3r6 noise estimations

Make noise elevation scalings consistent

---

sotodlib/io/load_smurf.py

add function where tunes are made and insert a missed continue

---

.github/workflows/run_tests.sh
.github/workflows/test.yml
setup.py
sotodlib/toast/export.py
sotodlib/toast/frame_utils.py
tests/_helpers.py
tests/test_detdb.py
tests/test_hardware.py
tests/test_metadata.py
tests/test_obsdb.py
tests/test_obsfiledb.py
tests/test_proddb.py
tests/test_time_constant.py
tests/test_toast_export.py
tests/test_toast_load.py

Run tests both with multiple processes and with MPI explicitly disabled.

Run both serial and MPI tests

---

sotodlib/tod_ops/detrend.py

Expose count argument to detrend_tod

---

.readthedocs.yaml
docs/requirements.txt

Will merge in 24 hours unless anyone has reservations!

Fix readthedocs by pinning versions

---

docs/g3tsmurf.rst
sotodlib/io/load_smurf.py

Lots of documentation updates for `load_smurf` functions. 
Sorry I messed up the text wrapping in places but I did test to make sure I fixed everything.

G3tsmurf docs

---

sotodlib/io/load_smurf.py

This is another error I'm seeing show up (loading an incomplete status object). I know why that error is happening but can we add the hot fix here until we've got the longer fix?

Also check for number of channels

---

docs/context.rst

Adding documentation for how to build a metdata index with information for specific detectors. @mhasself  feel free to edit if there are better ways to do it.

Add detector specific example for Metadata indexes

---

sotodlib/io/load_smurf.py

Fixes #204  and another bug I found in the channel naming while fixing that one.

G3tsmurf fix names

---

docs/axisman.rst
sotodlib/core/axisman.py
tests/test_core.py

Adding scalar support to axis manager (#176 )

Adding scalars to AxisManager

---

sotodlib/toast/ops/sim_source.py
workflows/toast_so_sim.py

This PR fixes the polarization weight calculation and begins the process of simulating the source at a location that fits the raster scan pattern.

Move simulated source position and fix polarization weight calculation

---

sotodlib/sim_hardware.py

Update SAT FWHM values to match SO forecast paper versus scaling.

Update SAT FWHM

---

sotodlib/io/load_smurf.py

Found an error when loading directly from files (no database) about the RUID handling. If we don't have a database we can't be sure of the readout unique IDs so we shouldn't load anything.
Also re-ordered the trys / messaging on the status load to quiet things down. This order removes a Warning message that was popping up during what should be default behavior when loading without a database.

Fix RUID load from file and reorder status error handling

---

sotodlib/io/load_smurf.py

Small bug in load_smurf.from_time(). I guess this function isn't used that much...

Bug in SmurfStatus.from_time function

---

docs/axisman.rst
sotodlib/core/axisman.py
sotodlib/core/axisman_io.py
sotodlib/core/flagman.py
tests/test_core.py

This adds .save() and .load() functions to AxisManager.  This can handle complicated data fields, such as RangesMatrix, other AxisManagers, and FlagManagers.
Note this does effectively provide save/load of RangesMatrix -- something we need for flag archives.

AxisManager: save/load to HDF5 (experimental / debugging)

---

.github/workflows/test-docs.yml
docs/conf.py
docs/requirements.txt

Builds sphinx docs, in picky -W mode, mostly to catch autodoc fails when new dependencies are added.

Docs workflow

---

sotodlib/core/axisman.py
sotodlib/io/load_smurf.py
tests/test_core.py

LabelAxis should only accept string labels

---

sotodlib/io/load_smurf.py
sotodlib/tod_ops/filters.py

SmurfStatus Revamp

---

sotodlib/io/load_smurf.py

Adding more logic to finding the end of observations. Related to issue https://github.com/simonsobs/sotodlib/issues/224 
This should fix all the inconsistencies/issues we've been seeing the the LATRt data.

add more logic and options to find end of observations

---

sotodlib/core/axisman.py
tests/test_core.py

Handle scalars properly when making copy of AxisManager

---

docs/conf.py
docs/index.rst
docs/site_pipeline.rst
sotodlib/coords/helpers.py
sotodlib/coords/planets.py
sotodlib/core/axisman.py
sotodlib/core/axisman_io.py
sotodlib/core/context.py
sotodlib/io/load.py
sotodlib/site_pipeline/__init__.py
sotodlib/site_pipeline/make_source_flags.py
sotodlib/site_pipeline/util.py
tests/test_coords.py
tests/test_core.py

PMN first light pipeline element "make-source-flags".  There are still some things to clean up here but this is solid start.  Tested on ACT Uranus context on simons1.
With this, I am also trying to start some conventions for how the pipeline element submodules and their documentation can be written.

make-source-flags

---

docs/conf.py
docs/requirements.txt

docs: mock modules manually

---

setup.py
sotodlib/io/load_smurf.py

Small fixes that I found as I updated our python and was installing things from scratch.

change import order and add pyfftw to requirements

---

sotodlib/io/load_smurf.py

Should close #249 
Note that here all its doing is setting the timezone to UTC without doing any conversions. I can instead have it convert the input datetimes to UTC if that is preferred.

Set timezone to UTC

---

sotodlib/core/axisman.py
tests/test_core.py

Add tests for basic loop behavior.

axisman: fix bug in reference loop handling

---

sotodlib/core/axisman.py
tests/test_core.py

Adding the ability to concatenate sparse arrays in AxisManagers. Found this while reviewing the PR.

Add sparse array AxisManager concatenation

---

sotodlib/io/load_smurf.py

Add functionality to automatically linearize unix timestamps.

linearize timestamps. close #253

---

sotodlib/core/axisman_util.py
tests/test_core.py

A couple of useful axismanager functions implemented in sodetlib usage. Katie said a few may be more generally applicable so I'm copying them here.
If these are merged in I'll remove them from sodetlib.

AxisManager utility functions

---

sotodlib/tod_ops/demodulation.py

Adds in demodulation module originally used for LATR tester timestream data analysis.

add demodulation tod module (exported from latrt_testing)

---

sotodlib/io/load_smurf.py

More edge cases caught by running with many slots. 
@skhrg @jeffiuliano  did you copy tune files between slots? I feel like the edge case we just hit should only come up if you did that? (ps, if you did that, why?! T_T)

Once again we need stream_id filter

---

sotodlib/io/load_smurf.py

Edge case for when trying to load with a g3tsmurf instance but when we're missing tune files in the database. This makes things fail nicely instead of badly.

Fix Tune file missing edge case

---

pipelines/toast_so_sim.py

Simple fix to HWPSS simulations from @Helbouha . Also included in #298 .

Import quick fix from PR 298

---

sotodlib/io/load_smurf.py

Check if end of file is before requested sample range

---

sotodlib/toast/ops/__init__.py
sotodlib/toast/ops/sim_stimulator.py
sotodlib/toast/ops/sim_wiregrid.py
tests/test_sim_stimulator.py
tests/test_sim_wiregrid.py
workflows/toast_so_sim.py

This PR contains both the wiregrid and stimulator simulation operators and their unit tests. There are matching projects in `pwg-scripts` that have been used to integration-test each operator. Further development is likely needed but both operators are functional.

Wiregrid and stimulator simulation operators

---

setup.py

it is imported in sim_hardware

Add so3g as requirement

---

sotodlib/flag_utils.py

This function uses the native stats function built into the `RangesMatrices` to plot the cut fractions for a given tod.

Add function for plotting flag statistics.

---

sotodlib/hwp/g3thwp.py
sotodlib/site_pipeline/update_hwp_angle.py

Instead of a single frame for each file it processes.
Also added a "--file" option to force reprocess something.
This makes it possible to load short segments of the output ~efficiently.

update-hwp-angles writes 60s frames

---

sotodlib/hwp/g3thwp.py

I was pointed out that update_hwp_angle.py has stopped in the middle of the process.
I modified some exception handlings, and also I fixed rotation direction handling.

Fixing exception handling and others

---

sotodlib/io/g3tsmurf_utils.py

Adds `add_detmap_info()` to `g3tsmurf_utils` to add relevant info using a detmap to an AxisManager.

Add wafer info

---

sotodlib/site_pipeline/make_focal_plane.py

First pass at make focal plane.
One thing to note (with more details in comments in the code) are that I made some assumptions about the format of my inputs that aren't currently true. Feedback on whether or not it makes sense to assume these things (or if I should load in this information in a different way) is much appreciated.
There are also a couple of features that I have kinda implement but not fully: outlier detection, more complex priors, and applying the optics model.
Outlier detection is partially tested but my main pain point there is what to do with the outliers. Do I add another field to the AxisManager that contains a mask for them? Or is better to just forgo it at this step and instead just include the likelihood for each `readout_id -> det_id` match and let the stages down …

Make focal plane

---

sotodlib/mapmaking.py
sotodlib/toast/ops/mlmapmaker.py
sotodlib/toast/ops/sim_hwpss.py
tests/test_detdb.py
workflows/toast_so_sim.py

Trivial fixes emerging from new scan strategy simulation runs.

Toast3 fixes

---

docs/site_pipeline.rst
sotodlib/site_pipeline/make_det_info_wafer.py
sotodlib/site_pipeline/make_read_det_match.py

Added logger handler and made bug fixes related to Detmap for these two functions to run (with logs). Verified they can also be re-run using the overwrite argument, related to this issue: #311 .

Bug fixes to make_det_info_wafer and make_read_det_match

---

sotodlib/io/bookbinder.py
sotodlib/io/imprinter.py
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/make_book.py
sotodlib/site_pipeline/update_book_plan.py

This PR includes several improvements / bug fixes to the existing imprinter + bookbinder stack:
- support passing readout_ids from imprinter to bookbinder and use them in the books 
- allow more parameters in bookbinder to be passed in as arguments
- use G3File instead of smurf_reader in bookbinder
- fix M_index.yaml time units
- several small bugfixes to get bookbinder and imprinter flows working on simons1

Bookbinder update

---

sotodlib/toast/ops/sim_source.py
sotodlib/toast/ops/sim_sso.py

When allow_none=True, and with a @validate function, the None case needs to be specifically addressed.

toast/ops: fix some None checks on traitlets

---

sotodlib/io/imprinter.py

This PR includes the following minor changes to imprinter
- fix a bug in `update_bookdb_from_g3tsmurf`
- improve logging of imprinter, allow custom logger from prefect
- better exception handling for readout_id missing problem

imprinter update

---

sotodlib/toast/ops/sim_sso.py

This PR solves a long-outstanding request to account for the planet angular diameter in simulating SSO signal. It is enabled with a simple argument: `--sim_sso.finite_sso_radius`. If simulation is run without this option _and_ the planet solid angle is over 10% of the beam solid angle, a warning is produced but the execution proceeds.
If the beam modelers agree, we can make this option the default.

Full working version

---

sotodlib/io/load.py
sotodlib/io/load_toast_h5.py

To test this requires a context.yaml ... will place script in pwg-scripts in a moment.

io: context-compatible loader for toast3 HDF5 format TOD

---

sotodlib/coords/planets.py
sotodlib/coords/pmat.py
sotodlib/core/axisman.py
sotodlib/core/metadata/loader.py
sotodlib/tod_ops/filters.py

Happy for comments but these are pretty minor.
Bug fix:
- planets: handle pixell's new non-tuple Geometry object
Tidying:
- metadata loader: clean up how errors are presented
- AxisManager: pre-check for conflicting keys when merging
- tod_ops.filters: add some logger.infos

Random minor fixes

---

tests/test_bookbinder.py

Forgot to update these in commit 3ceaa4e

Bookbinder: Update function name in unit tests

---

sotodlib/core/axisman_io.py
tests/test_core.py

Following some discussion from #119 this adds the ability to save/load AxisManagers with Quantities wrapped (which seems to be the only thing that wrapping Quantities breaks). I don't think this closes that issue since the task of adding in SO specific units that was started in [this branch](https://github.com/simonsobs/sotodlib/tree/add_units) may be incomplete.

Added ability to serialize quantities

---

sotodlib/io/imprinter.py

This PR includes various small changes to imprinter to work with the timing updates. This completes the last missing piece of #357. Also fixes point 4 in #388.

Imprinter: add support for timing system and its fallback

---

sotodlib/io/bookbinder.py
sotodlib/io/imprinter.py

This PR adds a new function to the imprinter that takes in an obs book (assuming a timing system), and returns a full gap-less list of timestamps that should be contained in the book.
This only takes 15 seconds to run for a 2 hour run for a two-hour timestream and I think could both:
-  simplify the gap-filling logic of the bookbinder, and allow for frame pre-allocation which may speed up current run-times
- Help the bookbinder determine whether there are missing samples at the start/end of files and frames
Relevant: #353

`get_book_times` helper function

---

sotodlib/io/imprinter.py

Changes dt in get_book_times from mean to median.

Changes gap dt from mean to median

---

sotodlib/site_pipeline/preprocess_tod.py
sotodlib/tod_ops/fft_ops.py

I found several errors / small bugs in the preprocess script while testing things on SAT data. This will at least fix the ones I encountered.

Edge cases and errors found while grouping preprocess tod

---

docs/preprocess.rst
docs/site_pipeline.rst
sotodlib/site_pipeline/cli.py
sotodlib/site_pipeline/preprocess_tod.py

Updates to `preprocess_tod` so that it can be used in an automated analysis setup. Big things are adding an entry point / argparser that looks for observations in Context that don't have matching entries in the preprocessing archive.

Preprocess updates

---

sotodlib/core/context.py
sotodlib/io/load_book.py
tests/test_context.py

Fix book loader

---

sotodlib/io/bookbinder.py

bookbinder: end_time -> stop_time

---

sotodlib/core/context.py
sotodlib/core/metadata/loader.py
sotodlib/core/metadata/manifest.py
sotodlib/io/load_book.py

Oops, should put that det_info into aman.det_info, not into root level.

context: bug-fix recent det_info changes

---

.readthedocs.yaml

This should fix the docs builds that broke recently.

Update to newer python version in readthedocs

---

sotodlib/hwp/g3thwp.py

I added time zone check for datetime input arguments in g3thwp, setting timezone to utc with logger.warning if there is no timezone info.
https://github.com/simonsobs/sotodlib/pull/469#issuecomment-1551701763

Adding timezone check to G3tHWP

---

sotodlib/io/load_smurf.py

I missed that these queries would not be backwards compatible for older databases.

Restore backward compatibility on Tuneset naming

---

docs/context.rst

Basic example of including time-ordered data vectors as metadata.

Another metadata example

---

docs/coords.rst
sotodlib/coords/focal_plane.py
sotodlib/site_pipeline/make_focal_plane.py

Module to generate focal plane from physical optics, this is just the LAT for now. I need to touch base with SAT optics folks about SAT optics again (but it should be simpler than the LAT).
One question I did have was if the corotator angle would be something that will be nominally loaded into the axis manager for LAT data (I assume yes)? And if we had a standardized name for it so I can have this code pull it from the aman by default.

Focal plane coords

---

workflows/toast_so_sim.py

Trivial modification of toast_so_sim.py that requires no review.

Report the number of selected detectors

---

sotodlib/coords/focal_plane.py

Turns out it had been a long time since I updated scipy and `interp2d` is old news. This is just an update to the newer `bisplrep` and `bisplev` functions.

Updated focal plane coords to newer 2d interp

---

sotodlib/toast/ops/sim_catalog.py
sotodlib/toast/ops/sim_source.py
sotodlib/toast/ops/sim_sso.py

Pick the correct branch for source-centric coordinates

---

sotodlib/flags.py
tests/test_flags.py

As discussed on slack this uses slope instead of max-min to find trending detectors.
The value for `max_trend` is from a quick look at some data from last year. As I look at the data from the most recent LATR cooldown I will refine the default.

Trending slopes

---

sotodlib/io/bookbinder.py
sotodlib/io/imprinter.py
sotodlib/site_pipeline/update_book_plan.py

Example M_index file from a hk book:
```
book_id: hk_16866_ocs3
start_time: 1686600000.0
stop_time: 1686699999.0
telescope: ocs
tube_slot: '3'
type: hk
```

hk book types

---

sotodlib/io/imprinter.py

- imprinter db schema change to make book status comparison easier: use sequential integers to represent different stages of bookbinding, starting from 0 for unbound, to 2 for bound, and then to 3 for when it is uploaded to librarian, and then to 4 when level 2 files are removed, that's when the record can be safely removed from the database, if necessary.
- also includes some utility functions to answer questions like till what time are all book bound, etc.

Imprinter db schema update

---

docs/g3tsmurf.rst
sotodlib/io/g3thk_db.py
sotodlib/io/g3thk_utils.py
sotodlib/io/imprinter.py
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/cleanup_level2.py
sotodlib/site_pipeline/cli.py
sotodlib/site_pipeline/make_book.py
sotodlib/site_pipeline/update_g3tsmurf_db.py

Automated tools for deleting level 2 files that have already made it into books. 
Currently running on the e2e system. 
It's been running for ~48 hours now and I've been finding edge cases that are now fixed. I believe we've now had every time of book made correctly w/ correctly deleted level 2 data (modulo some errors in how the the file emulators are running).

Level 2 file Deletion

---

sotodlib/io/g3thk_db.py

Updated the empty docstrings for the classes that define the tables in the HK database for improved documentation.

G3thk docstrings update

---

sotodlib/site_pipeline/update_obsdb.py

Needed to reorganize how some functions were named / called to get this script working through the site pipeline command line interface. I think this is the preferred format?

Change format to CLI interface works

---

sotodlib/io/g3thk_utils.py

Catch pysmurf-monitor checking edge case

---

sotodlib/io/imprinter.py

Tested the previous PR on the LAT books but not the site ones. Now this works with site books as well.

One imprinter bug fix

---

sotodlib/io/imprinter.py
sotodlib/site_pipeline/update_book_plan.py
sotodlib/site_pipeline/update_g3tsmurf_db.py
sotodlib/site_pipeline/update_librarian.py

Adds function for upload successfully bound books into the librarian. This has been tested on the site system.
I also added book count monitoring to the grafana influx db

Add Librarian Upload

---

sotodlib/site_pipeline/update_book_plan.py
sotodlib/site_pipeline/update_librarian.py

pass logger to imprinter

---

sotodlib/io/bookbinder.py

Fixes #553 
Tested on site books

fix boresight keyword check

---

sotodlib/io/load_book.py

Make load_book_file(..., samples=(tuple)) work

---

sotodlib/io/imprinter.py

One error from branch merged last night

Only run check books on detector books

---

sotodlib/mapmaking/__init__.py
sotodlib/mapmaking/bench.py
sotodlib/mapmaking/log.py

With the addition of these scripts, you can now run the [mapmaker script](https://github.com/simonsobs/pwg-scripts/blob/master/pwg-pmn/simple_ml_mapmaker/mapmaker.py) by just importing functions from `sotodlib`. The mapmaker script will just need minor name changes within it, when we bring it into `site-pipeline`.

Adding bench and log to mapmaking module

---

sotodlib/hwp/g3thwp.py

I have checked the HWP site highbay cooldown data (SCR1). 
There are relatively large number of packet drops compared with lab. data. 
This required additional exception handling and debugging of packet drop filling in G3tHWP.
Specifically, the following functions have been added and modified:
_process_counter_index_reset
_fill_dropped_packets
I have verified that the angle output is stable even with packet drops at least SCR1 (timestamp until 1692000000). 
Once HWP rotates, I plan to check the latest SATP1 data as well.
(FYI: IRIG timing shift is fixed from Oct. 11th)

g3thwp debug with SCR1 data

---

sotodlib/toast/scripts/so_sim.py
sotodlib/toast/workflows/job.py
sotodlib/toast/workflows/pointing.py
sotodlib/toast/workflows/proc_mapmaker.py
sotodlib/toast/workflows/proc_noise_est.py
sotodlib/toast/workflows/sim_atm.py
sotodlib/toast/workflows/sim_observe.py
sotodlib/toast/workflows/sim_sky.py

Cleanups after more extensive testing.  One corner case still being worked on.

Small fixes for problems introduced by refactor.

---

sotodlib/hwp/g3thwp.py

Changed default instance name of g3thwp for site data.
Modified g3thwp to handle both site-data and lab-data instance name conventions.

adjusted instance name of g3thwp

---

sotodlib/site_pipeline/update_obsdb.py

Fixed errors in the codes for start/stop labels so now we can get duration properly. Wrote some hardcoded labels for detectors, but needs polishing.

Fixes for time, duration, and detector/tube labels

---

setup.py
sotodlib/toast/scripts/so_sat_transfer.py
sotodlib/toast/workflows/job.py
sotodlib/toast/workflows/proc_demodulation.py
sotodlib/toast/workflows/proc_flagging.py
sotodlib/toast/workflows/proc_mapmaker.py

The transfer function workflow is not yet ready, but harmless to include.  There are several small critical workflow fixes included.

Workflow fixes and skeleton of SAT early science transfer function workflow

---

sotodlib/toast/workflows/proc_demodulation.py

Small fix to select the noise model passed to the demodulation operator (either estimated, loaded from files, or the nominal elevation weighted one).  The demodulation operator then creates the demodulated noise model.

Select input noise model to be demodulated

---

sotodlib/coords/det_match.py

Bugfix from last commit of the det-match PR.
Also adds a utility function that can be used to load a resonator set from a context that contains det_cal metadata.

Detmatch bugfix and from_ctx constructor

---

sotodlib/hwp/g3thwp.py

gethwp: fix typo in counter index reset

---

sotodlib/site_pipeline/check_book.py
sotodlib/site_pipeline/update_obsdb.py

Decided to go back and update boresight / other columns from the beginning of the SATp1 cooldown and _really_ wanted it do go in time order. 
And then started passing a logger around to make it quiet up a bit.

Sort bookcart

---

sotodlib/coords/pmat.py

The so3g "threads" should be treated as a list of RangesMatrix.

coords: minor fix to bilinear projection support code

---

sotodlib/hwp/g3thwp.py

Sometimes house keeping data gets duplicated.
This issue has happened in satp3 in December, and we also had this issue in one of the UTokyo HWP testing
observation id `obs_ufm_mv5_1703041906` is one of the example.
This is the slack link when we found this issue: https://simonsobs.slack.com/archives/C034C6WQEHH/p1703098228029259
To handle this issue, I added a process to remove the duplication in hk data.
We had a similar process for IRIG data (`_irig_quality_check`), so I changed the order of processes to make it easy to separate the issues in data.

g3thwp: correct duplication of hk data

---

docs/conf.py
docs/requirements.txt

Pulling Max's changes into a separate PR

fix sphinx version and intersphinx_mapping

---

docs/tod_ops.rst
sotodlib/flag_utils.py
sotodlib/tod_ops/jumps.py
tests/test_tod_ops.py

Improvements to the algorithm to get more jumps on the first pass and performance improvements.

Jump improvements

---

.github/workflows/test.yml
docs/toast.rst
sotodlib/core/context.py
sotodlib/core/metadata/loader.py
sotodlib/io/load_toast_h5.py
sotodlib/toast/__init__.py
sotodlib/toast/io/load_book.py
sotodlib/toast/io/save_book.py
sotodlib/toast/ops/__init__.py
sotodlib/toast/ops/act_sign.py
sotodlib/toast/ops/corotator.py
sotodlib/toast/ops/h_n.py
sotodlib/toast/ops/load_books.py
sotodlib/toast/ops/load_context.py
sotodlib/toast/ops/mlmapmaker.py
sotodlib/toast/ops/sim_hwpss.py
sotodlib/toast/ops/sim_source.py
sotodlib/toast/scripts/so_map.py
sotodlib/toast/scripts/so_sim.py
sotodlib/toast/workflows/__init__.py
sotodlib/toast/workflows/data.py
sotodlib/toast/workflows/job.py
sotodlib/toast/workflows/proc_act.py
sotodlib/toast/workflows/proc_intervals.py
tests/test_toast_books.py
tests/test_toast_context.py

General interface for parallel loading of context data into a toast observation.  Does not yet include hook for running pre-processing on load.  Still missing a roundtrip unit test.

Loading context data into TOAST

---

sotodlib/tod_ops/flags.py

Not instead of tilde slipped through in previous PR. Tested this one and it works to get flag logic right.

Fix not to tilde.

---

sotodlib/toast/workflows/sim_atm.py

This PR brings sotodlib defaults in line with https://github.com/hpc4cmb/toast/pull/723

Update atmospheric defaults

---

sotodlib/io/imprinter.py

I'm amazed we only just found this to be an issue. But the logic was working out that operations for single UFMs that overlap multi-UFM observations were trying to be added to two books at once. This requires all level 2 observations going into obs books to be of type obs.

Remove overlapping operations from multi-ufm observations

---

sotodlib/io/imprinter.py

Changes to sotodlib required for communicating with librarian v2

Librarian Updates

---

sotodlib/toast/scripts/so_convert.py

quick fix for the toast_so_convert script.

Small fix for the toast_so_convert script

---

sotodlib/tod_ops/pca.py

Fix wrap parameter in pca.

---

sotodlib/io/load_book.py

This basically makes it so 'primary' in data frames is not necessary. The returned AxisManagers will lack the primary and biases fields.
This was developed on sims so wait for me to test it on some real books ...

load_book: mods to work better on sim data

---

sotodlib/coords/planets.py

asssert => assert

---

sotodlib/hwp/g3thwp.py

Noticed that all the hwp_angle get zero when pid_direction is not available.
This PR avoids this issue.

debug hwp direction correction

---

sotodlib/coords/pmat.py
sotodlib/mapmaking/ml_mapmaker.py

Looks like I forgot to make a submit this pull request, which adds multipass mapmaking support.

Multipass fixed

---

sotodlib/site_pipeline/analyze_bright_ptsrc.py

Updates 1,3,4,5,7,8,9 from previous issue #479. For the 2nd bullet point of the required updates, an example file is included at https://github.com/simonsobs/pwg-scripts/blob/master/pwg-bcp/sotodlib_staging/data/initial_parameters_fit_pt_src.yaml.  Related to item number 6: does it make sense to simply add a parsing argument for the `detset` argument of `core.context.get_obs()` or do we assume we are completely agnostic as to which wafers/tubes are included in the observation until we load it?

Analyze bright pt src updates

---

sotodlib/tod_ops/jumps.py

Replaces #665 since it looks like most of stuff is already merged.

Jump updates

---

sotodlib/tod_ops/flags.py

Makes det bias flags work when meta is passed. Addresses issue #722

Detflags from meta

---

sotodlib/toast/ops/load_context.py
sotodlib/toast/workflows/data.py
sotodlib/toast/workflows/proc_mapmaker.py

Ensure that processes do not stomp on each other's ramdisk copy of data when loading with moby2

Small improvements for loading ACT data in parallel with moby2

---

sotodlib/io/load_smurf.py

New knob we need to be able to turn sometimes. On the todo list to make it accessible via CLI https://github.com/simonsobs/sotodlib/issues/764

add option to stop observation manually

---

sotodlib/site_pipeline/make_ml_map.py

Closes #774
This PR fixes the import issue @Ankurdev-astro reported. It is replicated on Perlmutter:
```bash
iparask@login34:/pscratch/sd/i/iparask/tmpwork2$ python make_ml_map.py --help
File "/pscratch/sd/i/iparask/tmpwork2/make_ml_map.py", line 373, in <module>
util.main_launcher(main, get_parser)
NameError: name 'util' is not defined. Did you mean: 'utils'?
```
It also removes an unnecessary import because the whole package is imported:
```python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sotodlib import tod_ops
>>> dir(tod_ops)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', …
```

Import fixes for make_ml_map.py

---

sotodlib/site_pipeline/update_obsdb.py

update_obsdb will try to include SAT HWP frequency by default

---

docs/tod_ops.rst
sotodlib/tod_ops/jumps.py
tests/test_tod_ops.py

Slowest routine is now ~7x faster.
~~Needs to have updated docs (including a note on getting better performance) and some correctness checks done before merging.~~
Some profiles here for those interested: `/so/home/saianeesh/data/profiles`
I also have some ideas that should increase accuracy but lets get these speed improvements in the wild first.

Jump speedups

---

sotodlib/tod_ops/fft_ops.py
tests/test_tod_ops.py

Change default nperseg behaviour

---

sotodlib/site_pipeline/update_smurf_caldbs.py

This PR changes the detcal scripts to add `tau_eff` and `v_bias` to the databases, along with a few small quality of life changes.

Update Detcal to add tau_eff and voltage bias

---

sotodlib/site_pipeline/preprocess_tod.py

Add type hinting and a try-catch statement to run through prefect.

Updates to run through prefect.

---

sotodlib/site_pipeline/preprocess_tod.py

Add `update_delay` parameter to restrict lookback time when running through prefect.

Preprocess update delay

---

sotodlib/io/load_book.py

This only affects multi-wafer loads.  The fix also makes the order of detsets, in multi-wafer loads, deterministic.
Bug report from @amaurea .

load_book: fix bug where signal was not ordered properly

---

sotodlib/site_pipeline/preprocess_tod.py

We moved from name -> unpack in context I fixed the dependence on name here.

Fixes dependence on name variable in context

---

sotodlib/coords/pmat.py

https://github.com/simonsobs/sotodlib/issues/763

added focal_plane nan checker in coords.pmat.for_tod

---

sotodlib/site_pipeline/update_smurf_caldbs.py

This PR fixes the bug currently holding up the det_cal prefect script, here: https://prefect.simonsobs.org/flow-runs/flow-run/9528799d-721b-4833-b0a0-e20ad7afc95d
I believe the source of the issue is the same as what's described in https://github.com/simonsobs/site-pipeline-configs/issues/60 is a mismatch between channels in the data file, and channels in the detset. This is likely from some of the timing tests I was doing this week, where I was manually setting the channel-mask, and not using a proper detset. We don't really care about these observations so fine to just add to the failed-obsid cache and move on.
This PR improves a bit how failures are tracked. Instead of the main process catching errors, the `get_cal_resset` function now returns a CalResult object that includes …

Clearer failure tracking in update_detcal

---

sotodlib/obs_ops/splits.py

should be `not(not(wrap))` instead of `not(wrap)`. The function was not wrapping to the aman

Major bug fix, function was not wrapping to aman

---

docs/site_pipeline.rst
sotodlib/site_pipeline/cli.py
sotodlib/site_pipeline/make_cosamp_hk.py
sotodlib/site_pipeline/make_level3_hk.py

I would like to request to make level3 metadata databases for important housekeeping data, such as pwv, mK-stage temperature and wiregrid. I followed the make_hwp_solutions' way to make metadata and sqlite.

Make metadata for important house keeping data

---

sotodlib/toast/ops/__init__.py
sotodlib/toast/ops/splits.py
sotodlib/toast/workflows/__init__.py
sotodlib/toast/workflows/proc_mapmaker.py
sotodlib/toast/workflows/sat.py

- Implement 3 trivial splits to start ("all", "left_going", "right_going").
- An interval list and per-detector cuts are toggled to implement each split.

Add a new Splits operator that runs the mapmaker over each split

---

docs/site_pipeline.rst
sotodlib/site_pipeline/make_cosamp_hk.py

Adding queryable parameters in manifestdb.

Make cosamp hk update

---

sotodlib/site_pipeline/preprocess_obs.py

- Fixes `tags` argument to work with prefect
- Added recent changes made to `preprocess_tod`

Fix preprocess_obs script for prefect

---

sotodlib/tod_ops/filters.py

Fix `UnboundLocalError: local variable 'i' referenced before assignment`
Also fix typo.

debug iir_filter

---

sotodlib/site_pipeline/update_obsdb.py

Look at timestamp of books instead of date of last modification of files.

Change recency criterion for update_obsdb

---

docs/calibration.rst
sotodlib/site_pipeline/calibration/wiregrid.py

I fixed a wrapping issue about the function of correct_wg_angle. Please check it and merge this into master.

fixed a wrapping bug with wiregrid.py

---

sotodlib/site_pipeline/make_hwp_solutions.py

This PR fixes the accidental change from relative path to absolute path in https://github.com/simonsobs/sotodlib/pull/809

abspath -> relpath in hwp_angles database

---

sotodlib/io/hkdb.py

Very small changes to hkdb indexing function so that we have some more logs in prefect. Just adds how many files are being indexed, and changes pb to ascii so it is hopefully more prefect compatible.

Adds some more logs for hkdb indexing

---

sotodlib/preprocess/processes.py
sotodlib/site_pipeline/preprocess_tod.py
sotodlib/site_pipeline/util.py
sotodlib/tod_ops/flags.py

- Added `HWPAngleModel` to preprocess
- Added `select` to `SourceFlags`
- Added optional `rn_range` and `si_nan` parameters to `get_det_bias_flags`
- Added verbosity to `preprocess_tod` and modified `util.init_logger` correspondingly to allow updating handler verbosity

Preprocess tod updates

---

sotodlib/io/bookbinder.py
sotodlib/io/imprinter.py
sotodlib/io/imprinter_cli.py
sotodlib/io/imprinter_utils.py

A small but important fix for finding azimuth / hk data (and additionally error raising for if it can't be found). 
Also add more named errors as a setup for future catching of named errors

Additional Bookbinding error handling

---

docs/site_pipeline.rst
sotodlib/io/so_ufm.py
sotodlib/site_pipeline/make_det_info_wafer.py

Final touches on make_det_info_wafer (doesn't use wafer_map.yaml).

make_det_info_wafer: simplify config file and update docs

---

sotodlib/site_pipeline/analyze_bright_ptsrc.py

From @nad-dch.
I propose we merge this without too much consideration, and add some notes to #736.

updates on analyze_bright_ptsrc to adapt to actual observations

---

sotodlib/toast/scripts/so_map.py
sotodlib/toast/scripts/so_sim.py
sotodlib/toast/workflows/proc_mapmaker.py

This PR replaces #690 that ended up in irreconcilable conflict with the main branch.

Detector maps2

---

sotodlib/toast/ops/splits.py
tests/test_toast_splits.py

Simplify structure of splits and expand docstrings.  Still need to add a unit test.

Cleanup the structure of Split classes

---

sotodlib/toast/ops/splits.py
tests/test_toast_splits.py

Extend the splits operator to support detector cuts

Add inner/outer focalplane split

---

sotodlib/site_pipeline/make_ml_map.py

Following the merge to introduce FlagManagers, the code to generate a mock set of glitch flags in make_ml_map broke. This PR adds a bit of code to incorporate the changes already introduced in PR #891 and adjusts the actual object added to obs.flags to be of correct shape and format.

Fixing the flags object following FlagManager implementation

---

sotodlib/site_pipeline/preprocess_obs.py

- Fix update_delay in preprocess_obs to be same as in preprocess_tod; this likely was causing prefect deployment to not find any recent planet obs
- Also add verbosity as in preprocess_tod

Fix update_delay in preprocess_obs

---

sotodlib/site_pipeline/finalize_focal_plane.py

fix: common mode faking with 2 OTs or UFMs

---

sotodlib/obs_ops/sources.py

- Fix point sources dictionary
- Add check for lengths of vectors

Fix point sources for preprocess_obs

---

docs/site_pipeline.rst
sotodlib/site_pipeline/update_g3tsmurf_db.py

Fix https://github.com/simonsobs/sotodlib/issues/916

Remove obs-id from tags

---

sotodlib/toast/workflows/pointing.py
sotodlib/toast/workflows/sim_atm.py
sotodlib/toast/workflows/sim_observe.py
sotodlib/toast/workflows/sim_optical_pickup.py
sotodlib/toast/workflows/sim_sky.py
sotodlib/toast/workflows/sim_sources.py

Add an independent pointing model to TOAST simulation workflows so we can have a mismatch between simulation and data reduction.

Toast pointing model

---

setup.py
sotodlib/toast/scripts/so_batch_control.py

Moving some logic out of slurm scripts into a simple python helper script.

Add a helper script for testing whether output directories are complete.

---

sotodlib/toast/ops/load_context_utils.py
sotodlib/toast/ops/readout_filter.py

Fix toast iir filter operator, broken by per-stream_id grouping

---

sotodlib/tod_ops/apodize.py

Current apodizer fails when there are many glitches near the start or end of the timestreams. This is because current apodizer only checkes first or last edge of flag.mask(). Fixed this error by simply checking all the edges. Also, we should loop over left edges and right edges independently because the number of left edges and right edges are not always same.
```
could not broadcast input array from shape (200,) into shape (90,)
File "/pscratch/sd/y/ykyohei/so_site/scripts/cmb_process.py", line 127, in hwpss_subtraction
hwp.get_hwpss(aman, flags=flags, merge_stats=False)
File "/global/homes/y/ykyohei/scratch/sotodlib/sotodlib/hwp/hwp.py", line 122, in get_hwpss
hwp_angle_bin_centers, bin_counts, binned_hwpss, hwpss_sigma_bin = get_binned_hwpss(
File …
```

fix apodizer

---

sotodlib/toast/ops/splits.py
sotodlib/toast/workflows/sim_observe.py

Small fixes emerging from the ISO simulations.

Fix toast splits

---

sotodlib/tod_ops/apodize.py
sotodlib/tod_ops/binning.py
sotodlib/tod_ops/sub_polyf.py

My binning was slow just because it loop np.histogram for all detectors.
Modified the binning function to the style with np.bincount, which result in ~2 times faster hwpss and azss calculation.

Faster binning

---

sotodlib/coords/planets.py

Added xi/eta offset in get_scan_q in planets.py in order to take into account off-centered UFMs/detectors.
I only added those offsets so that this version has backward compatibility.
Demonstrations/Discussion using Jupiter observation for satp3 that having dipole T2P leakage from p.6 in https://docs.google.com/presentation/d/1H1T2U94in_STM8gw5q5HR3xolJYrKs4FQfjjAyozsLw/edit?usp=sharing.

Modify planet mapmaker

---

sotodlib/toast/ops/mumux_crosstalk_util.py

Add contributions from detectors of other bandpasses and polarizations to mumux crosstalk model.

Include xtalk from other bandpasses and polarizations

---

sotodlib/io/imprinter_cli.py
sotodlib/site_pipeline/make_book.py

A few more QOL updated for the Imprinter CLI and try and autofix HWP missing errors.

Imprinter CLI updates

---

sotodlib/site_pipeline/update_det_cal.py

Allows you to switch between using multiprocessing "spawn" and "fork" start methods through the config file. Also changes the log-level for successful obs-ids to info.
This should help us debug some problems we're having right now with prefect.

update-det-cal: add ability to set multiprocessing start method

---

sotodlib/tod_ops/flags.py

fix: subtract off starting time during slope calculation

---

docs/site_pipeline.rst
sotodlib/coords/fp_containers.py
sotodlib/site_pipeline/finalize_focal_plane.py

A few updates, mostly convenience stuff for me and some prep to make things run automated down the line

Ffp Updates

---

sotodlib/preprocess/processes.py

Super simple update addressing #709

Add kind key

---

sotodlib/coords/pointing_model.py
tests/test_pointing_model.py

1. Added fp_offset xi and eta parameters
2. Changed name of bs_xi0 bs_eta0 to fp_rot xi and eta
3. All parameters with units now fit in radians
4. Added capability to fit for Az Rotation

Update to Pointing Model sat_v1

---

sotodlib/coords/demod.py
sotodlib/hwp/hwp.py
sotodlib/preprocess/processes.py
sotodlib/tod_ops/azss.py
sotodlib/tod_ops/pca.py

Added functions that are useful for estimating common mode of demodulated timestreams.
We had local discussions that implementing these functions and making plots of the common mode of demodulated timestreams will be useful for monitoring data quality.
Example plots. https://site.simonsobs.org/~ykyohei/satp3_tod_spectrum/gallery.html

Demod common mode

---

docs/context.rst
docs/tod_ops.rst
sotodlib/coords/helpers.py
sotodlib/coords/pmat.py
sotodlib/core/context.py
sotodlib/core/metadata/loader.py
sotodlib/flag_utils.py
sotodlib/io/load.py
sotodlib/io/load_toast_h5.py
sotodlib/tod_ops/filters.py
sotodlib/tod_ops/pca.py
tests/test_tod_ops.py

This is an omnibus of minor fixes I've been accumulating for, alas, literally years... highlights:
- pca cov code accepts a mask for downweight certain dets
- obsfiledb.prefix can be set through context.yaml file
- a simple "gain" filter
- wcs care in Pmat

Minibus of fixes

---

sotodlib/core/axisman_io.py
tests/test_core.py

This resolves https://github.com/simonsobs/sotodlib/issues/1016

Save and load RangesInt32

---

sotodlib/preprocess/preprocess_util.py

Fix the missing preprocess_util loggers bug introduced in #1027.

fix missing preprocess logger

---

sotodlib/preprocess/preprocess_util.py

Some fixes for the preprocess_util functions.

fix missing h5 import

---

sotodlib/preprocess/processes.py

This branch reworks the `calc_psd` handling in the preprocessing `PSD` pipeline stage.  Previously, the PSD calculation was carried out in the `process` function and wrapped into the axis manager.  When running the full pipeline, it was also wrapped into the processing axis manager, resulting in two copies.  The PSD would also be recomputed when loading from an existing database.
The `calc_psd` function has been moved into `calc_and_save` now so that it is only wrapped into the processing axis manager.  A slight change was made to the `Noise` stage as it expects the PSD to be present, so it now looks into the processing axis manager.  I didn't change the underlying behavior in `fit_noise_model` which will recompute the PSD and wrap it into the axis manager if the `PSD` is not an input.

Move PSD calculation to calc_and_save

---

sotodlib/preprocess/preprocess_util.py
sotodlib/site_pipeline/multilayer_preprocess_tod.py
sotodlib/site_pipeline/preprocess_tod.py

Fixes an issue with error logging when preprocessing failed and returned a list of [obsid, error].  Also added some more debugging statements to `cleanup_mandb` to help track some failure cases.

Fix error logging

---

sotodlib/io/hkdb.py

Small QOL update to properly instantiate HkConfig object from a dictionary.

Add from_dict method to HkConfig

---

sotodlib/toast/ops/load_context.py
sotodlib/toast/ops/load_context_utils.py

- Improve efficiency of obsdb queries when distributing multiple observations among process groups.
- Handle the case where a preprocessing pipeline is run on load, and some samples are truncated.

Fixes to toast context loading

---

sotodlib/io/hkdb.py

Resolves https://github.com/simonsobs/sotodlib/issues/1105.

HkDb: sort paths before loading frames

---

sotodlib/preprocess/processes.py

I would like to have these for source mapmaking using preprocess module. I tested these.
Also fixed some typos in PTPFlags and InvVarFlags.

add pca filters to preprocess

---

sotodlib/hwp/hwp.py

I tried to simplify this function to be modular #1102.
Now this function only estimates `hwpss_model` and we use `subtract_hwpss` for subtraction.
I removed iteration part because I think the iterative subtraction should be implemented by calling same function several times.
There is a difference in the treatment of turnaround, so please check.

simplify hwpss_subscan

---

sotodlib/coords/planets.py

Added an option to make pointing matrix for receiver fixed beam measurement.
Added explanations of some use cases in docs.
The sign of roll correction was validated through satp1 dipole T2P measurement by juputer.

pmat for receiver fixed beam measurement

---

sotodlib/core/axisman.py
tests/test_core.py

Because https://github.com/numpy/numpy/issues/16377

Fix axisman.concat to merge string fields properly

---

.github/workflows/monthly_releases.yaml

We want the whole history for this action. The checkout job pulls everything and prints also the old and new version.

Action pull all history

---

.github/workflows/test.yml
tests/test_metadata.py
tests/test_obsdb.py

Fix sqlite single quotes in tests.  Expand test matrix to include python-3.12 and macos.

Fixes to unit tests under python-3.12

---

sotodlib/core/metadata/obsfiledb.py

so-metadata script (fix-db) can be used to add this index, in situ.
Thanks to @JBorrow
Resolves #1123

obsfiledb: v3, with index on obs_id and detset

---

sotodlib/hwp/hwp.py
sotodlib/tod_ops/filters.py

A fix to address #1142 and correct the docstring for demod_tod().

Fix butter4 bandwidth filter

---

sotodlib/obs_ops/__init__.py
sotodlib/obs_ops/utils.py
sotodlib/preprocess/processes.py

This should be a temporary solution for this issue but it's helpful to have..

correct missing iir_params

---

sotodlib/preprocess/processes.py
sotodlib/tod_ops/azss.py
tests/test_azss.py

resolve azss part of iso-sat-review branch.

Iso sat resolve conflict

---

sotodlib/toast/ops/sim_source.py
sotodlib/toast/workflows/sim_sources.py

The PR finally solves the issue for drone scan size. Now the argument is required

Fixes to drone simulation range

---

sotodlib/tod_ops/jumps.py

Fix slicing of std_est https://github.com/simonsobs/sotodlib/issues/1154

fix jump.std_est

---

sotodlib/mapmaking/ml_mapmaker.py
sotodlib/toast/ops/mlmapmaker.py

The srcsamp is implemented but has not been tested yet.
The multipass needs to be updated. One pass works fine, but it will break at the second pass.

implementing the latest changes on the ml mapmaker to the toast operator

---

sotodlib/hwp/g3thwp.py

This makes hwp-make-solutiuons numpy 2 compatible https://github.com/simonsobs/sotodlib/issues/1174
Tested by numpy 2.2.4

fix numpy2 compatibility of hwp-make-solutiuons

---

sotodlib/coords/planets.py
tests/test_coords.py

feat: more flexible formatting for source names

---

sotodlib/toast/ops/sim_source.py

It is a quick modification of the drone operator to allow starting azimuth and elevation

added traits for azimuth and elevation starting point of the drone

---

docs/metrics.rst
sotodlib/site_pipeline/record_qa.py

Changes requested in today's site pipeline call.
I haven't tested these, but they are pretty minimal. If the implementation looks ok we could test it out.

Changes to handling of errors in `record_qa`

---

sotodlib/hwp/g3thwp.py

Add special fix for irig desynchronization problem. This is tested to reproduce corrected hwp_angle solution.
We specify the period and constant time offset in site-pipeline-configs/satpX/hwp_config.yaml.
Companion PR: https://github.com/simonsobs/site-pipeline-configs/pull/125
This correction was validated by hwpss angle study and Tau A map.

hwp_angle solution; Add special fix for irig desynchronisation problem

---

sotodlib/tod_ops/flags.py

This PR adds rn_flags if we pass `full_output = True` in flags.py.

add rn_flags in full_output

---

sotodlib/preprocess/processes.py

Addresses: https://github.com/simonsobs/sotodlib/issues/1202
Just add an example config for subtractHWPSS in preprocess.

add example config for subtractHWPSS in preprocess

---

sotodlib/preprocess/processes.py

Allow glitches to be saved into fields with names other than `glitch_flags`

Update glitches to allow unique names.

---

sotodlib/preprocess/processes.py

Adds to t2p example config entry the flag_name field.

Add flags to t2p docs.

---

sotodlib/preprocess/processes.py

This PR adds new function of intersect flags. This function is useful for planet mapmaking because we want to do preprocess outside of planet mask. Intersect flags from inversed source_flags and something can be used for this situation.
I checked that intersect flags is as expected

add intersect_flags

---

sotodlib/preprocess/processes.py

Fix issue with recent AzSS Updates w.r.t. skip_on_sim behavior.

Update AzSS method to default sim=False.

---

sotodlib/io/imprinter_cli.py
sotodlib/site_pipeline/update_g3tsmurf_db.py

I missed a lot of selfs in imprinter-cli and need to strip whitespace from the g3tsmurf error cheching

Bug fixes for Data Packaging

---

sotodlib/preprocess/processes.py

Another backwards compatibility thing we didn't catch in the big noise model update PR.

Fix indexing of noise model.

---

sotodlib/preprocess/processes.py

Fix aman and proc_aman unequal restriction.

---

sotodlib/preprocess/processes.py

A few processes are missing sim=False argument in process step.

Fix correct iir

---

sotodlib/core/axisman_io.py

Adds compatibility for https://github.com/simonsobs/so3g/pull/213

perf: skip shape check when expanding ranges matrix if possible

---

sotodlib/toast/ops/h_n.py
sotodlib/toast/ops/splits.py

This makes some small changes to handle upstream toast API changes for map-domain I/O.  This should not be merged until the following PRs are merged:
https://github.com/hpc4cmb/toast/pull/836
https://github.com/hpc4cmb/toast/pull/828
and a toast tag includes those changes.

Update `toast.pixels.PixelsData` API

---

sotodlib/preprocess/preprocess_util.py
sotodlib/preprocess/processes.py

Small fixes that guarantee simulation filtering is working for ISO v2.

Sim filtering iso v2

---

sotodlib/toast/ops/load_context.py
sotodlib/toast/ops/load_context_utils.py
sotodlib/toast/workflows/__init__.py
sotodlib/toast/workflows/proc_filters.py
sotodlib/toast/workflows/scripting.py

This adds logic to insert the preproc archive in the live config.  It also ensures that the hwp model is only applied once.

Changes to better support SAT reduction with toast

---

sotodlib/site_pipeline/make_hwp_solutions.py

Add mpi option to run make_hwp_solution in both site computing and data center.

mpi option for make_hwp_solution

---

sotodlib/io/hkdb.py
sotodlib/site_pipeline/cli.py
sotodlib/site_pipeline/update_hkdb.py

Introduces a more powerful CLI to help with hkdb inspection and repair.

update-hkdb expansion

---

sotodlib/site_pipeline/generate_reports.py

Puts `generate_reports` main function handling in line with other `site-pipeline` scripts to make it work with `Prefect`.

Update generate_reports main

---

sotodlib/coords/planets.py
tests/test_coords.py

Requires interface change to _get_astrometric.  Updated tests.
Resolves #1299

Fix planets.get_source_azel

---

sotodlib/site_pipeline/make_hwp_solutions.py

This is necessary to fix the prefect flow failure https://prefect.simonsobs.org/flow-runs/flow-run/ba0a2b28-5012-40a5-91ef-d9a848e217b5 Same solution as https://github.com/simonsobs/sotodlib/pull/1237

fix main function of make_hwp_solutions

---

sotodlib/qa/quality_reports/plots.py
sotodlib/site_pipeline/generate_reports.py

Fix for interpolation to allow for more fields (hwp, wiregrid) to be plotted in the efficiency plot.

Generate reports fix to allow extra target plotting

---

sotodlib/coords/fp_containers.py
sotodlib/site_pipeline/finalize_focal_plane.py

* fix: restore ability to pad output when we have no data
* feat: add R2 cut
* feat: make hits cut >= and log the number of used obs
* feat: add config and git hash to output
* feat: add cut on min dets and stream ids when getting list of obs ids
* feat: get tel-ot-ws-sid mapping from context
* feat: add ability to modify focal plane file in place, lots of minor dataclass edits for this
This also is making me realize that as the scope of this code has changed and features have been added the code is becoming messy, I will plan a cleanup/refactor when I get time.

Finalize focal plane: reveral fixes and streamlining features:

---

sotodlib/toast/ops/__init__.py
sotodlib/toast/ops/dark_template.py

TOAST operator to construct and subtract dark bolometer templates from optical bolometers.

Toast dark template

---

sotodlib/hwp/g3thwp.py

This PR fixes the bug of offcentering correction.
offcentering correction is done by taking average of two encoder data. Previous method was not making sure that two encoder data are aligned in time domain. In some observations (~20), previous correction was taking average of different rotations and leading to incorrect ver3 hwp angle. This was not introducing major issues in observations with constant speed, but this was introducing non-negligible bias in spin up observations.
Details: https://simonsobs.atlassian.net/wiki/spaces/PRO/pages/1248657450/Tau+HWP+debug#250922-validation-of-offcenter-fix
Since the number of observations affected by this issue is small, I plan not to update metadata version. I plan to re-run the solution for those observations.

Fix edge cases of hwp offcenter correction
