simonsobs/sotodlib

sotodlib/hardware/config.py

This pull request adds a necessary keyword to the select() method example. It also formats config.py with black.

Fix select() example

---

sotodlib/hardware/config.py

I noticed that the current `get_example` doesn't index the crates / cards for the readout system like we'd expect. Crates can't be split between different telescopes. 
This update splits the crates by telescope and makes sure the cards in a crate all come from wafers in the same telescope.

change crate and card indexing to match hardware plan

---

pipelines/make_hardware_maps.py
pipelines/toast_so_sim.py

This PR introduces a pipeline script to generate nominal and perturbed hardware configurations.
The perturbation means that detectors can no longer reference the band-averaged NET, fknee, bandwith etc. Instead, the script adds these parameters to the individual detector dictionaries. I have checked that these additional keywords get saved in the output TOML files and become available to future scripts that load the modified TOML file.

Per-detector bandpass and noise parameters

---

pipelines/toast_so_sim.py

Check the command line help for the default string that should be used for the simulations.
This requires:
* TOAST 2.3
* PySM 3 integration https://github.com/hpc4cmb/toast/pull/277
* PySM 3 master from https://github.com/healpy/pysm
* so_pysm_models from https://github.com/simonsobs/so_pysm_models
This is currently untested, I'll work on testing this in the next couple of days.

support custom SO models for PySM 3

---

pipelines/toast_so_example.py
pipelines/toast_so_sim.py
sotodlib/data/toast_export.py
sotodlib/data/toast_frame_utils.py
sotodlib/data/toast_load.py
tests/test_toast_load.py

This PR modifies the TOAST/so3g facilities to
* support breaking the so3g files by wafer, card or other detector characteristic listed in the hardware configuration
* support FLAC compression of the G3TimeStreams. The compression requires casting the floating point-valued TOD into integers. The `recode` method determines the optimal gain and offset to meet the desired number of significant bits within the TOD RMS. The applied gain and offset are recorded in the so3g file and used when decompressing the TOD.
* support loading all flavors of the TOD recorded in the so3g file
* fix a bug in recording the time stamps in the so3g files and add missing method to expand them into the TOAST cache upon load
* Fix a bug in not propagating the common flag mask from `ToastExport` all the way to …

Per wafer datadump

---

docs/intro.rst

Uses pip to manage the package directly. Useful when in the future there are other dependencies. See e.g. <https://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop/30306403>

intro.rst: use pip instead of setup.py directly

---

sotodlib/pipeline_tools/pysm.py

`so_pysm_models` has 2 versions for each model,
e.g. `SO_d0` is the same as PySM 2, `SO_d0s` has small scales signal added.
We want to automatically select the models with small scales if we are running at high nside

Automatically select the models with small scales if we are simulating high nside

---

sotodlib/data/toast_frame_utils.py

@mhasself noticed that the exported so3g files have the wrong Azimuth convention (#44). Initially I thought there was an error in the TOAST internal convention but it turns out we just need to invert the `phi` angle when translating the horizontal quaternions into Az/El. The TOAST internal conventions are fine.

Invert phi to get azimuth in export

---

sotodlib/utils/pipeline_tools/observation.py

This PR fixes a bug concerning the noise PSDs. It caused the same instance of noise PSD to be shared across observations. When applying the elevation factors, those factors got multiplied, causing a several percent excess in the simulated noise levels.

Make sure the observations get independent instances of the noise PSD

---

sotodlib/tod_ops/filters.py

This aims to address issue #77. docstrings and function signature are now borrowed from the wrapped filter functions.

tod_ops.filters: add docstr and signature for fft_filter decorator

---

docs/index.rst
docs/tod_ops.rst
sotodlib/tod_ops/__init__.py
sotodlib/tod_ops/pca.py

Provides principle component analysis routines, in the AxisManager framework.  This helps with high quality gap filling, and atmosphere cleaning in contexts such as map-making of compact sources (instead of common mode filtering, you remove several strong eigenmodes).
One thing I'm not thrilled about is the name of the "eigen" axis.  I would want to call that "modes", but modes is the name of the array that holds the modes.  The general idea of having a small number modes, along with individual couplings to each detector signal, is useful even outside PCA / eigen-decompositions.  E.g. for polynomials, or mean/trend (as in get_trends defined here).

tod_ops.pca

---

docs/tod_ops.rst
sotodlib/tod_ops/__init__.py
sotodlib/tod_ops/gapfill.py

Introduces simple polynomial (linear, really) gap filling, as well as "model-based" gap-filling that can use the results of a PCA (or common mode).
The Extract and ExtractMatrix classes (the later of which is not quite compatible with storage in AxisManager, but could be moved in that direction) help with storing sparse subsets of a TOD signal efficiently.

tod_ops: gap-filling

---

pipelines/toast_so_sim.py
sotodlib/io/toast_frame_utils.py
sotodlib/modules/__init__.py
sotodlib/modules/demodulation.py
sotodlib/utils/pipeline_tools/__init__.py
sotodlib/utils/pipeline_tools/demodulation.py
sotodlib/utils/pipeline_tools/export.py

This PR implements a TOAST demodulation operator. It processes the HWP-modulated signal, pointing, timestamps, noise PSDs and flags into demodulated and downsampled vectors. The process is irreversible, so it is not possible to perform Monte Carlo loops that involve demodulation.
A low pass filter used in demodulation is set automatically, but it is possible to control the filter width and set the window function.
For the time being, flags, pixel numbers and timestamps are simply sampled from the full resolution vectors. A more advanced approach may be developed later.

HWP demodulation

---

.github/workflows/run_tests.sh
tests/test_hardware.py

Running the tests in this branch locally takes about 20s on my laptop:
```
python setup.py test
<snip>
Ran 39 tests in 20.255s
OK
```
If I disable plotting, I get:
```
SOTODLIB_TEST_DISABLE_PLOTS=1 python setup.py test
<snip>
Ran 39 tests in 10.738s
OK
```
Is this acceptable?  If so, then this closes #62

Reduce size of simulated hardware test.

---

docs/coords.rst
sotodlib/coords/helpers.py
sotodlib/coords/pmat.py

Summary of improvements:
- Simpler rules for how coords.P processes arguments and what is cached / not cached.
- Passing wcs_kernel=  causes get_footprint to be called to populate self.geom.
- Speed up weights matrix inversion and application.
- Complete documentation of P methods.
This work was done in parallel with developing a compact source mapmaker and refining the unbiased mapmaker.  The pwg_tutorial on coords still works... unbiased mapmaker works, with minimal modifications.
Please post any reviews / comments within 1 week.

Refactoring of Projection Matrix

---

.github/workflows/install_deps.sh
docs/tod_ops.rst
sotodlib/tod_ops/detrend.py
sotodlib/tod_ops/fft_ops.py
sotodlib/tod_ops/filters.py
tests/test_tod_ops.py

Key changes:
- New tests, covering some (but not much) of tod_ops module.
- The fourier filter framework also exposes an "apply" method, that can be faster in some applications.
- fourier_filter will pad to any nice FFT number, not necessarily 2^n.
- New names for timeconstant (de-)convolution filters; deprecates "tau_filter".
- Made some important filter arguments non-optional; better arg names.
- More docs.

Filter upgrades

---

sotodlib/io/load_smurf.py

This PR adds support for multiple Stream-id's when loading data. In order to not mess up existing analysis functions, I'm keeping it as simple as possible for the time being. 
If no stream_id is provided, default behavior is to first check if there are multiple stream_ids in the specified range. If there's only one ID, it'll load the data like before, and if there are multiple it'll throw an error. If a stream_id is specified, it'll only query files that have that stream_id.
If we want to add a way to load multiple stream_ids at once, we can add a function that calls `load_data` with each stream_id separately, but I think this is good enough for now.

Adds stream_id support

---

docs/g3tsmurf.rst
sotodlib/io/load_smurf.py

This PR does a fair bit of updates / rearranging to the data loading functions in load_smurf. The goal is to expand functionality and move toward full `sotodlib` integration without breaking any existing analysis code. 
Main updates: 
- `load_file` function that takes any SO style `.g3` file (or list of files) and returns a correctly formatted AxisManager
- `get_channel_mask` function that connects a user's request for different channels to what exists in a file or observation. When the `dets` kwarg is passed to either `load_file` or `G3tSmurf.load_data` only the requested channels will be loaded into memory. 
- `G3tSmurf.load_data` now uses `load_file` under the hood. Right now this is slightly less optimized than before, because `sotodlib.io.load.unpack_frames` doesn't have Seek …

Load .g3 file

---

docs/coords.rst
sotodlib/coords/__init__.py
sotodlib/coords/helpers.py
sotodlib/sim_hardware.py
sotodlib/vis_hardware.py
tests/test_coords.py

Resolves #157.
It was necessary to alter both the plotting code and the layout generation code.  Instead of totally rewriting all the layout code in a right-handed system, this rewrites the 'quat' field in the detector info, once everything is done.  The plotting code was fixed mostly by transposing X and Y in all matplotlib calls.  I tweaked some labeling and coordinate code along the way to address minor issues with the plotting that I noticed.
The plots produced by so_hardware_plot are unchanged, compared to before, except for small changes in the axis ranges and new wafer label sizes.  But the plots now do represent the focal plane as TOAST will use it.
To allow me to use G3 quat code I'm also putting in the "ToastishQuat" wrapper -- I had originally planned to put this into …

Coord sys revamp

---

sotodlib/io/load.py
sotodlib/io/load_smurf.py

Preliminary work to support using G3SuperTimestream (in development in so3g) in the place of G3TimestreamMap in our data files.  This should still work fine with old so3g, when processing old data.  But if so3g has G3SuperTimestream, this can extract data from files where G3SuperTimestream has been subbed in.
This has only been tested on "load_smurf" compatible data files... the pipe-s0001 or similar format has additional complexity such that we should probably just write a new schema and extractor for it when we go to G3SuperTimestream.

G3SuperTimestream support

---

pipelines/update_g3tsmurf_database.py
sotodlib/flags.py
sotodlib/io/load_smurf.py

This PR fixes a laundry list of issues:  #170 , #160, #137 , #173, #138, #135
Nothing should be breaking existing code. 
highlights:
1. Adds tag tracking to observations, automatically applying tags set at the time of taking the data
2. Adds some new generators that makes it easier to search through the SMuRF folder for things
3. Adds an "official" database update script into pipelines so we can standardize how that's called
4. Many bug fixes.

G3tsmurf Misc updates

---

sotodlib/core/context.py

@mhasself  I'm not sure if this is how you'd like to fix it. But I found an edge case in context where if there's only one listed metadata entry to loaders fail. `SuperLoader.load( spec_list, request)` expects as list for `spec_list` and with one metadata entry it's just getting that single dictionary.

single metadata edge case

---

sotodlib/io/load_smurf.py

While trying to track down an error we were seeing I realized that the way I was building the frames table was subtly wrong. I was marking every Status frame as a dump frame instead of only when `frame['dump'] == 1`. This branch fixes that and an indexing error. 
Also edited the `add_file` function so we could use it to fix entries we found to be wrong. 
Lastly, I fixed the actual error we were encountering, where the queries were not returning the correct status objects. This was happening because we were mixing `Frames.Start` for Scan frames and `Frames.Time` for Observation frames and these are not guaranteed to be in order.

G3tSmurf: Fix Frame making and querying

---

sotodlib/io/load_smurf.py

Adds functionality in load_file so if a user tries to load a g3 file from the middle of an observation, it loads the full status information from the g3 file at the start of the observation. If this fails because of reasons (most likely it tries to load a file that doesn't exist), provides an error message and raises an exception. Closes https://github.com/simonsobs/sotodlib/issues/182, but does not address obsfiledb things yet, but can easily add this (just wasn't sure what was necessary right now). Tested this on a variety of observations and it had no problems, but happy to add more if necessary.

Adding fix to load_file to load status from start of an observation

---

sotodlib/io/load_smurf.py

without the condition check, load_file will fail with an error in accessing the primary field, when the field doesn't exist.

add missing condition check

---

sotodlib/toast/sim_hwpss.py

This bug effectively made the HWPSS signal time-dependent. Many thanks to @Helbouha for reporting it!

Use static polarization weights, not celestial weights

---

docs/context.rst
sotodlib/core/__init__.py
sotodlib/core/axisman.py
sotodlib/core/context.py
sotodlib/core/metadata/loader.py
sotodlib/core/metadata/obsfiledb.py
sotodlib/g3_condition.py
sotodlib/io/load.py
sotodlib/io/load_smurf.py
tests/test_obsfiledb.py

New features:
* samples argument to Context.get_obs
* better chance that get_obs can work in absence of a DetDb
* ObsFileDb.lookup_file enables Context.get_obs(filename=...)
Bug fix / reorganization:
* metadata is looked up relative to the metadata index (the database file)
* obsloader registry lives in context.py

Context tuneup

---

sotodlib/io/load.py
sotodlib/io/load_smurf.py

This implements the new Context loading over a sample range for the G3tSmurf loaders. I went ahead and implemented things so that a sample range could be passed to `load_file` with both database backends or with no connection to a database. (The "no database" version is pretty inefficient but I decided I wasn't going to be too worried about that case.)
Doing this I realized I'd messed up the sample counting in a previous update so I've fixed that here. And since that requires fixing already existing databases I went ahead and also added the first half of the "end of observation" fixing discussed in this issue: https://github.com/simonsobs/sotodlib/issues/224 
I believe this should close #193, and #178
```
from sotodlib.io.load_smurf import G3tSmurf, Observations
from tqdm import tqdm …
```

G3t Smurf Add Sample Counting

---

docs/intro.rst
setup.py

This PR adds the required packages (that I know of anyway) to the `install_requires` option within `setup.py`. I also updated the intro docs page for installation. 
The thing this doesn't really solve (and I'm not sure it should) is providing any description of installing spt3g/so3g within conda. If a new sotodlib user chooses to use conda, then they might run into difficulty there.
This was motivated by a user installing sotodlib, but finding so3g and PyYAML to be missing. They pointed out that the docs didn't list so3g as a requirement.
I took the approach of adding to setup.py since it should reduce the need for the user to manually install packages, as the dependencies will be checked and installed when running `pip install .` to install sotodlib.
For conda users, I believe they …

Update installation dependencies and add requirements to setup.py

---

sotodlib/core/metadata/manifest.py
tests/test_metadata.py

Addresses #231 .
Note it can't protect you from other kinds of invalid data, such as overlapping ranges.

metadata: ManifestDb throws or replaces duplicate index entries

---

sotodlib/io/load_smurf.py

Because the branch was far enough behind, and the source file was edited (mostly for pep8 compliance) the rebasing was causing difficulty and making the commit history very dirty. The discussion about this PR can be seen here https://github.com/simonsobs/sotodlib/pull/228, but otherwise this is ready to be merged.

Adding functions to generate a detdb from an obs_id and load via context

---

sotodlib/core/axisman_io.py
sotodlib/flags.py
tests/test_core.py

This is part of a larger project I'm working on for creating descriptive caldbs off of observations but I'm breaking this out for easier review. Sparse arrays look like they're going to be super useful for saving the values behind calculated flags without need to create ndets x nsamps boolean masks. They go directly into AxisManagers and expanding the IO for saving them is straightforward. 
I'm not very excited about the try-catch import statement I've put in everywhere, but the scipy docs say they're actively moving away from the old matrix versions of the sparse arrays. All the functionalities I've been using are interchangeable between the two versions so I figured I'd make it so later down the line we can just change the import statement.

Add IO interfaces for sparse arrays

---

sotodlib/io/load_smurf.py
sotodlib/tod_ops/filters.py
tests/test_tod_ops.py

I would like to revisit the interface for iir_params -- see amendments in this PR.
The good news is that the options and logic are greatly simplified.  The bad news is that this doesn't defualt to looking in "status" anymore.
@skhrg @kmharrington  This will break the integration with 'status' in g3tsmurf.  Can you have the g3tsmurf loader instead populate "iir_params" directly?  I think that's more general.  Also you will need to compute the original sampling frequency and use that to set fscale (it is not simply the decimation factor, it turns out).  Feel free to add that to this PR if convenient.
In the proposed system here, parameters "a", "b", and "fscale" are loaded from an AxisManager called "iir_params".  I am open to other names for these things (especially "iir" and "fscale"), …

tod_ops: cleanup iir_filter

---

docs/context.rst
setup.py
sotodlib/core/metadata/manifest.py

ManifestDb problems can be difficult to debug ... this command line tool helps with that, a little, by presenting the DB structure and content summary in human readable form.
Also you can re-write filenames, by prefix, which is useful for moving things between systems (as I am about to do...).

so-metadata script

---

sotodlib/core/metadata/loader.py
sotodlib/io/metadata.py

This PR adds 2 new metadata loaders, one that loads `AxisManagers` and another that determines the type of data being loaded. 
`DefaultHdfLoader` assumes the file is an hdf5 file and will look for the `_axisman` attribute in the dataset, if it's there it will load through the new `AxisManagerHdfLoader` and if it is not it will assume it is a `ResultSet`. I've also updated the default loader to be this new one.

Expand H5 Default Loading for CalDbs

---

sotodlib/core/context.py
sotodlib/core/metadata/loader.py
sotodlib/io/load_smurf.py

This PR adds functionality to Context to build the obs_detdb, a DetDb-like object that is constructed upon calling either get_obs or get_meta (or check_meta) after providing a specific obs_id. It populates the attribute `ctx.obs_detdb` and leaves `ctx.detdb` alone to make clear that the object is not the same as a traditional DetDb, though it does still belong to that class. 
Adds a hook, living in the load_smurf module, that is called with key `before-load-obs` after the obs_id is initialized. Here is an example Context file:
```
tags:
g3tsmurf_dir: '/mnt/so1/users/kmharrin/smurf_context'
obsfiledb: '{g3tsmurf_dir}/latrt_db_v4.db'
obsdb: '{g3tsmurf_dir}/latrt_db_v4.db'
imports:
- sotodlib.io.load_smurf
obs_loader_type: 'g3tsmurf'
context_hooks: obs_detdb_load
```
Notice that the detdb …

Context changes to support on-the-fly detdb

---

sotodlib/tod_ops/jumps.py

Dumb typo that got through on my last PR that I caught when working on jumpfixing stuff. It's something that is a simple enough fix but causes annoying enough problems that I would rather merge it now that wait for a bigger jump related PR.

Return jump sizes as float not int

---

docs/context.rst
sotodlib/core/__init__.py
sotodlib/core/axisman.py
sotodlib/core/context.py
sotodlib/core/metadata/__init__.py
sotodlib/core/metadata/loader.py
sotodlib/core/metadata/manifest.py
sotodlib/core/metadata/obsfiledb.py
sotodlib/core/metadata/resultset.py
sotodlib/core/util.py
tests/test_context.py
tests/test_core.py
tests/test_metadata.py

Addresses everything listed in #261 .  (Supersedes #264 as the comments below reflect major interface changes.)
I am still interested in feedback on the context.get_obs/get_meta interface, but I think it's much better now.  You can do any of the following for get_obs:
```
ctx.get_obs(obs_id)
ctx.get_obs(obs_id, dets=['det_01', 'det_02'])
ctx.get_obs(obs_id, detsets=['w29'])
ctx.get_obs(obs_id, dets={'readout_id': ['det_01', 'det_02']})
ctx.get_obs(obs_id, dets={'detset': ['w29']})
ctx.get_obs(obs_id, dets={'band': 'f090'})
```
Also, filename= still works. And you can throw in samples=(start, stop). And you can still use "obs_colon_tags" (internal nomenclature is now "free tags"). Another example, with 'band' as a free tag:
```
ctx.get_obs(obs_id+':f090', samples=(0, 1000))
```
For …

Detdb transformation

---

.gitignore
sotodlib/site_pipeline/make_det_info_wafer.py
sotodlib/site_pipeline/make_read_det_match.py

Streamlined the usage of DetMap functions in sotodlib.
What sodetlib was doing with DetMap was something that was valuable to all DetMap users. The processes that were in sodetlib have been folded into DetMap so that they are tested and maintained for all users of DetMap.
Specifically, for sotodlib these upgrades added methods for iteration of over the metadata for an array, as well as the iteration over mapped data. This pull request corresponds to upgrades in DetMap that are now available on the main branch. The new iteration and data access is best shown in the demonstration notebook [detmap/example/demo_iter.ipynb](https://github.com/simonsobs/DetMap/blob/main/detmap/example/demo_iter.ipynb).
The old version of the sotodlib branch `get-det-db` will still work with the with the …

Gen det db detmap

---

sotodlib/io/load_smurf.py

If files have no scan frames their starts and stops do not get set.

catch another file edge case

---

sotodlib/io/load_smurf.py

Recently we realized that the indexing of how to build a channel mask was pretty not-useful if you just wanted to blindly load sections of channels. This updates `load_file` and `get_channel_mask` to just accept `channels= range(x,y)` and return the resonator channels at those indexes. Will be useful for batching and just limiting detector loads in general.
Solves this issue: https://github.com/simonsobs/sotodlib/issues/278

Change how channel indexing works on load.

---

site-scripts/update_g3tsmurf_database.py
sotodlib/io/load_smurf.py

A couple bug fixes found in LATR testing. Add stream-id to file queries and extend the buffering time in the updates because there are large delays between when frames are being made.

Multi-slot Bugfix

---

site-scripts/update_g3tsmurf_database.py
sotodlib/io/g3tsmurf_db.py
sotodlib/io/load_smurf.py

Many changes related to databasing based on errors found with LATR testing
* `Observations.start` is now the time of the first data point in a file instead of the time the Observation frame is created
* Automatically order `Observation.files` by start time (new thing I didn't sqlalchemy could do, makes those lists much nicer)
* Use `Observations.session_id` to know what files should be part of an observation. No more fuzzy logic there.
* Close #241 
* Close #206  (still could be nicer but I'm seeing this as a massive improvement for little work)
* More filtering by `stream_id`

G3tSmurf Database Updates

---

sotodlib/io/g3tsmurf_db.py
sotodlib/io/load_smurf.py

This PR adds calibration observations to the G3tSmurf observations table. In particular, it adds `take_iv`, `take_bias_steps`, `take_bgmap`, and `take_noise`, gives any observations an obs_id that looks something like `cal_<stream_id>_<session_id>`. It also adds a `calibration` column to the Observations table, which will require a database update script before we can merge this into master, which @kmharrington said she would help provide at least an outline for.

Adding calibration observations to the G3tSmurf Observations table

---

docs/g3tsmurf.rst
docs/site_pipeline.rst
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/update_g3tsmurf_database.py

Several things I've been meaning to do for awhile for the database update script that's part of the first light pipeline. Moved to the correct place, print statements are now entirely replaced with logger, control over logging level in the script, and some documentation updates.

Clean Up for the g3tsmurf update script

---

docs/site_pipeline.rst
sotodlib/coords/__init__.py
sotodlib/coords/planets.py
sotodlib/coords/plotting.py
sotodlib/coords/pmat.py
sotodlib/core/metadata/loader.py
sotodlib/io/load.py
sotodlib/site_pipeline/make_source_flags.py
sotodlib/site_pipeline/make_uncal_beam_map.py
sotodlib/site_pipeline/util.py
sotodlib/tod_ops/__init__.py
sotodlib/tod_ops/detrend.py
sotodlib/tod_ops/filters.py
tests/test_metadata.py
tests/test_tod_ops.py

site_pipeline.make_uncal_beam_map
This runs successfully on ACT data and SAT sims.  There are a couple key features missing (demod + downsampling), but this is still useful.  Here's the plot it made for an ACT TOD:
Some other fixes / changes / supports made along the way:
- `coords.planets` has ways to auto-populate detector splits, and map them simultaneously.
- `coords.BeamMapAxes` provides a matplotlib "projection" that is good for beam maps.  Axes for enmaps get auto-labeled with xi and eta and will auto-rescale to deg/arcmin/arcsec depending on the viewport.
- minor/rare bugs fixed in `coords.P` (when threading not in use), `metadata.loader` (when applying a result to only a subset of the detectors that it has data for)
- `make_source_flags` is updated for new metadata practices.
- …

make-uncal-beam-map

---

sotodlib/io/load_smurf.py

Various things we needed to update just in general or for end-to-end tests.
* use observation frames to determine if an observation. Technically completely closes #224 even though I apparently decided to close the issue before doing this. 
* add stream_id to the SmurfStatus object because we need a way to pass that around and that makes the most sense
* Add the `no_signal=True/False` option to the g3tsmurf loader. closes #269  even though it's not actually needed for this I just felt like finally doing that.

Updates to get things working for End-to-end Testing

---

docs/g3tsmurf.rst
sotodlib/__init__.py
sotodlib/io/g3tsmurf_utils.py
sotodlib/io/load_smurf.py

The main additional function here came from discussions at the face-to-face where we wanted to make easier ways to get sections of observations instead of just loading complete observations. `get_batch` is a generator that will yield AxisManagers that are subsets of complete observations. 
@mhasself @jlashner @jseibert575  Interested in what you all think of this?

Batched Loading of level 2 AxisManagers

---

pipelines/toast_so_sim.py
sotodlib/toast/sim_hwpss.py

This is a fix to a bug in the HWPSS simulation which was causing spurious peaks to appear in the Fourrier spectrum. This implementation avoids this by first interpolating the HWPSS template to fast sampled HWP angles, and then downsampling to the original sample rate using [`scipy.signal.decimate`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.decimate.html#scipy.signal.decimate)

HWPSS simulation fix

---

docs/context.rst
sotodlib/core/metadata/manifest.py
tests/test_metadata.py

New functions in ManifestDb to help with cases where one needs to inspect existing db before trying to modify it:
- .inspect() -- load records, matching only fields provided (which can be Index or Endpoint)
- .update_entry() -- starting from records returned by .inspect(), change the data.
- .remove_entry() -- based on records returned by .inspect(), delete entries.
@jseibert575 and @kmharrington please let me know what else might be helpful.
(In looking at this (first time in a while) I am seeing that having a separate table for files was probably not a good idea.  There's an advantage to having a special *type* for endpoint data that contains filenames (because you can perform path resolution), but it would be much easier to treat it like other endpoint data.  I think we should change …

metadata.ManifestDb: add inspection and modification API

---

sotodlib/io/load_smurf.py

Added in functionality to process the high quality timing words from the Smurf timing system. I tested this on some data we took on when we were testing the timing system at 4kHz as below:
```
aman = load_smurf.load_file('/mnt/so1/data/ucsd-sat1/timestreams/16505/crate1slot3/1650583410_000.g3')
plt.plot(aman.timestamps, aman.primary['UnixTime'])
plt.xlabel('SMuRF EPICS Timestamps', fontsize = 16)
plt.ylabel('UNIX Timestamps', fontsize = 16)
```
This data had the PPS level triggered not edge triggered (clearly visible in the plot) and the data wasn't downsampled so this should be tested on the data from SAT1 where these two issues are fixed

Add smurf timestamps

---

docs/hwp.rst
sotodlib/site_pipeline/update_hwp_angle.py

I've changed around the update hwp angle script to make it find it's own files instead of just running on a single file. The script looks through the `data_dir` and compares the file names to the `output_dir`. All existing files except the last one are assumed to have been complete and ignored. 
I tested this as data was actively coming in for P10r1, so I think this is a stable enough solution for now. 
I have a new config file shared at `/mnt/so1/shared/site-pipeline/data_pkg/p10r1/update_hwp_angle.yaml` and updated in the docs. This might break some of the usages in `G3tHWP` but I don't _think_ it will break how people have been interactively using it. 
@yukisakurai  could you please make sure I didn't do anything stupid? Will this still work for you?
@guanyilun  I think this is good …

Have update_hwp_angle find it's own files.

---

sotodlib/io/g3tsmurf_utils.py
sotodlib/io/load_smurf.py

Expand the g3tsmurf loading from configs a bit and add a utility function for loading up HWP angles. This assumes the HWP angles are saved in the format generated by the `update-hwp-angles` site pipeline script. 
The loading for the HWP data is _slow_. We're going to have to fix that soon-ish. But this does work and does get the HWP angles loading into the AxisManager. We can upgrade this function when we get faster methods.

Add v0 of HWP angle loading

---

docs/axisman.rst
docs/hwp.rst
sotodlib/hwp/g3thwp.py

There is a hardware issue that makes frequently flipping quad value (rotation direction) in P10R1. This PR adds an option to enable quad or not in config file. This option should be basically on if hwp readout is working correctly, but it is useful for lab. testing and debug.
You need to include `enable_quad: False` to config yaml file if you want to turn off it.
Also I modified reference slit finding module to fix hwp_rate and updated docs.  
(This PR has been overwritten from RP#315.)
**Angle solution**
**hwp_rate**

HWP angle calculator with quad enable option

---

sotodlib/core/axisman.py
tests/test_core.py

I would really like to change the default behavior of AxisManager concatenation because the current behavior is causing issues for what I'd like to save in my todo pre-processing scripts. Effectively I have a script that saves an AxisManager with `dets` and `dets,samps` fields along with an additional field aligned just along `samps` that I'd like to have available later through the metadata loading. 
When I try and load these the [loader is calling concatenate](https://github.com/simonsobs/sotodlib/blob/master/sotodlib/core/metadata/loader.py#L285) on them and the presence of the `samps` only field is causing an error. I don't think we can change the default behavior of the loader because it's able to call concatenate on AxisManagers, ResultSets, and numpy arrays. So instead I'd like to …

Change default concatenation behavior for AxisManagers

---

sotodlib/site_pipeline/util.py

Is there any reason we don't want the log stream to go to stdout by default? Going to stdout allows prefect to pick it up.

site_pipeline.util: redirect StreamHandler to stdout

---

docs/toast.rst
setup.py
sotodlib/core/hardware.py
sotodlib/scripts/hardware_plot.py
sotodlib/scripts/hardware_sim.py
sotodlib/sim_hardware.py
sotodlib/toast/focalplane.py
sotodlib/toast/ops/corotator.py
sotodlib/toast/ops/h_n.py
sotodlib/toast/ops/sim_hwpss.py
sotodlib/toast/ops/sim_source.py
sotodlib/toast/ops/sim_sso.py
sotodlib/toast/ops/sim_stimulator.py
sotodlib/toast/ops/sim_wiregrid.py
sotodlib/toast/sim_focalplane.py
sotodlib/vis_hardware.py
tests/test_hardware.py
workflows/get_wafer_offset.py
workflows/make_hardware_maps.py
workflows/mapmaker_test.py
workflows/toast_so_map.py
workflows/toast_so_sim.py

* Use new xi/eta/gamma support in toast when simulating detector layout.
* Fix projected LAT rotation on the sky, and also the tube positions.
* Add LAT co-rotation options when making focalplane plots.
* Support focalplane plots in both Xi / Eta and X / Y coordinates.
* Cache detector beams in SimSSO and SimSource, in case we have the same beam for many detectors.
* Small tweaks to get_wafer_offsets arguments
* Add a new toast workflow that just loads data and reduces it.

Update hardware sim and toast workflows.

---

tests/test_tod_ops.py

Fixes issue where jumpfinder test will randomly fail sometimes (see [slack discussion](https://simonsobs.slack.com/archives/C60J078P7/p1667416485276259) for details).
Main problem seems to be that I set the min jump size to just 2 sigma, that has been upped to 5.
The jumps themselves have also been made more extreme and the seed is set to 0 for consistency.

Jump test fix

---

.github/dependabot.yml

This configures dependabot to automatically check and update the versions of reused github actions, i.e. `actions/checkout`.
This was motivated when I recently noticed in the Actions logs a bunch of warnings related to `actions/checkout` and `actions/setup-python`, which are both out of date.
I've used dependabot on several other repos and find it really helpful, it'll automatically create a PR to update actions to the latest version when one becomes available. It can automatically request reviews from a list of users if desired as well, though I've left that off for now.

Create dependabot config for actions updates

---

.github/workflows/test.yml
tests/_helpers.py
tests/test_sim_stimulator.py
tests/test_sim_wiregrid.py

This ensures that all communicators are cleaned up at the end of each unit test.  This seems to be needed on github CI services to avoid a deadlock when running MPI-enabled tests.

When running unit tests, cleanup MPI communicators.

---

sotodlib/io/load_smurf.py

Closes https://github.com/simonsobs/sotodlib/issues/327, changing the obs_id for operations to have `oper` instead of `cal` prepended, and also prepends `obs` to the observation obs_ids.
Do we need a database update script for this?

Adds obs and oper tags to obs_ids

---

sotodlib/hwp/g3thwp.py
sotodlib/hwp/hwp.py

The demodulation code was only valid for forward rotation. That was because in the calculation of hwp speed, diff of hwp_angle was moded by 2 pi. If diff of hwp_angle is negative, that became close to 2 pi. The calculated speed is used for center frequency of bandpass filter. So that resulted in too large center frequency of bandpass filter.
I modified this by adding pi before mod and subtracting pi after mod. Besides, add bpf_center to arguments as manual input of center frequency of bandpass filter.

modified demod code to support reverse rotation

---

sotodlib/hwp/g3thwp.py

1
Fixed the default instance of `load_data` from `HAB` to None.
The instance name should be initialized by config.yaml, default values, or explicitly specified in load_data function.
Therefore the following error looks unnecessary.
> else:
>             logger.error("Can not find field instance")
>             return {}
2
Added mod2pi option to the `g3thwp.analyze`
I added this option because the monotonically increasing hwp angle is useful for evaluating hwp angle jitter.

Add mod2pi option and fix handling of encoder instance name 

---

sotodlib/hwp/g3thwp.py

I found a bug in the hwp angle calculation and fixed it.
The ecoder ref_index is shifted by 1 and this is making an angle glitch once in one hwp revolution.
Please see the following notebook for the difference after debug.
https://gist.github.com/ykyohei/54f91be27dc9bf180dc7d6d196014b5f

fix hwp ref index

---

docs/context.rst
sotodlib/core/context.py
sotodlib/core/metadata/loader.py
sotodlib/core/metadata/obsfiledb.py
sotodlib/core/util.py
tests/test_context.py

As mentioned in #346, det_info indices were enforced to be unique, which prevented broadcasting place-holder data using det_id='NOT_FOUND'.
This PR fixes that, tests it, and fixes a couple other minor things.
Check the docs for new context syntax... you want to set multi: true on the detector wafer info table, not the det_id-readout_id mapping input.

Fix det info multicast

---

sotodlib/io/bookbinder.py
sotodlib/io/imprinter.py
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/make_book.py
sotodlib/site_pipeline/update_book_plan.py
tests/test_imprinter.py

This PR includes some bugfixes and improvements to imprinter+bookbinder stack. A brief summary of the changes:
- `imprinter`: 
- minor bugfixes, add `get_books` function
- database migration to include more fields
- improve test coverage
- change configurations such that one instance watches over multiple `g3tsmurf` dbs. This also suggests that there will only be a single imprinter db for all data sources (SAT1, TSAT, etc.)
- update `update_book_plan` script to reflect imprinter change
- `load_smurf`: 
- add `db_args` option to allow more configurable db connection
- `bookbinder`: 
- fix #373
- update `make_book` script to reflect imprinter change

bookbinder update

---

sotodlib/toast/ops/sim_sso.py

This PR extends the SimSSO operator to work on sources that are larger or comparable in size to the beam map.
It explicitly adds support for Moon observations. There is presently no Lunar emission model included in the data file `data/planet_data.h5`. This may be desirable as the surface temperature of the Moon greatly depends on latitude and surface illumination. It is not obvious to me how refined we want to make the emission model.
Here is an illustration of the Moon observed at 150GHz using the `i1` optics tube:

Support for Moon observations

---

sotodlib/io/bookbinder.py
tests/test_bookbinder.py

As pointed out in #357, if the timing system isn’t on, the timestamps between wafers don't line up and the system should fall back to making individual books for each wafer. Although the Imprinter will check for a timing system from the database and instruct the Bookbinder, the Bookbinder should still double-check for the presence of timing counters.
* If the counters are missing where they are expected (i.e., the database indicates the timing system was on), an error should be thrown to be caught by Imprinter, which will rerun Bookbinder in single-wafer mode.
* If the counters are present, calculate the correct timestamps and write them into every `.times` field in the output Book. Timestamps are calculated using the logic in load_smurf.py (ver. Jan 23, 2023): …

Bookbinder: Check for timing system

---

sotodlib/io/bookbinder.py

@jlashner did some digging and found that the `ndarray.astype()` casting during data buffering is taking up ~20% of the runtime because it is rebuilding the arrays from scratch. We can remove these calls, instead initializing the arrays with the types described in [TOD format doc](https://github.com/simonsobs/tod2maps_docs) and adding assertions to ensure that subsequent input data has the right type.

Bookbinder: Optimizing array allocations

---

sotodlib/io/bookbinder.py
tests/test_bookbinder.py

@mhasself suggested that I can minimize the number of numpy array allocations by changing how the buffered data is stored. Instead of creating a new ndarray every time new data is added, we append the new data to a running list (as a new item in the list) that only gets converted into a contiguous array at the output call.
A simple test where I add a 1000-by-1000 array to the buffer 10 times show a notable speedup between the two methods.

Bookbinder: Optimize data buffer I/O

---

sotodlib/io/g3tsmurf_db.py
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/monitor.py
sotodlib/site_pipeline/update_g3tsmurf_database.py

This has been rebased off of #392  and #390  so we need to wait for these two to merge here. I would also like to wait until [this PR](https://github.com/simonsobs/smurf-streamer/pull/38) has started running at UCSD because I'd prefer to not need to repair the UCSD databases more than once (and this should technically be tested on "good" files). 
This PR adds a timing tracking column to the Files and Observation tables in G3tSmurf. It also adds our first example of the QDS monitor into the update-g3tsmurf-db script which will let us set up a grafana alter if the timing information dies at some point. 
Merging this PR will come with the need to run some table updates on the existing databases. I have scripts for these but @guanyilun  we'll need to coordinate running those scripts on the …

G3tSmurf Timing Updates

---

sotodlib/tod_ops/filters.py

@tterasaki found that the default fourier filter behavior to apply a linear detrend was screwing up some of the demodulation operations. After discussion with @kmharrington and @mhasself on slack we agreed the right solution for now is to set the default behavior to be no detrending.

Fourier filter default behavior is no detrending

---

sotodlib/io/bookbinder.py

This reverts commit 75dafd8. The Python 3.7 version of Numpy doesn’t include dtype as an option for `hstack`. Since it was only put in to satisfy my paranoia, we remove it here to ensure continued compatibility.
@jlashner can you check that this works?

Bookbinder: Backward compatibility with Python 3.7

---

sotodlib/hwp/g3thwp.py

Debugged encoder slot patter subtraction.
Previous code fails when the number of encoder slots in the range of interest is specific numbers.
Previous example of error 
on /mnt/so1/data/ucsd-sat1/hk/16750/1675094333.g3
```
line 516, in eval_angle
solved['fast_time'] = solved['fast_time'] - subtract
ValueError: operands could not be broadcast together with shapes (8296086,) (8295780,) 
```

debug hwp slot pattern subtraction

---

sotodlib/io/load.py
sotodlib/io/load_smurf.py

load_file will take copies, instead of refs, when pulling a ~small number of dets out of a frame stream.

load_smurf: reduce RAM footprint when loading a few detectors

---

sotodlib/toast/ops/sim_sso.py

Following discussion from slack, moved this over from #251 
I can add backwards compatibility with pickle files if we want. I do have a scrip for converting the old pickle files to hdf5 that I can put in pwg-scripts if needed.

Use HDF5 to store beam

---

sotodlib/io/g3tsmurf_utils.py

Allows users to include optional columns that are part of the entire detmap csv output to `add_detmap_info`
This addresses #417.

Added optional columns to add_detmap_info

---

sotodlib/io/imprinter.py

This PR adds smurf ancillary data to `oper` books. Currently this only copies files that have a `npy` suffix, which I believe captures everything we want to add, but we can easily change this if it doesn't. Files are currently copied to `book_output/smurf/<basename>`, but this can change. I was considering `book_folder/smurf/<stream_id>/<basename>`, but I don't think it matters since there will only be one stream-id per oper book.
A few other things this includes
- I added a test_mode kwarg to the `bind_book` function, since it is _really_ useful to be able to run that function to write an existing book to my local directory where I can check it. In test_mode, none of the changes to `book` will be committed, and it won't complain about the book already being bound.
- Removes the hwp …

Adds smurf data to oper books

---

sotodlib/io/imprinter.py

This makes the start/end determination more robust to instances where the last file has no scan frames, as Yilun pointed out in #420.

Fix get_start_and_end frame loop

---

sotodlib/io/bookbinder.py
sotodlib/io/imprinter.py
tests/test_bookbinder.py

This improves the Bookbinder’s missing-sample checker. Rather than only checking for gaps between input frames when inputting data, it is better to just look for missing samples in the output frame that will be written to a book. This would also catch missing samples that were in the middle of frames, instead of only between frames.
Like before, two methods to check for missing samples are provided: matching with a provided reference timestamp list or using an estimate of the sampling interval to look for gaps. The missing timestamps are filled in using the `fill_time_gaps` function written by jlashner in #405; the samples are assigned the value of FLAGGED_SAMPLE_VALUE (default: -1) and flagged in the output as before.

Bookbinder: Fill in missing samples

---

sotodlib/hwp/g3thwp.py

IRIG quality check was only working for 1Hz, so it was modified to work for irig_type=1 (10Hz).

g3thwp: fix irig_quality check for irig_type=1, 10Hz

---

sotodlib/io/bookbinder.py

If the buffer is exactly maxlength, the Bookbinder clears the buffer without advancing the frame split time and gets stuck. This fix changes the `>= maxlength` to a strict `>`. The split time written is then changed to be the first sample of the next frame, consistent with the convention for HK-determined splits.
Fixes #422

Fix 0-length buffer bug in Bookbinder

---

sotodlib/io/bookbinder.py
sotodlib/io/imprinter.py
tests/test_bookbinder.py
tests/test_imprinter.py

Fixed issues (1,3,5) with metadata found in #388.
An example M_index.yaml file from this PR:
```yaml
book_id: obs_1677794454_sat1_1111101
book_type: obs
end_time: 1677795650.3189769
n_frames: 38
n_samples: 239315
sample_ranges:
- - 0
- 239315
session_id: 1677794454
start_time: 1677794453.7489772
stream_ids:
- ufm_mv14
- ufm_mv18
- ufm_mv19
- ufm_mv22
- ufm_mv6
- ufm_mv9
telescope: sat1
```
An example M_book.yaml from this PR:
```yaml
book:
book_id: obs_1677794454_sat1_1111101
finalized_at: '2023-03-18T17:14:16.597195'
schema_version: 0
type: obs
bookbinder:
codebase: /home/yguan/software/sotodlib/sotodlib/__init__.py
context: simons1-data-pkg-dev
version: 0.4.0+1175.gf37013d.dirty
```
Also fixed an off-by-1 bug that came up during my local testing, and propagated the corresponding changes …

Book metadata improvements

---

docs/site_pipeline.rst
setup.py
sotodlib/site_pipeline/cli.py
sotodlib/site_pipeline/make_source_flags.py
sotodlib/site_pipeline/make_uncal_beam_map.py
sotodlib/site_pipeline/update_g3tsmurf_database.py
sotodlib/site_pipeline/util.py

This adds an entry point called so-site-pipeline, the purpose of which is to more easily access scripts in sotodlib.site_pipeline.
Only a couple of elements have been "registered" for now; a certain interface in the submodule is expected.
@guanyilun Since this requires formalizing entry points to site pipeline scripts, it is worth considering if it is also a good time to build in easier access from Prefect.  I forget what the exact requirements are there.

so-site-pipeline command line interface

---

sotodlib/io/hk_utils.py

Adding an extra function to `hkutils` that takes in an hkconfig file, a detconfig file, and an obs.id to output an HK axis manager that's cosampled with detector time streams.
Incorporates #404 
Things to note:
- could expand it to make it more general outside of detector timestamps but may need a bit more thinking
- assumes the start and stop times of an `obs.id` is all the start and stop time you need
- probably a better way to do this: right now, it takes in the detector timestamps and adds it as an axis to each individual HK axis manager. Likely, we want just one timestamps axis and need the HK axis manager's to have only interpolated data.
- it'll be good for me to add documentation to the readthedocs on using `hkutils`

Make HK Amans Cosampled with Detector Timestreams

---

sotodlib/toast/ops/sim_source.py
sotodlib/toast/ops/sim_sso.py
workflows/toast_so_sim.py

This PR extends the planetary emission models to include linear polarization.  The user sets the polarization fraction and angle that get applied to all planetary observations and all planets. The reference frame is set by the workflow and is currently set to be the Celestial system.

Add options to make the planets polarized

---

sotodlib/core/hardware.py
sotodlib/sim_hardware.py
sotodlib/site_pipeline/make_det_info_wafer.py
sotodlib/toast/sim_focalplane.py
sotodlib/vis_hardware.py

Adding the ability to use actual UFM hardware information for the readout sims. The UFM rotations relative to each other look correct. Note: this DOES NOT work for LF detectors yet, the mappings between MF and UHF are similar enough that I can use existing MF mappings to spoof the UHF. The LF detector positions and setup will be totally different. There will be straightforward ways to build off this when we know which UFMs are installed in which wafer slots.
Example use for creating a hardware setup: 
```
lat_hw = sim_nominal()
core.hardware.sim_wafer_names(lat_hw)
sim_telescope_detectors(
lat_hw, 
"LAT", 
tube_slots=["i1"],
det_info=("/home/kmharrin/scratch/20230216_toast_scratch/det_info.h5","Cv4"),
)
```

Add UFM mapping

---

docs/context.rst
setup.py
sotodlib/core/metadata/__init__.py
sotodlib/core/metadata/cli.py
sotodlib/core/metadata/manifest.py
sotodlib/core/metadata/obsdb.py
sotodlib/core/metadata/obsfiledb.py
tests/test_context.py
tests/test_obsdb.py
tests/test_obsfiledb.py

Enhancements to the `so-metadata` command line interface.
It is now possible to inspect Context yaml files, and ObsDb and ObsFileDb, in addition to ManifestDb.
This should make it easier to debug context / metadata configuration issues.

Improve so-metadata cli

---

sotodlib/flags.py
sotodlib/site_pipeline/preprocess_tod.py
sotodlib/tod_ops/__init__.py
sotodlib/tod_ops/detrend.py
sotodlib/tod_ops/fft_ops.py
sotodlib/tod_ops/filters.py
tests/test_tod_ops.py

The hour+ SAT books are giving us a good opportunity to profile the `tod_ops` code. There are several we'll need to work on but this is the start. 
Detrend on 1 UFM x 1.2 hours of data was taking ~110 seconds on simons1. The longest parts were subtracting the slopes and recasting at then end (in case data types had changed). Moving to the `-=`, using the `for` loop if possible, and only recasting if the data type had changed got it down to ~6 seconds. Added some comments so we hopefully remember why it's done this way.
Also add another argument to `get_glitch_flags` which lets us speed that up a little bit but that one will take some more careful work to speed up in the future (it's currently at ~240 seconds). 
Edit: Added some quick changes to `calc_psd` to let us just reduce the samples …

Detrend Speedup

---

docs/g3tsmurf.rst
sotodlib/io/g3tsmurf_db.py
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/update_g3tsmurf_database.py

Going through a bunch of g3tsmurf updates at once. Now ready for review!
Biggest part of this PR is re-ordering the database updating and reworking some of the logic based on existing issues. To test this I made a databases covering all of SAT1's P10R2 cooldown using both the current master branch and this branch. All the differences between the two databases are because of fixing existing issues. Making note of what I checked here because this really should go into a test structure somehow:
- Size Old: 126Mb, New: 112Mb
- Channels: Old: 42572. New: 42288.
- Channel Assignments: Old: 198, New: 198
- Tunes: Old: 197, New: 197
- TuneSets: Old: 197. New: 25 ( Expected because of #259 )
- Observations: Old 2010. New 2222 ( Expected, with caveats because of #304 )
- Tags: Old 2006. New. 6728 …

G3tsmurf Updates 2023-04

---

sotodlib/io/load_smurf.py

when tunes.name naming convention is changed, this is one compatibility change that's missed in previous PR.

fix tunes name parsing

---

sotodlib/flags.py

This is a simple 1-line change I found when reviewing how our glitch detection works for my thesis. In `flags.get_glitch_flags`, the `t_glitch` argument wasn't used, and 0.002 was hardcoded into the gaussian filter.

t_glitch argument wasn't used

---

sotodlib/io/check_book.py
sotodlib/site_pipeline/check_book.py

For oper books, especially, there will be ancillary files and sometimes analysis output that needs to be accepted.  You can still explicitly ban files that match some pattern, such as frame_splits.txt...

check-book: settings to tolerate arbitrary extra files in book

---

sotodlib/core/axisman.py

This was causing tests to fail on py39 and py310, I guess because scipy on the CI systems just ticked up into version 1.11.

Fix use of csr_matrix.hstack.vstack

---

sotodlib/toast/sim_focalplane.py

This fixes an immediate bug in SOFocalplane.  However, the unit test for this is pending as part of #505.
Closes #508.

Fix logic when parsing det_info tuple.

---

sotodlib/site_pipeline/update_g3tsmurf_db.py

`update_g3tsmurf_db` needs an argument reordering. I found this fixed the bug in prefect auto-deployment but I still need to understand why. It may have to do with how I modify function signature by hand. Before I figure out the reason, we should make sure that `logger` is always the last argument in each site-pipeline module script.

g3tsmurf indexing deployment bugfix

---

sotodlib/io/g3thk_utils.py
sotodlib/io/load_smurf.py

Found synchronization issue while setting things up at the site. This adds some search buffer while looking for pysmurf monitor control information.

Allow some buffer in update time checking

---

sotodlib/scripts/hardware_plot.py
sotodlib/sim_hardware.py
sotodlib/toast/instrument.py
sotodlib/toast/sim_focalplane.py
sotodlib/vis_hardware.py
tests/test_hardware.py

This PR is the matching one for the [upstream PR in toast](https://github.com/hpc4cmb/toast/pull/674).  This ensures that focalplane layout widths are always given in terms of pixel centers rather than field of view.

Simulated focalplane spacing

---

sotodlib/coords/demod.py

The make_map function is missing a center_on=None parameter in the inputs. If center_on is not defined it fails at some point.

fix bug in make_map function in coords/demod.py

---

sotodlib/io/load.py
sotodlib/io/load_book.py
sotodlib/io/load_smurf.py

Book -> AxisManager loader module is substantially rewritten.
Now:
- `load_book_file()` can be used to load any .g3 file from an obs/oper book, without obsfiledb support.  In fact you can load (and concatenate) multiple files from any single detset.  The output is basically identical to what you'd get loading them through obsfiledb/Context.  This addresses #514 .
- The Book "ancil" data (i.e. position encoders) are loaded into the AxisManager.  In the present design, they are all simply copied into a sub-axisman called "ancil".  They are also copied, and scaled, into a sub-axisman called "boresight".  As the data are processed I am imagining that "ancil" will remain untouched but "boresight" might be updated (or recomputed) based on a pointing model. 
- Wiring frames are parsed, using …

Changes to book loader

---

sotodlib/io/imprinter.py
sotodlib/site_pipeline/make_book.py

This update, matched with [site-pipeline-config changes here](https://github.com/simonsobs/site-pipeline-configs/pull/9) make the HK bookbinding separate from the detector book binding. This is necessary for the LAT data, which has the HK and detector data going to separate places and for the site hk data, which has no detectors. I've tested this on some of the site level 2 data and looks like it all works.

Split HK sources from Detector data sources

---

sotodlib/toast/ops/sim_source.py

Looks like this was just a typo where `h5py` was used instead of `h5py.File`.

Fix bug introduced in #415

---

sotodlib/io/bookbinder.py
sotodlib/io/imprinter.py
sotodlib/io/imprinter_utils.py
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/make_book.py
sotodlib/site_pipeline/monitor.py
sotodlib/site_pipeline/update_book_plan.py
sotodlib/site_pipeline/update_g3tsmurf_db.py

A bunch of changes to deal with some hanging issues with stray / smurf books. Biggest issue was that smurf and stray books needed to be made per daq node and, given the structure of imprinter, it was much easier to just add the requirement that we have one imprinter instance / database per daq node (that's how things are set up at the site but pieces of the code were more flexible than that).  
* Closes the two linked issues. 
* prevents stray books from being made if there are books throwing errors that we might want in stray books later. 
* adds a `WONT_BIND` status option that we can set by hand. If books have that status than their .g3 files will get added into the stray books
* stream ids that aren't part of the telescope tubes go into stray books
* add some utility functions that we …

Site updates to data packaging

---

sotodlib/io/imprinter.py
sotodlib/io/imprinter_utils.py
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/update_book_plan.py
sotodlib/site_pipeline/update_librarian.py

* The librarian upload should definitely be throwing errors when if fails instead of just passing
* I realized the timecode finalization should be based on servers instead of on stream_ids because that's actually how the files are made. This is also now possible based on the "one per daq-node" setup that is now enforced with imprinter
* Added a function that will now tell us why the timecode books aren't being made.

Site Updates for Data Packaging

---

sotodlib/coords/helpers.py

I've tried to make changes to `get_wcs_kernel` as pointed out in [issue 525.](https://github.com/simonsobs/sotodlib/issues/525)  I'm not sure this is what was envisioned, but I've tested it on an various projections and resolutions and it yields expected results. The function will throw an error in cases where the beam is too large, or doesn't come from a pre-approved set of sizes. 
If this is acceptable, I can propagate the change into `get_footprint`, which is the only function that I can find that will need to be changed.

Change get_wcs_kernel to be more stringent

---

sotodlib/coords/helpers.py

As mentioned in #554 , I've updated the check to be even at a degree level, and check this quantitatively, rather than by parsing a string.
`if abs(div) > 1e-8:` will only let projections with real remainders through, and won't catch any that might be a result of float point inaccuracy. 
I've tested this with inputs in arcsecs, arcmins and degrees. Let me know if I've missed something.

Wcs resolutions

---

sotodlib/flags.py

Based on the discussions in issue #536, I have put in a catch to supply a decimation factor for the Fourier filtered signal if there are over 50,000 samples in the AxisManager. The decimated array will now be around 20,000 samples, which will speed up the `stats.iqr` step.

Faster glitch flagging

---

sotodlib/site_pipeline/preprocess_tod.py

When the `sotodlib.site_pipeline.preprocess_tod` method `_build_pipe_from_configs` is called and the config dictionary includes a process name which doesn't have a corresponding class defined in `sotodlib.preprocess.processes` a log warning should be raised but currently that logging is not imported properly so that log statement breaks the code. I now added that import and tested that it works.

Add logger import.

---

sotodlib/io/g3thk_db.py

improve performance of hk agent loading by eager loading all children fields.

use joinedload instead of lazyload to speed up db queries in hk

---

sotodlib/coords/planets.py

To visualize when boresight hits the planet, I want a function to get the trajectory of planet.

Add function to derive the az el of planets

---

sotodlib/coords/pmat.py
sotodlib/mapmaking.py

This pull request adds support for bilinear mapmaking to sotodlib. This functionality depends on the bilinear branch of so3g, but I've added some temporary scaffoling in this pull request to still make standard nearest neighbor mapmaking work while using the old version of so3g. This scaffolding is quite ugly, so I suggest we remove it as soon as possible. The scaffolding involves working around the shape of the threads/rangs/ivals (I wish this thing had a more consistent name in the code!) object having 4D in new so3g and 3D in the old one; as well as the Projectionist accepting a new interpol argument in the new version but not in the old version.

Bilinear mapmaking support

---

sotodlib/io/bookbinder.py

Many books are failing with this error: 
```
2023-10-16 19:09:08,420: Preprocessing smurf obsid oper_ufm_mv19_1697142674 (INFO)
2023-10-16 19:09:08,467: Preprocessing HK Data (INFO)
File "/so/home/jlashner/work/book_debugging/main.py", line 15, in <module>
b.bind()
File "/so/home/jlashner/repos/sotodlib/sotodlib/io/bookbinder.py", line 778, in bind
self.preprocess()
File "/so/home/jlashner/repos/sotodlib/sotodlib/io/bookbinder.py", line 634, in preprocess
frame_splits = find_frame_splits(self.ancil)
File "/so/home/jlashner/repos/sotodlib/sotodlib/io/bookbinder.py", line 1089, in find_frame_splits
return block.times[idxs]
IndexError: arrays used as indices must be of integer (or boolean) type
```
After looking into it I found that these lines are …

Fixes float idxs for scan crossings

---

sotodlib/io/bookbinder.py
sotodlib/io/check_book.py
sotodlib/io/imprinter.py
sotodlib/site_pipeline/update_obsdb.py

This PR adds a few things 
* fixes the miss-ordering between `stream_ids` and `detsets`. which were causing the creation of a lot of weird and wrong detsets.
* adds an option in check book to ignore the requirement of this ordering being the same
* adds an option in check book to remove fixed tones from detector lists
* adds options to just skip adding failed books to an obsfiledb / obsdb. 
Using all of these, I have now obsfiledb and obsdb making running on the site uploaded books.

ObsDb error handling for site books

---

sotodlib/toast/ops/sim_catalog.py

Ok, perhaps this time I haven't slaughtered a branch. 
`get_beam_map` would crash because it was incorrectly reading in h5 files. `observe_catalog` crashed due to unit errors. Both of these issues have been fixed here.

Fixes to units and syntax in sim_catalog

---

sotodlib/toast/ops/sim_source.py

In `_get_source_position` there is bug when `scan_type=fixed`, since `az_start` and `el_start` are left undefined.

Fixing a bug that did not allow to run with scan_type=fixed

---

sotodlib/site_pipeline/update_smurf_caldbs.py

Long awaited first set of smurf related caldbs. I'm also starting this script with the assumption that I'll get expanded later. 
Right now this copies over all the interesting stream_id, wafer/tube-slot info, and channel tuning info and sets things up for it to load the metadata as desired. 
Test it out for yourself at: `'/so/scratch/kmharrin/202310_smurf_detsets/context.yaml'`

SMuRF detset info

---

sotodlib/io/bookbinder.py

This PR changes the bookbinder such that if data has Low-precision (software) timestamps, it will linearize it using the frame-counter.
This fixes issues that we're having binding LAT data, which is running without a timing system, which breaks the bookbinder, since it detects and tries to fill gaps where there are none.
This has been tested on `obs_1698478281_lati6_100`, which is currently failing.

Linearize times in bookbinder if Low Precision

---

sotodlib/io/bookbinder.py
sotodlib/site_pipeline/update_obsdb.py

Also removed a (now) unnecessary fork in how `update_obs` is called.

update-obsdb: sanitize tags list (no empty strings)

---

sotodlib/core/metadata/cli.py
sotodlib/core/metadata/loader.py
sotodlib/core/metadata/obsfiledb.py

Major thing here is a change to obsfiledb to loosen the requirement on detector names.  Previously a detector name could belong to only one detset ... but now it can belong to more than one.  (Within a single _observation_, such overlapping detsets must not be used!)
An existing obsfiledb can be upgraded to the new format, like this:
```
so-metadata obsfiledb  /path/to/obsfiledb.sqlite  fix-db --overwrite
```
Couple of other fixes:
- addreses half of #600 -- so-metadata obsdb can handle queries that use tags.
- makes context.get_obs a bit more permissive, if an observation is not registered in obsdb yet.  fail later!

obsfiledb fix, minor metadata improvements

---

sotodlib/toast/ops/sim_source.py

Fix warning about unit declaration; seen on python 3.10, astropy 5.3.4.
```
>>> units('deg / s / s')
WARNING: UnitsWarning: 'deg / s / s' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]
units("deg / s2")
```

Fix warning about astropy.units

---

sotodlib/io/bookbinder.py
sotodlib/io/imprinter.py
sotodlib/io/imprinter_cli.py
sotodlib/io/imprinter_utils.py

Should be solving all of #602  and #578
* Adds corotator positions into the LAT books. (doesn't solve the larger "why is the bookbinder hardcoding those fields?" question but good enough for now). 
* Adds ability for imprinter to deal with an empty wafer slot in an optics tube
* Accepts more info from the imprinter configuration file and adds the wafer slot info into the `M_index.yaml` file. I've left this backward compatible since this is probably be a slow roll-out on the site config pieces.
All of these have been tested on site data. Example new index file: 
```
az_speed_mean: 1.4717079588791546
az_speed_stdev: 0.16743276067991805
book_id: obs_1700036552_satp1_1111111
detsets:
- ufm_mv19_1699368806_tune
- ufm_mv18_1699303578_tune
- ufm_mv22_1699294049_tune
- ufm_mv29_1699293235_tune
- …
```

Imprinter Updates

---

docs/site_pipeline.rst
sotodlib/core/metadata/obsfiledb.py
sotodlib/io/load_book.py
sotodlib/site_pipeline/update_smurf_caldbs.py

This update adds a new function to the `update_smurf_caldbs` script that will write detector calibration info pulled from sodetlib IVs and bias steps to a Manifestdb + hdf5 archive. I have run this and tested in my home directory on a subset of the full observation list. I think it should take ~ an hour or so to run completely, so we may want to run directly as the pipeline user before adding to prefect, so we don't have a massive hour-long operation.

Add detector calibration info to update_caldb script

---

sotodlib/io/load_book.py

Resolves #628 and #618 
Bugs fixed:
- get_obs won't load anything other than the iir_params from the G3 frames; no more innocuous ERROR message
- samples=(a, b) should work, even if a!=0.

Book loader fixes

---

docs/site_pipeline.rst
sotodlib/io/so_ufm.py
sotodlib/site_pipeline/cli.py
sotodlib/site_pipeline/make_det_info_wafer.py

The code to generate `det_info.wafer` datasets is now entirely internal and parses the layout CSVs directly.  This can be run as a site-pipeline script.
The formatting of the output `wafer_info` has changed in a few ways.
- `angle` is now in degrees, not radians.
- 1-letter code fields (`pol`, `rhombus`) use 'X' to represent N/A, rather than 'None'.
- `det_x` and `det_y` renamed to `x`, `y`.
- `mux_band` is an int, not a str-that-could-be-safely-cast-to-an-int.
- new field "crossover", giving the 1-letter detector pad class, TBLR.  Open to a better name here; I don't totally know what this is I just know it could be important in the future.  Maybe "pad_type"?

make-det-wafer-info modernization

---

sotodlib/io/g3tsmurf_db.py
sotodlib/io/imprinter.py
sotodlib/io/imprinter_utils.py
sotodlib/io/load_smurf.py

The last PR fixed things so that books with `obs.timing = False` got shoved in to single wafer books. 
This PR rounds out the logic to get timing = False for the two ways we could have non-cosampled UFMs. The first, which was already implemented, is low-precision timestamps in the files. The second is when the downsample mode is set to internal. Both need to be true for UFMs to be co-sampled.
I've checked that the SATp1 files get `status.downsample_external = True` and the current LAT and SATp3 files have `status.downsample_external = False`

Downsampling mode into timing logic

---

sotodlib/preprocess/processes.py
sotodlib/tod_ops/flags.py

The version of turnaround_flags added in the sub_polyf PR only included a process operation for preprocess. This PR adds in a calc_and_save operation and updates the flags returned to be RangesMatrices size n_dets x n_samps.

Update trending_flags to work with preprocess.

---

sotodlib/toast/workflows/pointing.py
sotodlib/toast/workflows/proc_characterize.py
sotodlib/toast/workflows/proc_demodulation.py
sotodlib/toast/workflows/proc_filters.py
sotodlib/toast/workflows/proc_flagging.py
sotodlib/toast/workflows/proc_mapmaker.py
sotodlib/toast/workflows/proc_mapmaker_filterbin.py
sotodlib/toast/workflows/proc_noise_est.py
sotodlib/toast/workflows/sim_detector_readout.py

Disable all unnecessary TOAST operators by default.
Extend support for `--full_pointing` command line option.

Better toast defaults

---

sotodlib/io/bookbinder.py
sotodlib/io/imprinter_cli.py

The bookbinder currently looks at calculating framing off of azimuth position for almost 20 minutes of buffer time around different observations. And somehow today we managed to move the mount of satp3 so that the framing calculator became an infinite loop. 
This PR **does not** fix that infinite loop but does stop the current error by significantly reducing the amount of buffer time around the detector data that we use to calculate when turn-arounds / starts / stops are happening. This was a faster quick-fix that will hopefully hold until we can get a real fix around this issue. I have double checked that the framing remains identical for two SATp1 scans, (1 cmb, 1 point source) and that it fixes the issue with the satp3 book that was infinite looping.

Bookbinder only examines Azimuth positions around detector data

---

docs/context.rst
sotodlib/core/context.py
sotodlib/core/metadata/cli.py
sotodlib/core/metadata/detdb.py
sotodlib/core/metadata/loader.py
sotodlib/core/metadata/manifest.py
sotodlib/core/metadata/obsdb.py
sotodlib/core/metadata/resultset.py
tests/test_context.py

This PR brings one major functional change needed for proper functioning of the context system, and a few little bugfixes.
Major functional change is in how det_info is merged during metadata parsing with Context.  det_info now merges more like how other metadata does -- any fields are matched against fields with the same name in the existing det_info, and that is used to associate new data to each existing readout channel.  This should be backwards compatible (stuff that used to work will still work), but now lots of other stuff will work too (this is especially needed to associate stuff with det_id=NO_MATCH rows).
Other little fixes:
- CLI: `so-metadata metadata metadata.sqlite entries` -- mode to dump all rows in the table existed but didn't show up in help output.
- DetDb docs are …

Metadata fixes

---

sotodlib/io/g3thk_db.py

Using `selectinload` seems much faster than `joinedload` for querying small amount of entries out of the big database.

`selectinload` instead of `joinedload` for performance improvement.

---

sotodlib/hwp/g3thwp.py
sotodlib/io/bookbinder.py
sotodlib/io/imprinter.py
sotodlib/io/imprinter_cli.py
sotodlib/site_pipeline/make_hwp_solutions.py
sotodlib/site_pipeline/preprocess_tod.py
sotodlib/site_pipeline/update_smurf_caldbs.py

Next round of bookbinding fixes and setup for smurf calibration databases and hwp angles. Updates include:
1. Implementing a method of checking for duplicate ancillary data and removing it from bookbinding if found (and if we say it's ok to remove it). Associated updates to the imprinter cli to choose to rebind books with flags.
2. Update how we find edges in scanning to deal with slower scans and make it impossible for infinite loops to happen. I have checked this new method versus the old one on 24 hours worth of observations a from satp1 and the new frame edges were never more than 2 samples different from the old frame edges.
3. Change smurf caldb function to accept a context file per type of caldb (det-cal needs detsets but detsets can't use a context that assumes detsets already …

Bookbinding / Automation Fixes

---

docs/hwp.rst
sotodlib/hwp/g3thwp.py

I think we should have little more flexibility in the `force_quad`, because we would like to `force_quad` both forward and reverse direction depending on the observation conditions.
To have more fallibility in `force_quad`, I moved the `force_quad` from `hwp_config` to the argument of `analyze`.

g3thwp: add force_quad to the argument of analyze

---

sotodlib/site_pipeline/make_det_info_wafer.py

There are a couple other references to detmap in site-pipeline, but this is the only one referenced in the CLI.

Remove unused import that is also difficult dependency

---

sotodlib/hwp/g3thwp.py
sotodlib/io/imprinter_cli.py
sotodlib/io/imprinter_utils.py
sotodlib/site_pipeline/make_hwp_solutions.py

This fixes the logic for making and/or connecting to ManifestDbs with the HWP angles. Previously the behavior was creating a new database every time it was run. 
Also includes a fix to the Imprinter CLI to account better for an books we bind outside the docker image.

ManifestDb HWP logic fix

---

sotodlib/tod_ops/flags.py

Currently the `det_cal` based flags have the opposite logic as the rest of flags (i.e. True for good channels and False for bad). Here I swapped that to match the rest of the module (i.e. True for bad channels and False for good). I also added an `edge_guard` argument to the `get_glitch_flags` function to exclude glitches detected at the ends of the data due to ringing of the HPF.

Flag fixes

---

sotodlib/site_pipeline/update_smurf_caldbs.py

This adds a few things to the `update_smurf_caldbs` script to:
- Cache failed obsids in the update_detcal function
- Adds option to write the h5path relative to the dbpath in both detset and detcal dbs. This makes it so that we can simply copy the h5 and sqlite files to a new location and don't have to re-root.
- Adds `root_dir` param to config, so you can update that once instead of changing the path for the h5files and dbfiles separately when testing in a new directory.
- Adds `--skip-detsets` and `--skip-detcal` args for testing

Failed file cache and relative paths in smurf_caldbs

---

sotodlib/hwp/g3thwp.py
sotodlib/site_pipeline/make_hwp_solutions.py

Added a field (`hwp_err`) in HWP ManifestDb to indicate when the HWP angle is all zeros, whether it is a calculation failure or just a lack of L2 HWP data.
Motivated by this issue: #669

Include error indicator field in HWP ManifestDb

---

docs/context.rst
sotodlib/core/context.py
sotodlib/core/metadata/__init__.py
sotodlib/core/metadata/cli.py
sotodlib/core/metadata/loader.py
sotodlib/site_pipeline/preprocess_tod.py
tests/test_context.py

This updates the metadata handling system in Context to be more flexible in how missing data are treated.  This builds on the system started in #460 and the discussion there.
Main features:
- New `load_metadata` function can be used to load a result from a ManifestDb, starting from only an AxisManager and a metadata spec.
- Format of metadata entries in Context is modified (and features extended):
- new `on_missing` = `trim`, `skip`, `fail` option
- "name" is deprecated in favor of "unpack" and "label"
- You can "unpack" into multiple places
- The on_missing for an entry can be overridden when calling Context get_obs or get_meta.
Also:
- Documentation of the metadata system is reorganized a fair bit.  This could still use some work, but it's better.
- More tests of metadata loading for …

Metadata - on_missing

---

sotodlib/preprocess/__init__.py

I got a bit tripped up figuring out how to import registered processes, because you first had to import the `processes` module, then `PIPELINE` from `core` in order for it to be populated. I thought doing it this way made more sense, but let me know what you think.
Now you can `from sotodlib.preprocess import PIPELINE` to get the registered processes.

Move process registration to __init__.py in Preprocess.

---

sotodlib/mapmaking/utilities.py

This PR fixes the following error:
```python
0    0.38  3.85  4.93  8.59 Downsampling 1,1
0    0.38  3.85  4.93  8.59 Active downsampling 1
File "/scratch/gpfs/ip8725/tmp/mapmaker.py", line 286, in <module>
obs = mapmaking.downsample_obs(obs, passinfo.downsample)
File "/home/ip8725/.local/lib/python3.10/site-packages/sotodlib/mapmaking/utilities.py", line 513, in downsample_obs
res.wrap(key, downsample_cut(getattr(obs, key), down), [(0,"dets"),(1,"samps")])
File "/home/ip8725/.local/lib/python3.10/site-packages/sotodlib/core/axisman.py", line 375, in __getattr__
return self[name]
File "/home/ip8725/.local/lib/python3.10/site-packages/sotodlib/core/axisman.py", line 356, in __getitem__
raise KeyError(name)
KeyError: 'source_flags'
```

Setting `source_flags` as optional.

---

sotodlib/coords/demod.py
sotodlib/coords/pmat.py
tests/test_demod_map.py

Addresses problems in coords.demod.make_map identifed by @chervias.
I believe that what was in there before was correct only when the focal plane and celestial coordinates were well aligned; e.g. when looking due north or due south, or in source-scan coordinates.
There's a unit test now.

Fix demod mapmaking

---

sotodlib/core/axisman.py
sotodlib/core/axisman_io.py
sotodlib/hwp/g3thwp.py
tests/test_core.py

Compress h5 output of axisman.save.
I chose gzip with default compression level as default. This is lossless compression and available with every installation of HDF5.
https://docs.h5py.org/en/stable/high/dataset.html#lossless-compression-filters
I tested this compression on satp3 hwp angle files. The data size reduces by factor of ~4.
Before
-rw-r--r-- 1 site-pipeline so       138G Feb 12 20:06 hwp_angle.h5
After
total 32G
-rw-r--r-- 1 ykyohei so 608K Feb 24 15:33 hwp_angle.sqlite
-rw-r--r-- 1 ykyohei so 2.2G Feb 24 05:17 hwp_angle_1701.h5
-rw-r--r-- 1 ykyohei so 1.2G Feb 24 06:16 hwp_angle_1702.h5
-rw-r--r-- 1 ykyohei so 3.9G Feb 24 08:32 hwp_angle_1703.h5
-rw-r--r-- 1 ykyohei so  27G Feb 24 13:08 hwp_angle_1704.h5
-rw-r--r-- 1 ykyohei so 1.4G Feb 24 14:57 hwp_angle_1707.h5
-rw-r--r-- 1 …

Compress h5 output of axisman.save

---

sotodlib/io/imprinter.py

Looked into the code, and turns out the bookbinder just copies every npy file into the book, so I think that should not be a problem with bias waves: https://github.com/simonsobs/sotodlib/blob/468bd7f75eddb2b324a40a0c17917056221b21f4/sotodlib/io/bookbinder.py#L1157-L1160
The added lines just correctly point to the copied bias_waves file in M_index yaml file.

Adds bias wave metadata to metadata index

---

sotodlib/hwp/hwp.py
sotodlib/preprocess/processes.py

This allows the signal argument to be passed to the `EstimateHWPSS` class. The check for a signal that disables the prefilter is needed because the [filters module does not support other axes](https://github.com/simonsobs/sotodlib/blob/c65acf976e0bd2a6f190187478c1de34f6964ddc/sotodlib/hwp/hwp.py#L94-L99).
I tested this with this script:
```python
import yaml
import numpy as np
from sotodlib import core, preprocess
configs="/so/home/koopman/hackathon/preprocess_config_cmb_240301.yaml"
configs = yaml.safe_load(open(configs, "r"))
ctx = core.Context('/so/home/msilvafe/shared_files/contexts/satp1_scr3_context_20240125.yaml')
aman = ctx.get_obs('obs_1704770693_satp1_1111111', dets={'wafer_slot':'ws0'})
aman.restrict('dets', aman.dets.vals[:10])
x = np.ones(shape)*np.sin(2*aman.hwp_angle) …
```

Add signal arg to `EstimateHWPSS`

---

sotodlib/site_pipeline/update_smurf_caldbs.py

Katie found an error that causes smurf_caldbs pipeline script to fail when `root_dir` is set but not `failed_obsid_cache`.

Fix bug when failed cache is not set

---

docs/preprocess.rst
sotodlib/preprocess/processes.py

Title basically says it all. The yaml will be more useful for users writing a preprocess config file.
I added missing classes to the `preprocess.rst` file when I found missing ones with example config blocks in their docstrings.
I also indented the yaml with two spaces, as that seemed like convention in the head of the preprocess configs I've been working with.

Convert example preprocess configs to valid yaml

---

sotodlib/core/axisman.py
tests/test_core.py

Slices need to be copied when restricting with `in_place=False`. Also added a test to catch this error and a comment to remind us not to change the nested in_places. 
Closes https://github.com/simonsobs/sotodlib/issues/636

Make copy of slices because slices are pointers

---

sotodlib/hwp/g3thwp.py
sotodlib/site_pipeline/make_hwp_solutions.py

To address this issue https://github.com/simonsobs/sotodlib/issues/689
- Split h5 files by first 4 digits of Unix time. This might be temporary solution.
- Make make_hwp_solutions.py robust to temporary IO blocking.
We update the version of `hwp_angles` with this PR. Identifier: `satpX_hwp_angles_240301m`
Documentation: https://simonsobs.atlassian.net/wiki/spaces/PRO/pages/306708481/hwp+angles+Metadata+Version+Log#240301

Split hwp h5 files

---

docs/site_pipeline.rst
sotodlib/coords/det_match.py
sotodlib/site_pipeline/update_det_match.py

A few updates to `det_match` and `update_det_match` that I added when creating new solutions and a new manifestdb for sat1 wafers.
Detmatch changes:
- PointingConfig class used to help with generating pointing from an optics model
- `ResSet.from_wafer_info_file` fn to load a resonator set with resonator design info based on Matthew's wafer_info file.
- In `ResSet.from_array`, adds option to ignore extra field, which lets you load older ResSet data after the Resonator interface has changed.
- Bug fixes in the `get_stats` fn.
update_det_match change:
- Begins to support different "solution-set" configurations. Adds some solution configuration that allows you to base matches off of a dir of npy ResSet files instead of kaiwen's solutions in site-pipeline-configs. I expect this to evolve as we …

Updates to det-match and site-pipeline-script to create better solutions

---

sotodlib/preprocess/processes.py

This PR implements two things in the `Calibrate` operation:
1. Passing the `signal` arg to `Calibrate`
2. Passing an array to `Calibrate`, which provides a calibration factor per detector
The signal arg was tested with a script like:
```python
import yaml
import numpy as np
from sotodlib import core, preprocess
configs="/so/home/koopman/hackathon/ppc_cal_pw_cmb_240301.yaml"
configs = yaml.safe_load(open(configs, "r"))
ctx = core.Context('/so/home/koopman/hackathon/satp1_scr3_context_20240125.yaml')
aman = ctx.get_obs('obs_1704770693_satp1_1111111', dets={'wafer_slot':'ws0'})
aman.restrict('dets', aman.dets.vals[:10])
shape = (aman.dets.count, aman.samps.count)
x = np.random.rand(*shape)
aman.wrap('test', x, [(0, 'dets'), (1, 'samps')])
pipe = preprocess.Pipeline(configs["process_pipe"]) …
```

Prepare `Calibrate` for preprocess integration

---

docs/tod_ops.rst
sotodlib/preprocess/processes.py

I tested this with this `process_pipe`:
```
process_pipe:
- name : "psd"
signal: "signal" # optional
wrap: "psd" # optional
process:
psd_cfgs: # optional, kwargs to scipy.welch
nperseg: 1024
wrap_name: "psd" # optional
calc: True
save: True
- name: "noise"
calc:
low_f: 5
high_f: 10
save: True
select:
max_noise: 2000
```
The changes below were mostly in response to each failed run of the pipeline. I think this should probably be tested with a more complicated "noise" config before merging though.

Generalize passing psd and fit cfgs to Noise operation

---

sotodlib/site_pipeline/analyze_bright_ptsrc.py
sotodlib/site_pipeline/check_book.py
sotodlib/site_pipeline/make_book.py
sotodlib/site_pipeline/make_hwp_solutions.py
sotodlib/site_pipeline/preprocess_tod.py
sotodlib/site_pipeline/update_book_plan.py
sotodlib/site_pipeline/update_g3thk_database.py
sotodlib/site_pipeline/update_g3tsmurf_db.py
sotodlib/site_pipeline/update_librarian.py
sotodlib/site_pipeline/update_obsdb.py
sotodlib/site_pipeline/update_smurf_caldbs.py
sotodlib/site_pipeline/util.py

logger arg in main functions of each site_pipeline script is to provide a way to pass prefect logger into the script. Now we are using stream capture, so directly passing in logger is no longer required. Directly modifying function signature is also somewhat unstable. This PR is meant to go along with the incoming update in prefect wrapper: https://github.com/simonsobs/so-workflow/pull/33

remove logger arg of the main function in site_pipeline scripts

---

sotodlib/hwp/g3thwp.py

Found a hwp angle glitch due to the overflow of the 32 bit internal counter of the bbb in `obs_1704077057_satp3_1111111`, and implemented process to detect and correct this type of hwp angle glitch.
I note that there is another type of glitch due to noisy quad in this observation that is independent from this bug.
We will address in another PR.

G3thwp overflow glitch

---

sotodlib/site_pipeline/make_hwp_solutions.py
sotodlib/site_pipeline/update_obsdb.py
sotodlib/site_pipeline/util.py

fixed a bug in init_logger introduced by #731 : if handler exists, formatter will be undefined. Also prefer shorter names in site-pipeline loggers.

logger fix and shorter logger name

---

docs/conf.py

This removes `html_theme_path` in order to fix search.
Search works locally, but not on the readthedocs website. This was suggested as a possible fix in [1].
Will test in the docs build on this PR.
[1] - https://stackoverflow.com/a/77358365

Fix search on readthedocs website

---

docs/index.rst
docs/metrics.rst
sotodlib/preprocess/core.py
sotodlib/preprocess/processes.py
sotodlib/qa/__init__.py
sotodlib/qa/metrics.py
sotodlib/site_pipeline/record_qa.py

I fleshed out one way that recording QA metrics could work in `preprocesstod`. This is very much a work in progress and I haven't tested anything at all, but I thought it would be useful to get some feedback on whether or not this may be a good approach (and on all the ways I am misunderstanding the codebase!).
I tried to integrate it into the `preprocesstod` flow, while making it possible to run after the fact without loading the data. Not sure if this ends up being awkward in the end... One limitation may be that this results in recording a single `detset` at a time, because this is how `preprocesstod` does it, but otherwise it might be more efficient to load it all at once (?).

[WIP] QA metrics for preprocesstod

---

docs/coords.rst
sotodlib/coords/demod.py
tests/test_demod_map.py

We need a function to generated TOD from signal only map to validate our preprocess functions and calculate transfer function.
Basic code already exists in `coords.P.from_map`.
But we should again consider the coordinates for w/ HWP configuration as [Carlos and Matthew's PR](https://github.com/simonsobs/sotodlib/pull/720).
(BTW, thank you so much Carlos and Matthew for fixing the bug!)
The new function is shown below.
It receives an axismanager with `timestamps`, `focal_plane`, and `boresight` and input T,Q,U maps. And it returns timestreams.
https://github.com/simonsobs/sotodlib/blob/be2ee3e4ba775101be40874de5f310939f5e2c81/sotodlib/coords/demod.py#L145-L182
Please see the log book
https://simonsobs.atlassian.net/wiki/spaces/PRO/pages/337772548/Transfer+Function
or
`computeXX: …

Quick map-to-tod function for SAT (for the purpose of transfer function)

---

docs/context.rst
sotodlib/core/axisman.py
sotodlib/core/axisman_io.py
sotodlib/core/metadata/loader.py
sotodlib/io/metadata.py
tests/test_context.py
tests/test_core.py

When concatenating AxisManagers (during metadata loading):
- Non-dets vectors that contain nans do not automatically trigger a concatenation failure.
- You can use metadata spec entry like `drop_fields: ["one", "two", "other_*"]` to discard things before concatenation. 
- We don't concatenate single items any more, we just return them.

Improve AxisManager concatenation (for metadata loading)

---

sotodlib/core/axisman.py
sotodlib/hwp/hwp.py
sotodlib/preprocess/core.py
sotodlib/preprocess/processes.py
sotodlib/site_pipeline/preprocess_tod.py
sotodlib/tod_ops/fft_ops.py
sotodlib/tod_ops/flags.py
tests/test_preprocess.py
tests/test_tod_ops.py

Using to AxisManagers to solve the preprocess selection issue. Should also solve #712  but not tested yet.
This PR adds another AxisManager inside of the preprocess Pipeline that is used to track the original size of the TOD AxisManager. At every step any new fields in `proc_aman` are added to the `full` AxisManager after they are expanded in size to match the original shape of the TOD AxisManager.  This expansion assumes that each top-level entry in `proc_aman` is an AxisManager (true for all existing processes, so now just required) and it was complicated enough to start test cases to make sure it works the way we'd like.

Preprocess Full

---

sotodlib/hwp/hwp.py
sotodlib/preprocess/core.py
sotodlib/preprocess/processes.py
sotodlib/tod_ops/fft_ops.py

This PR amounts to adding a full samps -- `fsamps` and full dets -- `fdets` which we fill with a nominal value at the beginning before calculating anything in preprocess. Then as preprocess proceeds and the dets or samps axis gets restricted the data is sliced into the full dets and full samps so that it's not further restricted as the pipeline proceeds. This amounts to keeping all of the calculated values and flags at the shape the data was when the calculation was run.

Keeping metadata shape even with preprocess select=True.

---

sotodlib/site_pipeline/analyze_bright_ptsrc.py

Adds some det-pointing fitting functions developed during the hack session. 
The `pointing_quickfit` function fits pointing for a bright source (such as the moon) for a detector. It has a few differences with respect to the full point source fits, including:
- downsampling signal between filtering and fitting
- only fitting xi and eta, with other beam params fixed
- Use scipy.optimize.minimize instead of curve-fit
- model is filtered at each iteration
The function takes 1-2 sec per detector, and results agree nicely with tomoki's map-based pointing (see below for ws:
Some missing dets can hopefully be recovered  using jump-fixes and flags dbs.
A few additional added functions:
- `quickfit_and_save_pointing` runs the fit on specified channels in an axis-manager, and saves the fitted xi, …

pointing quickfit for time domain fitting

---

sotodlib/hwp/hwp.py

@samdayweiss raised in slack that the docstring lists the default bins at 3600 but its actually 360 in the hwp.get_hwpss function. Updated the docstring here.

Fix docstring for bins to reflect defaults.

---

sotodlib/core/axisman.py

I keep getting annoyed that I can't do this and don't think I am alone.
In and ideal world maybe we want all the np fancy indexing but I think this is by far the most common use case and will be nice to have.

Allow labelaxis to be restricted by a mask

---

sotodlib/site_pipeline/preprocess_tod.py

This update allows us to run `site_pipeline.preprocess_tod` on multiple sub groups for example a config file that specifies:
```
subobs:
use: ['wafer_slot','wafer.bandpass']
```
Will process the data in len(wafer_slot) x len(wafer.bandpass) subsets of detectors at a time. The logs for a single subset look like this:
```
108.230: Beginning run for obs_1704770693_satp1_1111111:['ws0', 'f090'] (INFO)
117.809: Running flag_turnarounds (INFO)
Ranges(n=479864:rngs=28)
119.300: Saving data to /so/home/msilvafe/shared_files/preprocess/satp1_test/preprocess_archive.h5:obs_1704770693_satp1_1111111_wafer_slot_ws0_wafer.bandpass_f090 (INFO)
119.335: Saving to database under {'obs:obs_id': 'obs_1704770693_satp1_1111111', 'dataset': 'obs_1704770693_satp1_1111111_wafer_slot_ws0_wafer.bandpass_f090', …
```

Add ability to run on multiple subgroups

---

sotodlib/preprocess/core.py
sotodlib/site_pipeline/preprocess_tod.py
sotodlib/tod_ops/flags.py

This cleans up the logs:
- Removes a print from turnaround flagging
- Moves running <process> to debug instead of info log level
I tested this log-level + print statement running a single obs through preprocess_tod.main() in a jupyter nb.
It also fixes a bug in PR #804 that we didn't test for where it will fail when trying to find which obs + subobs to restart at when starting the preprocess_tod script running in "update mode" on an existing db. I've tested that this works on the satp3 database which I was running last night off of master post PR #804 merge and which failed when I tried to restart it this morning.

Fix subgroup restart and cleanup logs msgs.

---

sotodlib/io/load_book.py

This is faster when only a subset of detectors are being loaded.
G3SuperTimestream.extract is available in so3g v0.1.13

io.load_book: use G3SuperTimestream.extract, if available

---

sotodlib/site_pipeline/preprocess_tod.py

This adds the ability to restrict by passing a dets dictionary or meta AxisManager as can be done in ctx.get_obs and ctx.get_meta when running `site_pipline.preprocess_tod.load_preprocess_tod`
I tested this by running it as is now (where all wafers/dets are loaded at once) and then restricting after by 
```
aman.restrict('dets', aman.dets.vals[(aman.det_info.wafer_slot == 'ws0') & (aman.det_info.wafer.bandpass == 'f090')])
```
And confirmed that I had the same number of detectors at the end as if I ran with this new branch using:
```
aman = pt.load_preprocess_tod(oid, configs="/so/home/msilvafe/repos/site-pipeline-configs/satp1/preprocess_config_cmb.yaml",
dets={'wafer_slot':'ws0', 'wafer.bandpass':'f090'})
```

Add meta and det_info restriction.

---

docs/preprocess.rst
sotodlib/preprocess/core.py
sotodlib/preprocess/processes.py
sotodlib/site_pipeline/preprocess_obs.py

- Fixed `update_full_aman` (and `_expand`) in preprocess core to work with aman with no signal (no dets broke the function)
- Updates to `preprocess_obs` to add Prefect capability that was added to `preprocess_tod`
- Added `tags` argument to allow querying planet scans
- Updated SSOFootprint to allow provided source list in config file (as opposed to finding nearby sources)
@guanyilun after I test run this on multiple obs and after this gets merged, I'll PR to site-pipeline-configs to get this running on Prefect.

Updates to preprocess_obs and SSOFootprint

---

docs/context.rst
sotodlib/core/metadata/loader.py
sotodlib/core/metadata/manifest.py
tests/test_context.py

This should make it easier to produce metadata products such as hwp_angles or pointing/angle correction models.
Without this fix, the hwp_angle product has needed to store the complete "dets" axis, which is awkward.  And there was no way to store a simple dict-like structure that might be applicable to many obs.

AxisManager metadata does not need dets axis

---

sotodlib/preprocess/core.py
sotodlib/preprocess/processes.py
sotodlib/qa/metrics.py
sotodlib/site_pipeline/record_qa.py

I've added some more metrics for the current `preprocesstod` output.
I was also thinking a bit about the volume of data this will be feeding to InfluxDB, and whether it will remain a sustainable rate. A very rough estimate could be that an Influx line is up to 1 kB (1000 char, no compression), and here I am saving one line per detector per obs_id. If there are order tens of thousands of detectors for the full observatory, that would come to tens of MB per obs_id. Is that sensible?

More preprocess metrics

---

sotodlib/core/context.py
sotodlib/core/util.py
sotodlib/io/bookbinder.py
sotodlib/io/datapkg_utils.py
sotodlib/io/g3thk_db.py
sotodlib/io/imprinter.py
sotodlib/io/imprinter_cli.py
sotodlib/io/imprinter_utils.py
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/make_book.py
sotodlib/site_pipeline/update_book_plan.py
sotodlib/site_pipeline/update_g3thk_database.py
sotodlib/site_pipeline/update_g3tsmurf_db.py

Large overhaul of data packaging. Parts of this running on site.
Things implemented in this PR:
* General
* Add a load_configs function that accepts tags from either a file name or environment variable pointing to a file. This substitutes in tags so that we can more easily work inside and outside the docker environments. We can also use this for easily switching between to test environments.
* Made the analogous updates to the site-pipeline-configs configuration files https://github.com/simonsobs/site-pipeline-configs/pull/64 
* Setup instructions here: https://simonsobs.atlassian.net/wiki/spaces/PRO/pages/248972873/Site+Automation+Upkeep+Data+Packaging+and+Site+Pipeline#Building-a-personal-development-environment 
*  Imprinter related
* database has to be explicitly told to start a new …

Data Packaging Updates

---

docs/obs_ops.rst
sotodlib/obs_ops/__init__.py
sotodlib/obs_ops/splits.py

Functions for detector splits. First we start with a relative detector function, then we can add an absolute splits, etc.

Functions for detector splits

---

sotodlib/tod_ops/jumps.py

I guess this disappeared at some point. Thanks to @ktcrowley for noticing.

fix: add in colon in jumpfixing that disapeared

---

sotodlib/qa/metrics.py

In `use_this.yaml` `"label"` is used.

fix(qa.metrics): Rename label in context file parsing.

---

setup.py
sotodlib/io/bookbinder.py
sotodlib/io/datapkg_utils.py
sotodlib/io/imprinter.py
sotodlib/io/imprinter_cli.py
sotodlib/io/imprinter_utils.py
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/update_g3tsmurf_db.py
sotodlib/site_pipeline/update_librarian.py
tests/test_bookbinder.py

We ran into an issue today where one UFM streamed for ~3 hours while all the others were being turned off and on. This was an exact issue we'd said we "wouldn't deal with" but we need the drone data and the update functions were going to keep throwing errors about it. We can't automate a fix but this set of code makes it easier to manually fix these events. 
(1) the error is now a useful printout instead of just a uniqueness database constraint error
(2) we have a helper function to isolate the offending time range and make it easy to choose which book the overlapped observation goes in to. 
```
rsets = utils.find_overlaps(imprint, 'obs_ufm_mv9_1714406208', min_ctime, max_ctime)
imprint.register_book( rsets[0], commit=True)
```
(3) the update function now removes already registered level …

Deal with overlapping observations

---

sotodlib/tod_ops/filters.py

As the level3 data has iir_params one layer deeper than level2:
```
tod.iir_params
```
is
```
AxisManager(per_stream, ufm_mv22*)
```
So I modified defaulting lines of `tod_ops.filters.iir_filter`
From:
```
if a is None:
if iir_params is None:
iir_params = 'iir_params'
if isinstance(iir_params, str):
iir_params = tod[iir_params]
try:
a = iir_params['a']
b = iir_params['b']
fscale = iir_params['fscale']
```
To:
```
if a is None:
if iir_params is None:
iir_params = 'iir_params'
if isinstance(iir_params, str):
iir_params = tod[iir_params]
if 'a' not in list(iir_params._fields.keys())::
iir_params = iir_params[list(iir_params._fields)[1]]
try:
a = iir_params['a']
b = iir_params['b']
fscale = iir_params['fscale']
```
Then people can apply de-phasing filter just by:
```
iir_filt = …
```

get iir_params from tod.iir_params[`stream_id`]

---

sotodlib/toast/ops/load_context.py
sotodlib/toast/ops/mlmapmaker.py
sotodlib/toast/scripts/so_convert.py
sotodlib/toast/workflows/job.py

- Add support for both collective and independent reading of data from the context.
- Add support for specifying the full detector selection dictionary.
- Add ability to apply preprocessing if a preprocessing config is specified.
- Avoid loading any data when distributing observations among process groups.
- In mlmapmaker wrapper, disable MPI in pixell if it is disabled in toast.  This prevents mpi4py imports on NERSC login nodes.
- Small fix in specifying workflow configs when running interactively.

Improvements to toast context loading plus small fixes

---

docs/hkdb.rst
docs/index.rst
docs/site_pipeline.rst
sotodlib/io/hkdb.py
sotodlib/site_pipeline/update_hkdb.py

This is a draft PR with an initial level-3 housekeeping indexing and loading framework.
Docs will come shortly, but this can currently be used and tested on satp1 data, since I have a satp1 index that should be up to date as of 03/28.
First create a hk.yaml file to use as configuration, such as:
```
hk_root: /so/data/satp1/hk
hk_db: /so/home/jlashner/work/daily/2024-03-28/l3-hk/satp1_hk.db
aliases:
fp_temp: cryo-ls372-lsa21yc.temperatures.Channel_02_T
```
Then in python, you can load data the last week's worth of focal-plane temps as follows
```
t1 = time.time()
t0 = t1 - 7*24*3600
cfg = hkdb.HkConfig.from_yaml('hk.yaml')
ls = hkdb.LoadSpec(
cfg=cfg,
fields=['cryo-ls372-lsa21yc.*.*'],
start=t0, end=t1,
)
res = hkdb.load_hk(ls, show_pb=True)
plt.plot(*res.fp_temp)
```

Level-3 HK database and loading framework

---

docs/toast.rst
sotodlib/toast/workflows/__init__.py
sotodlib/toast/workflows/proc_flagging.py
sotodlib/toast/workflows/proc_noise_est.py

There are two instances of this operator:  one for flagging outliers prior to any processing, and one for quick noise estimation prior to mapmaking.

Add sample-diff white noise estimates to workflow tools

---

docs/hwp.rst
sotodlib/hwp/g3thwp.py
sotodlib/hwp/hwp_angle_model.py
sotodlib/site_pipeline/make_hwp_solutions.py

This PR updates hwp_angles metadata and implement apply_hwp_angle_model
- Add draft of apply_hwp_angle_model https://github.com/simonsobs/sotodlib/discussions/735
- We still need to implemenet hwp_angle_model metadata
- Previously make_hwp_solution was correcting relative hwp rotation direction between observations using configured method, but removed this correction from make_hwp_solution to implement more robust correction in apply_hwp_angle_model
- Add sotodlib version to hwp_angles metadata https://github.com/simonsobs/sotodlib/issues/776
- Split hwp_angles metadata more https://simonsobs.slack.com/archives/C05K7CSFTPX/p1712183463493169
- This is necessary for more efficient hwp metadata data transfer
- Save fast/slow data into different HDF5 files.
- Split HDF5 file by first 4 digits …

Hwp metadata update

---

sotodlib/toast/workflows/proc_mapmaker.py

Not all workflows use all possible noise estimation techniques.  When selecting the noise model for the mapmaking, check for existence before checking if it is enabled.

Small bug fix for corner case introduced in #843

---

sotodlib/hwp/g3thwp.py
sotodlib/site_pipeline/make_hwp_solutions.py

Delete dets axis from hwp_angles metadata, to fix the issue that the all the detectors get eliminated when we load data with hwp_angles metadata.
Actually dets axis was always included in hwp metadata. This became a problem because we changed the timestamp loading from ctx.get_obs(obs_id, no_signal=True) to ctx.get_obs(obs_id, dets=[]) in https://github.com/simonsobs/sotodlib/pull/809

hwp_metadata delete dets axis

---

setup.py

Adds `venn` package dependency to extras `sotodlib[site_pipeline]`, used in `plot_det_bias_flags`

Add venn package dependency

---

sotodlib/tod_ops/filters.py
tests/test_tod_ops.py

Also minor code simplifications and tests for both the dict interface and the nested parameter support.

tod_ops.filters: restore iir_filter params as dict

---

sotodlib/preprocess/pcore.py
tests/test_preprocess.py

Random access (especially random writes) of sparse arrays is inefficient, so construct it from base data as efficiently as possible.
I also expanded the unit tests to make sure treatment of sparse arrays matches treatment of a full array.
On my test machine, with biggish arrays and 5% density, this is over 10 times faster and takes much less RAM.

Faster sparse matrix expansion for preprocess

---

setup.py

This PR adds the `psycopg2-binary` requirement, which is necessary for reading and updating postgres databases such as hkdb.

Adds psycopg2-binary requirement for hkdb

---

sotodlib/hwp/hwp_angle_model.py

Explanation of hwp encoder origin offset. This correction was missing.
https://simonsobs.atlassian.net/wiki/spaces/PRO/pages/466845698/HWP+encoder+origin+offset
Documentation of hwp_angle.
https://simonsobs.atlassian.net/wiki/spaces/PRO/pages/235372640/HWP+Data+Products

hwp encoder origin offset correction

---

sotodlib/coords/pointing_model.py
tests/test_pointing_model.py

Implements encoder offsets, base_tilt, and focal plane center of boresight rotation.
Given our current pointing products (measured at boresight=0), a model that specifies "bs_xi0" and "bs_eta0" should be able to cancel the pointing shifts in SATP1 arising from boresight != 0.

pointing_model: sat_v1 begins

---

sotodlib/toast/ops/act_sign.py
sotodlib/toast/ops/load_context.py
sotodlib/toast/ops/load_context_utils.py
sotodlib/toast/scripts/so_map.py
sotodlib/toast/workflows/sim_observe.py

- Extract many functions into a separate source file.
- Change the way that data is read.  The first process with data from a wafer is the reading process for that wafer.  Each reading process loads the data and optionally applies the HWP model and preprocessing.
- More robust and general distribution of detector data on the group communicator.
- Correct support of observing sessions.  By default each Context obs ID is split into observations with one per wafer.  This can be overridden to place all wafers into a single observation if desired.
I have tested this on a single observation and verified consistent binned maps in the following cases:
1. Single wafer, single process group, [1, 4, 16, 64, 128] processes.
2. Two wafers, single process group, [4, 16, 64, 128] processes, both …

Reimplementation of LoadContext Operator

---

sotodlib/toast/instrument.py

Found another stale branch. This one seems still relevant.

Apply net_corr factors by default to TOAST focalplanes

---

setup.py
sotodlib/toast/ops/splits.py
sotodlib/toast/scripts/so_transfer.py
sotodlib/toast/workflows/proc_mapmaker.py

This is currently a work in progress.  Immediate focus is the `toast_so_sat` workflow for producing maps of splits.

Implement transfer function workflow with splits

---

sotodlib/core/axisman.py
tests/test_core.py

Currently if you try to wrap a field into an axis manager which already exists it will fail, this adds an overwrite argument which will write over the existing data in that field if true.

Adds the ability to overwrite existing fields.

---

sotodlib/mapmaking/demod_mapmaker.py

I added the calculation of the map in the demod mapmaker object, but now I'm realizing this makes no sense since this can be potentially repeated in every MPI job. I believe it makes much more sense to not have it here and do the inverse of the weights times the weighted map on the script side, where you can have much more control over exactly what you want to do.

Removing the map = weights^-1*wmap calculation

---

docs/g3tsmurf.rst
docs/requirements.txt
docs/rtd_requirements.txt
setup.py
sotodlib/coords/planets.py
sotodlib/io/bookbinder.py

Fixes a few issues with CI recently:
- pin numpy<2, because so3g probably segfaults otherwise.
- fix some warnings in docs build that have been rising to error level (including asserts that were malformed)

Pin numpy<2 in package reqs and docs

---

sotodlib/site_pipeline/update_det_match.py

This PR protects against the problem found by SATP3 where a detset was added to the failed-file-cache before any observations were added, even though it was a valid tune.
To protect against this, the script will now find the associated timestamp of the detset and check that it has been more than `cfg.time_before_cache_failure` sec before adding it to the failed cache.

Detmatch cache time limit

---

sotodlib/toast/workflows/scripting.py

When using simulated observing and nominal noise models, setup pointing first.

Trivial fix for case of simulated elevation weighted noise models

---

sotodlib/preprocess/pcore.py
sotodlib/preprocess/processes.py
sotodlib/site_pipeline/preprocess_tod.py
sotodlib/tod_ops/fft_ops.py

This PR includes new functions to process a simulation following the data processing (using PR #873) : 
- New function `site_pipeline/preprocess_tod.load_preprocess_tod_sim` that allows to load a CAR map into tods
- Changes of the `Pipeline.run()` method allowing to skip some steps in the pre-processing configuration file with a boolean flag `skip_on_sim`
- New function to derive the median across detectors of the noise fit parameters to allow for non-fixed parameters in the pre-processing configuration file in the `fourier_filter` steps.
e.g. : 
```
- name: "fourier_filter"
signal_name: "demodU"
wrap_name: "demodU"
process:
filt_function: "counter_1_over_f"
trim_samps: 2000
noise_fit_params: True
noise_fit_array: "noiseQ_fit"
filter_params:
fk: "fknee"
n: "alpha"
```

Use of preprocessing database to process simulated data

---

sotodlib/tod_ops/flags.py

In `get_ptp_flags`, if there are nans in the data the `while True` loop will continue to infinity.

Fixing infinite loop if there are nans in the data for get_ptp_flags

---

sotodlib/qa/metrics.py

A change in the preprocess context file was preventing the QA script fro starting.
@guanyilun How do I proceed to deploy this change to site?

fix(qa.metrics.PreprocessQA): Reliably get db file from context.

---

sotodlib/site_pipeline/record_qa.py

If crucial metadata like the det_match is missing, catch the exception and proceed with following obs_id's.

fix(site_pipeline.record_qa): Catch errors on loading metadata.

---

sotodlib/site_pipeline/update_obsdb.py

Creates two new columns in ObsDb with respectively stream_ids and wafer_slots for each observation, as comma separated strings. E.g. wafer_slots_list: 'ws0,ws1,ws2,ws3,ws4,ws5,ws6' and stream_ids_list: 'ufm_mv19,ufm_mv18,ufm_mv22,ufm_mv29,ufm_mv7,ufm_mv9,ufm_mv15'

Track stream_ids and wafer slots

---

sotodlib/mapmaking/utilities.py

This fix allows for the downsampling to be used in the ML mapmaker / depth-1 mapmaker. @iparask you left a comment about this some months ago. The partial solution we have for now is that obs.flags will contain all processing flags, including glitch_flags, etc. In the future we want to make the flags location and names to be user-defined in a config file or something, but this other solution is what we use in the mean time in other sections of the mapmaker. @tanaybhandarkar has also worked on this with me.

Fix for flags and downsampling.

---

sotodlib/hwp/hwp_angle_model.py

The hwp angle model for satp2 has been added.
The definition of the rotation angle and angle offset is based on this page.
https://simonsobs.atlassian.net/wiki/spaces/PRO/pages/185434251/CHWP+main+page#Rotation-direction-definition

Add hwp model for satp2

---

sotodlib/site_pipeline/update_det_match.py

Currently SATP3 detmatches are being held up because the script loops infinitely if a match fails but is too new to add to the file cache. This addresses that bug, and resolves https://github.com/simonsobs/sotodlib/issues/956.
This has been tested by rebuilding the satp3 detmatch db in my home dir.

Fix infinite loop in det-match script

---

sotodlib/coords/planets.py

Added a function to generate a projection matrix for an arbitrary source in horizon coordinates.
This will be especially useful for the drone mapmaking.
For example, one can make a drone map measured by SAT as follows.
```
P = coords.planets.get_horizon_P(tod, az, el, geom=geom, comps='TQU', hwp=True)
map = coords.demod.make_map(aman, P=P)
```
@axf295 already demonstrated drone mapmaking using an equivalent code.

add get_horizon_P

---

setup.py
sotodlib/site_pipeline/preprocess_obs.py
sotodlib/site_pipeline/preprocess_tod.py

Adds [lmsi](https://github.com/jborrow/lmsi) to `preprocess_obs` and `preprocess_tod` site pipeline scripts, to be used on prefect. To use, simply add the path to the lmsi config file as `lmsi_config` in the preprocess config. This will produce an HTML file to serve the plots as a simple gallery. @guanyilun has already run a catchup on the existing plot directories.

Add lmsi to preprocess_obs and preprocess_tod

---

sotodlib/io/g3tsmurf_db.py
sotodlib/io/imprinter_utils.py

Found while trying to close our some LAT time codes. Change the unique constraint to deal correctly with different servers. 
closes #960 
To update existing tables will need to run. (I'll take care of doing this on site)
```
CREATE TABLE time_codes_new (
id INTEGER NOT NULL, 
stream_id VARCHAR, 
suprsync_type INTEGER, 
timecode INTEGER, 
agent VARCHAR, 
PRIMARY KEY (id), 
UNIQUE (stream_id, suprsync_type, timecode, agent)
);
INSERT INTO time_codes_new SELECT * from time_codes;
DROP TABLE time_codes;
ALTER TABLE time_codes_new RENAME to time_codes;
```

Fix unique constraint and indent logic error

---

docs/site_pipeline.rst
sotodlib/site_pipeline/jobdb.py
tests/test_jobdb.py

Exposes a job manager, which uses a database to help with managing the data reduction lifecycle: identify work; try (perhaps many times) to do the work; succeed or eventually give up.
Also:
- Database makes it easier to run multiple data reduction processes on the same set of jobs -- each worker locks the job they are working on.
- Database helps track "visit_count" and last "visit_time", to help with try, retry, retry, ... give up sequences.
- CLI helps with inspecting / modifying the jobs table (e.g. to clear stale locks, "ignore" bad jobs, mark things for retry).
- Tested with sqlite and postgres.
(Couple more commits coming here, for docs and to expose the CLI.)

site_pipeline.jobdb

---

sotodlib/hwp/g3thwp.py
sotodlib/site_pipeline/make_hwp_solutions.py

There were hwp angle nan issues in the observations that the hwp stopped in the middle of observations. https://github.com/simonsobs/sotodlib/issues/966
This is because the old hwp angle extrapolation method returns nan when the data range of hwp angle is shorter than the range of observation. This PR improves the hwp data extrapolation methods in general and resolves the nan issue.
This PR also improves the logging of hwp solution pipeline.
This PR does not change the pipeline output except for edge cases, so I do not plan to update the version of hwp_angles metadata.

G3thwp nan fix

---

sotodlib/site_pipeline/update_det_cal.py
sotodlib/site_pipeline/update_smurf_caldbs.py

This resolves #1012 , where update_smurf_caldbs fails when the bias voltage on lines >= 12 are not nan in the bias step analysis.

Fix caldb issue with bias lines >= 12

---

.github/workflows/test.yml
setup.py

Removing 3.8 broke socs builds; sorry!
Although 3.8 is end-of-life now, and 3.9 was released more than 3 years ago, it ain't broke so let's not drop it yet.
On the test matrix: it is more important to test the legacy edge (3.8, 3.9) and the bleeding edge (for us, 3.11) than to test intermediate releases.

Restore Python 3.8 support for now

---

sotodlib/site_pipeline/record_qa.py

I mocked up my understanding of how JobDB could be used to track processed observations in the `record_qa` metrics pipeline. I'm using it pretty minimally with the main objective to avoid re-attempting to process observations that failed previously. We could consider exercising some more functionality like retrying some number of times before quitting.
@mhasself if you have time to take a look and let me know if what I did makes sense, I'll proceed to testing this out next.

feat(site_pipeline.qa): Use JobDB to track processed observations.

---

docs/coords.rst
sotodlib/coords/__init__.py
sotodlib/coords/healpix_utils.py
sotodlib/coords/helpers.py
sotodlib/coords/pmat.py
sotodlib/mapmaking/demod_mapmaker.py
sotodlib/mapmaking/utilities.py
tests/_helpers.py
tests/test_demod_map.py
tests/test_demod_mapmaker.py
tests/test_pmat.py

Add healpix support to the sotodlib mapmaking module.
Includes some re-factoring of demod_mapmaker to minimize code duplication

Merge healpix mapmaker

---

sotodlib/io/hkdb.py

This fixes a bug when indexing hk files, which currently fails when the db has a combination of relative and absolute paths.

Fixes bug in HKDB file-indexing

---

docs/site_pipeline.rst
sotodlib/io/so_ufm.py
sotodlib/site_pipeline/make_det_info_wafer.py

- Support bandpass remapping so we can make UHF info from files that insist the two bands are 90 and 150
- Change mux_subband 'NC' indicator from '-1' to 'NC'. This was found because if you include -1 in an array of strings, the dtype becomes 'U21' or larger... that's too much.
- Apply --overwrite option to also clobber manifestdb entry.
@skhrg Heads up the LAT UHF wafer_infos should be redone with the bandpass_remap option, too.

make-det-info-wafer: updates and fixes

---

docs/preprocess.rst
sotodlib/coords/helpers.py
sotodlib/mapmaking/demod_mapmaker.py
sotodlib/preprocess/__init__.py
sotodlib/preprocess/preprocess_util.py
sotodlib/site_pipeline/preprocess_obs.py
sotodlib/site_pipeline/preprocess_tod.py
sotodlib/site_pipeline/update_preprocess_plots.py
sotodlib/site_pipeline/util.py

This branch moves around some of the preprocessing functions into a common `preprocessing/preprocess_util.py` file.  The ones moved specifically are:
- `load_preprocess_det_select`
- `load_preprocess_tod`/`load_preprocess_obs` (merged into `load_and_preprocess`)
- `preproc_or_load_group` (to address #1025)
- `cleanup_mandb`
Some of these aren't shared among multiple files yet but they will be when #1026 is merged.  Note that the inputs of `load_and_preprocess` are slightly modified from `load_preprocess_tod`/`load_preprocess_obs`.  It now accepts `no_signal` which defaults to `None` and the `dets` and `meta` inputs not in `load_preprocess_obs` are now added.  The default config names were removed, though we could re-add them based on the value of `no_signal` perhaps.
Some additional files …

Unify preprocessing functions

---

sotodlib/mapmaking/obs_grouping.py

Addressing #1011, we use the obsdb to get the wafer list. The freq list is hard coded (if mf we do f090, f150, etc.) We need to complete this for uhf and lf in the future.

Load wafer list / freqs from obsdb

---

sotodlib/preprocess/processes.py

This branch adds an optional lowpass filter to the `PCARelCal `stage of the pipeline.  Previously, the lowpass was run as a separate filter stage before `PCARelCal` which results in a copy of timestreams being saved.  Now, the filtering occurs in the PCA `calc_and_save` function and is only temporarily stored.  The `lpf` configs, as well as the number of samples to trim, can be added to the `PCARelCal` config step.

Add lowpass filter to PCA Relcal

---

sotodlib/mapmaking/obs_grouping.py

We need this tiny fix since in TOAST sims the band flavors are defined in upper case, but the data has them defined in lower case.

Fix obs_grouping

---

sotodlib/preprocess/processes.py

This branch should address the comment made in #1050 where the number of samples between original axis manager and the processed axis manager are not the same.  The difference occurred because the original axis manager was trimmed during demodulation and the processed axis manager was then trimmed based on the already trimmed axis manager, resulting in even fewer samples.

fix mismatching samples

---

docs/preprocess.rst
sotodlib/preprocess/pcore.py
sotodlib/preprocess/preprocess_plot.py
sotodlib/preprocess/processes.py
sotodlib/tod_ops/fft_ops.py
sotodlib/tod_ops/flags.py

Add basic statistics, PSDs, and glitches on subscans.

Add subscan operations to preprocess

---

sotodlib/coords/helpers.py
tests/test_coords.py

- ignores nan positions
- processes optional "det_weights" for user-specified considerations

coords: get_focal_plane_cover masking

---

sotodlib/coords/helpers.py
sotodlib/coords/pmat.py
tests/test_pmat.py

Re-enable the test for rectpix tiled case.  This required a lot of custom checking for the rectpix+tiled case... and when combined with the healpix checking, this was hard to read.  So I've also abstracted that away using the notion of "flatten" and "unflatten" for maps.  This affects healpix and rectpix.

coords.pmat: fix tiling .from_map behavior

---

sotodlib/core/metadata/obsfiledb.py
sotodlib/io/load_book.py

Although it's usually an error load dets=[], make-hwp-solution does that, using a basic context. This re-enables that support by optimizing obsfiledb.get_files.

load_book: don't over-optimize getting the file list

---

sotodlib/mapmaking/demod_mapmaker.py
sotodlib/mapmaking/utilities.py
sotodlib/obs_ops/splits.py
sotodlib/preprocess/processes.py

This changes how the mapmaker handles the focal plane splits, so that they follow the same convention as preprocessing.
Also fixes a minor bug in preprocess.

Putting the mapmaker in the same split convention as the preprocessing

---

sotodlib/tod_ops/jumps.py
sotodlib/tod_ops/utils.py
tests/test_tod_ops.py

Realized that in some round of modifications I essentially canceled out the matched filter since I was looking for peaks in `np.diff(np.cumsum(x), 2)` which is basically just `np.diff(x)` (there is some smoothing as well).
This is because `np.cumsum(x)` makes jumps show up as slope changes unless we cross 0. In the old recursive version this was solved by mean subtracting and finding the largest jump (which crossed 0 when mean subbed) and then recursively repeating between jumps which was slow.
~~Here we solve the problem by detrending the matched filtered data which makes the slope changes look like relative extrema and then using `argrelmax` (much faster than `find_peaks`) to look for them.~~ EDIT: Actually the detrend to make things peaks doesn't work as well as I like, what does work …

Switch back to peakfinding in the matched filter

---

sotodlib/io/bookbinder.py
sotodlib/io/datapkg_completion.py
sotodlib/io/datapkg_utils.py
sotodlib/io/g3thk_db.py
sotodlib/io/imprinter.py
sotodlib/io/imprinter_cli.py
sotodlib/io/imprinter_utils.py
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/cleanup_level2.py
sotodlib/site_pipeline/update_book_plan.py

A whole bunch of updates that are complete enough and should probably be merged into main since we're now at a point of running this on-site and deployments for deletion are mostly ready to be automated. Summary of all the changes:
**DataPackage** and **cleanup_level2**
* `datapkg_completion` module has a `DataPackage` class I built to work with both G3tSmurf, G3tHK, and Imprinter at the same time to go through and do the checks necessary to make sure we're ready to delete data from each timecode. 
* re-write cleanup level 2 to use the `DataPackage` functions and to run deletion at three different phases
* Phase 1 - Completion: go through a timecode folder and make sure every single book that should exist does (planned for a 14 day lag)
* Phase 2 - delete staged files as long as …

Data Packaging Revamp

---

sotodlib/preprocess/preprocess_util.py

Fix bug with `outputs_grp` naming when deleting files.

fix bug with save_groups_and_cleanup

---

sotodlib/preprocess/preprocess_util.py
sotodlib/site_pipeline/multilayer_preprocess_tod.py
sotodlib/site_pipeline/preprocess_tod.py

Adds  some error checking around `preprocess_utils.get_groups` to catch failures related to getting det info.

Add try except to catch det_match failures

---

sotodlib/preprocess/processes.py
sotodlib/tod_ops/flags.py

Updates `SourceFlags` preprocess functions.  Adds a check to see if the input source is nearby and does the flagging as before.  Returns a zero `RangeMatrix` if no source is found.  Now, it accepts a list of sources and loops through them which are wrapped into `proc_aman.source_flags.source_name`.  Currently requires `FocalplaneNanFlags` to be run first so that any focal plane `NaNs` are removed.

Source flags update

---

sotodlib/preprocess/pcore.py
sotodlib/preprocess/preprocess_util.py

Was seeing the estimate_azss and t2p fields being written to both proc_aman and aman.preprocess but inv_var_flags and split_flags were only being written to proc_aman. I fixed this by adding a .copy() in pipe.run(). But now cfg check is failing when loading first layer and processing 2nd layer but not when processing through both.

250104 fix preproc or load group

---

sotodlib/coords/helpers.py

https://github.com/simonsobs/sotodlib/pull/1033 changed the return type of _apply_inverse_weights_map to numpy.ndarray with default arguments. This PR changes it back to pixell.enmap.ndmap.

fix _apply_inverse_weights_map

---

sotodlib/io/hkdb.py

Max was finding that repeated calls to `load_hk` was eventually causing the number of connections to max out, due to the time it takes for hkdb.Session to be garbage collected.
This change allows you to manually pass in an HkDb instance to `load_hk`, avoiding repeated calls to sessionmaker if you are calling the function in a loop.

Allows you to set hkdb object to use in LoadSpec

---

sotodlib/preprocess/processes.py

This branch is to fix a problem that arose when loading data back in that was introduced from the Source Flags preprocessing module.  Since fields are added into the axis manager, all detectors are cut when non-source entries are added.  For now, I copied the source list generation and use the fields that match sources in the source_flags axis manager.  We could alternatively just exclude "valid," but might not be future proof.

Fix for Source Flags

---

sotodlib/site_pipeline/update_obsdb.py

Makes it possible to skip the slowest step in most update_obsdb runs, crawling the entire directory from base_dir to evaluate the age of each book. If running with the command-line option --fastwalk, the code will assume the dirs are are the form base_dir/obs|oper/17493 and will figure out which 5 number directories it needs to look into.

Fast directory walk option

---

sotodlib/preprocess/preprocess_util.py

Changes cleanup_mandb to accept filenames without paths from the config file.

Allow plain filenames in cleanup_mandb

---

sotodlib/preprocess/preprocess_util.py

Minor fix to logger when running `multilayer_load_and_preprocess`.  The logging level would previously get reset due to the recursive call of `check_cfg_match`.

Minor fix for logging in multilayer_load_and_preprocess

---

sotodlib/tod_ops/t2pleakage.py

Fix the weight of t2p join fit. This was messing up the reduced chi square of t2p fitting.
I'm using lmfit version '1.3.2'.
For example, in (obs_1723613525_satp3_1111111, ws2, f090), this changes `aman.t2p_stats.redchi2s` from
```
[2.19e-09, 2.45e-09, 2.03e-09, 2.53e-09, 2.03e-09, 2.47e-09,
2.03e-09, 2.10e-09, 3.59e-09, 2.14e-09, 2.64e-09, 3.63e-09,
2.40e-09, 2.86e-09, 2.58e-09, 4.00e-09, 2.69e-09, 2.34e-09,
3.13e-09, 2.75e-09, 3.50e-09, 2.33e-09, 2.42e-09, 2.91e-09,
2.82e-09, 2.45e-09, 3.20e-09, 2.64e-09, 2.12e-09, 2.84e-09,
2.23e-09, 2.16e-09, 2.03e-09, 2.19e-09, 2.09e-09, 1.74e-09,
1.69e-09, 2.12e-09, 2.36e-09, 2.26e-09, 2.96e-09, 2.33e-09,
2.57e-09, 2.27e-09, 2.49e-09, 2.50e-09, 2.46e-09, 2.17e-09]
```
to
```
[0.99 0.97 0.95 0.95 0.95 0.94 0.95 0.99 0.96 0.98 0.95 0.97 0.95 0.95
0.96 …
```

fix t2p lmfit weight

---

sotodlib/site_pipeline/check_book.py
sotodlib/site_pipeline/update_obsdb.py

This resolves issue where update_obsdb would sys.exit when a book check failed.
So now update_obsdb doesn't call main, it calls two other functions.
@AERAdler  I have not tested the update_obsdb changes!  Please do so to confirm they behave as we want.  In particular this should raise an informative error, not exit, when it encounters a bad book.
The logging will change slightly, because the update_obsdb logger is passed into the check_book functions.

site_pipeline: check_book funcs for update_obsdb use

---

sotodlib/site_pipeline/update_obsdb.py

I went back and edited a line that looked at a book's timestamp instead of its edit time (which is what we want to look for) Now that there's the fastwalk option the line was redundent, so I replaced it with something actually useful.

update_obsdb uses book edit time instead of book_id for recency check

---

sotodlib/preprocess/preprocess_util.py

The function `multilayer_load_and_preprocess` incorrectly handled the meta information for the second layer.  It now uses the axis manager from the first layer loading as the meta axis manager.

Fix meta issue in multilayer_load_and_preprocess

---

sotodlib/core/axisman.py
sotodlib/core/axisman_io.py
tests/test_core.py

Introduces notion of Axis equality. This is to make .load work faster -- in that case you are merging in lots of AxisManagers that have already concordant axes; and even if they weren't concordant you definitely don't need to keep a copy of the unrestricted objects around while you merge.
On test case '/global/cfs/cdirs/sobs/sat-iso/preprocessing/satp1_20250108_init/preprocess_archive_932.h5', group 'obs_1730532853_satp1_1111111_wafer_slot_ws0_wafer.bandpass_f150', this reduced load time from 4.5s to 1.0s

AxisMan: faster .wrap(axisman) and .merge(...)

---

sotodlib/io/bookbinder.py

As we discussed today, the easiest way at the moment to resolve the discrepancy between the det-db and non-resonator channels existing in the data is to separate them from the 'signal' array in the bookbinder. This PR selects channels that don't have an associated stream-id or tunefile and puts them into a separate array instead of adding them to `signal`.
The implementation here may need to change if we change the readout_ids of fixed tones so they aren't marked with NONE.

Separate non-res channels into separate field in G3File

---

sotodlib/core/metadata/loader.py

Properly formats error message that occurs when there is a detector count mismatch between manifestdb and obsfiledb and adds some clarifying detail.
This error message quoted in several open issues and discussions:
- https://github.com/simonsobs/site-pipeline-configs/issues/60
- https://github.com/simonsobs/sotodlib/issues/1078

Clarify error message when there is a detector count mismatch

---

sotodlib/tod_ops/jumps.py
tests/test_tod_ops.py

Relies on https://github.com/simonsobs/so3g/pull/196 
This is a direct rewrite for the most part, no algorithmic changes.

feat: move slow jumps and jumpfix to so3g

---

sotodlib/hwp/hwp.py
sotodlib/preprocess/processes.py
sotodlib/tod_ops/azss.py
sotodlib/tod_ops/binning.py
sotodlib/tod_ops/gapfill.py

These changes make it possible to perform iterative glitch removal and HWPSS removal via the preprocessing module, as follows. I think the changes of default behaviors of GlitchFill can break previous preprocess.yaml which was relying on default parameters, but it should be easy to fix.
```
- name: "union_flags"
process:
flag_labels: ['jumps_2pi.jump_flag', 'glitches.glitch_flags', 'jumps_slow.jump_flag']
total_flags_label: 'exclude'
- name: "estimate_hwpss"
signal: "hwpss_remove"
calc:
hwpss_stats_name: "hwpss_stats"
flags: "exclude"
save: True
- name: "subtract_hwpss"
signal: "signal"
process:
subtract_name: "signal"
- name: "glitchfill"
signal: "signal"
skip_on_sim: True  # updated
process:
nbuf: 10
use_pca: False
modes: 1
glitch_flags: "exclude"
wrap: "signal"
```

Allow flags str for easy iterative glitch removal via preprocess

---

sotodlib/tod_ops/azss.py

Cherry pick from https://github.com/simonsobs/sotodlib/pull/1120
When azss bin range is wider than scanned az, the azss will be nan. We need to mask nan bins to correctly extrapolate azss.
This resolves the glitches near the boundaries of subscan induced by azss subtraction.

fix azss extrapolation

---

sotodlib/preprocess/processes.py
sotodlib/tod_ops/azss.py

I propose this way of estimation and subtraction of azss in left_going scans and right_going scans separately.
Also fixed the azss extrapolation at the boundaries of subscans. This resolves the glitches near turnarounds induced by azss subtraction.
I tested updated individual functions and a proprocess module.

add scan_flags to azss modules

---

docs/context.rst
sotodlib/core/metadata/manifest.py
sotodlib/core/metadata/obsdb.py
sotodlib/core/metadata/obsfiledb.py
tests/test_obsdb.py

This is enforced starting at sqlite3.sqlite_version 3.49.1 or so.
Resolves #1119

sqlite3: remove double-quoted string literals

---

sotodlib/mapmaking/demod_mapmaker.py
sotodlib/mapmaking/ml_mapmaker.py
sotodlib/site_pipeline/make_atomic_filterbin_map.py
sotodlib/site_pipeline/make_ml_map.py

This adds the writing of units into the fits keyword BUNIT for maps produced by the ML and atomic-filterbin mapmakers. It requires the latest branch of pixell.

Implementing units for fits maps

---

sotodlib/core/metadata/obsfiledb.py
sotodlib/io/load_book.py
sotodlib/site_pipeline/check_book.py

Two fixes needed:
- when updating obsfiledb, allow a detset to expand.
- when loading books, accept that obs might not have all the dets that listed in obsfiledb detset.
Tested on:
```
oper_1741050783_satp1_0010000
oper_1741051126_satp1_0010000
oper_1741115973_satp1_0100000
oper_1741116451_satp1_0100000
```
Resolves #1136 .  Once this is merged I can update site obsfiledb with new dets, and also add the obsfiledb index from #1127 .

check-book/load-book: handle case where obsfiledb detset is just a bounding set

---

sotodlib/io/load_smurf.py
sotodlib/preprocess/preprocess_plot.py

These are numpy 2 compatibility issues:
https://numpy.org/doc/stable/reference/generated/numpy.in1d.html
The `unicode_` is deprecated and removed. Numpy says to use `str_` instead.

numpy 2 compatibility fixes

---

sotodlib/io/bookbinder.py

Correcting an innocuous mistake I made years ago while copying over the code snippet from `io/load_smurf.py`.

Fix typo of EPICS time in Bookbinder comment string

---

sotodlib/coords/pointing_model.py

I am making this PR in response to issue #1158 raised by Kyohei. I have added the following to the end of the pointing_model.model_sat_v1 function to add or subtract 2 pi from the azimuth values if any of them are off by over 2pi from what is expected. However if not all of the azimuth values have the same issue, perhaps this should be changed to a np.all() or make changes to individual values instead of all the tod. 
```
neg_az, el, roll = quat.decompose_lonlat(q_hs)
if np.any((-neg_az - az_orig) > 2*np.pi):
new_az = -neg_az - 2*np.pi
elif np.any((-neg_az - az_orig) < -2*np.pi):
new_az = -neg_az + 2*np.pi
else:
new_az = -neg_az
return new_az, el, roll
```

Pointing model quat.deconstruct_lonlat issue

---

sotodlib/coords/planets.py

This PR is for fixing a bug for `SlowSource` Class.
Ra/Dec used in this class is in radian, but there is a line that treats in degree units.
This does not affect much, though.

fix bug SlowSource

---

sotodlib/site_pipeline/make_ml_map.py

`args.downsample` is a string of comma-separated values, and this comparison will always be true. Changing it to `passinfo` checks against an integer and specifically of the current iteration

Fix downsampling comparison

---

sotodlib/io/check_book.py
sotodlib/site_pipeline/check_book.py

This was sort of done in io.check_book, but that code segment wasn't called from update_obsdb / site_pipeline.check_book.  Now io.check_book never releases the names of the fixed tones.  The "remove_fixed_tones" work-around setting is removed, since we just always want to remove them.

update_obsdb: exclude NONE dets (fixed tones) from detsets

---

sotodlib/toast/ops/corotator.py

corotator pointing quaternion order bugfix

---

docs/hkdb.rst
sotodlib/io/hkdb.py
sotodlib/site_pipeline/update_hkdb.py
sotodlib/site_pipeline/util.py
tests/test_hkdb.py

- Each result item is a tuple of arrays, not a (2, n) array.
- Empty datasets are returned as a tuple of 0-len arrays.
- New args to load_hk for fine-tuning fields and times.
- New function get_feed_list, for inspecting db.
- "subdirs" option to make scanning hk archive subsets easier.
- Update docs for new function; add more links; more autodoc.
cf #1163 
"round2" of changes, coming later, will include a change in db schema that makes it possible to retrieve a field list without tooooo much G3 file reading.

hkdb updates -- note some API changes

---

sotodlib/coords/planets.py

get_nearby_sources used a stale signature of so3g.proj.FocalPlane.from_xieta(). From Matthew: (imperfect upgrade, 1e17035e4)

get_nearby_sources used stale signature of so3g...from.xieta 

---

sotodlib/io/bookbinder.py
sotodlib/io/datapkg_completion.py
sotodlib/io/g3tsmurf_utils.py
sotodlib/io/imprinter.py
sotodlib/io/imprinter_cli.py
sotodlib/io/imprinter_utils.py
sotodlib/io/load_smurf.py
sotodlib/site_pipeline/update_g3tsmurf_db.py

* Add autofixing for operations books with NoMountData errors (we generally don't care too strongly about the mount positions where operations take place, and/or it's find to miss the positions of some of these)
* Add option to skip the check that requires HK times to be monotonically increasing. We've seen this now around time periods where NoMountData was also getting thrown, we're going to want to be very careful about actually using this flag, (the time I saw this and I've checked that data, the mount was stationary the whole time, so I'm not worried about interpolations for that one)
* If librarian checking fails, try again (hoping that helps with caching errors at NERSC/Princeton)
* Allow over-riding ctimes for manual book making. Used once or twice when the ACU dropped out. 
* …

Data Packaging: Updates for repairing failed books

---

sotodlib/utils/procs_pool.py

This is to provide a process pool executor when MPI has only one process and fails to launch, essentially moving forward with:
```
File "/global/homes/m/mmccrack/so_home/repos/sotodlib/20250407_mpi/sotodlib/sotodlib/site_pipeline/preprocess_tod.py", line 391, in <module>
rank, executor, as_completed_callable = get_exec_env(args.nproc)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/global/homes/m/mmccrack/so_home/repos/sotodlib/20250407_mpi/sotodlib/sotodlib/utils/procs_pool.py", line 133, in get_exec_env
_get_mpi_comm()
File "/global/homes/m/mmccrack/so_home/repos/sotodlib/20250407_mpi/sotodlib/sotodlib/utils/procs_pool.py", line 34, in _get_mpi_comm
MPICommExecutor(comm, root=0, max_workers=max_workers).__enter__(), …
```

Not enough workers fix

---

sotodlib/toast/io/load_book.py
sotodlib/toast/io/save_book.py
sotodlib/toast/ops/mlmapmaker.py
sotodlib/toast/ops/save_books.py

Update all instances of TOAST `Interval` to use the new open-ended definition. The unit tests will fail until a new tag of TOAST is uploaded.

TOAST intervals are now open-ended

---

sotodlib/preprocess/processes.py

Fix for `noisy_subscan` flags.  In the loop `signal` is not a copy but a reference to `self.calc_cfgs`, so this ends up being modified when `subscan_stats` is overwritten.

Fix noisy_subscan flags config dictionary copying

---

sotodlib/coords/planets.py

Found case of `[Errno 24] Too many open files` when calling this line:
https://github.com/simonsobs/sotodlib/blob/67b4aa7cb730bb30dcecdba682361570a5399c10/sotodlib/coords/planets.py#L316
This occurred when I was running a catchup `preprocess_obs` job. Each obs would already open many files due to this loop here:
https://github.com/simonsobs/sotodlib/blob/67b4aa7cb730bb30dcecdba682361570a5399c10/sotodlib/obs_ops/sources.py#L49
When running on a list of many obs, these files that are never closed continue to pile up.

close ephemeris file to avoid too many open files

---

sotodlib/coords/det_match.py

Fixing some issues I found while trying to run LAT pointing fits through the detector matching code.

Fix typos for LAT det match

---

sotodlib/preprocess/processes.py

The PCA relcal function wrapped in arrays that included the bandpasses in their names, which breaks when trying to load in multiple bandpasses from an existing preprocessing database.  Those arrays were only used in the PCA plotting, so this branch changes things such that they are only made when plotting is enabled and are deleted once that band's plots have been made.  While it might be useful to have these values available, it is currently more or less impossible to store per-band information (unless they are per-detector indexed) in the preprocessing axis manager and be able to load it back due to restrictions from the axis manager loading/concatenation functions.  This requires changes at a deeper level in the axis manager classes.
Made a slight change to the plotting which was …

Update per-band array handling for relcal

---

sotodlib/preprocess/preprocess_util.py

Previously this function was set up to only find corrupted files that didn't completely write out, but an existing db entry raises a RuntimeError, so this branch adds a catch for those.  Probably will improve `cleanup_mandb` to identify existing db entries in a future update (maybe along with the features of #1156).

Add runtime error check in save_group_and_cleanup

---

sotodlib/preprocess/processes.py

In the current version of AzSS there's different logic for the `process` method of the `AzSS` preprocess class depending if this is the first time the pipeline is being run or a subsequent time (i.e. if `proc_aman` is being loaded back from the archive or being created for the first time in the `calc_and_save` method). Currently if `process_cfgs` is set to `subtract = True` it will only subtract if the `proc_aman` is loaded from the archive (i.e. the 2nd+ time the pipeline is run) since its checking for `self.calc_cfgs.get('azss_stats_name') in proc_aman` which is not added to `proc_aman` until the `calc_and_save` step which is run after the `process` step in the `Pipeline.run()` function. Here I've updated the logic so that the subtraction happens regardless of if its the first time or …

Fix AzSS subtract logic.

---

sotodlib/site_pipeline/multilayer_preprocess_tod.py
sotodlib/site_pipeline/preprocess_tod.py

Separates part of #1156 as a standalone PR.  This will raise an error if any obs_ids either have `error` is not `None` or cannot be extracted from the future result for `preprocess_tod.py` and `multilayer_preprocess_tod.py`

Add option to raise errors at end of preprocessing if obsids failed

---

sotodlib/preprocess/preprocess_util.py

Adds a check for if the preprocessing manifest db exists in save_group_and_cleanup to make sure it works when no database exists.

Add a db check to save_group_and_cleanup

---

sotodlib/io/datapkg_completion.py
sotodlib/io/imprinter.py
sotodlib/site_pipeline/make_book.py

This update is starting a parallelization effort for book binding  with just the operation books (there's lots of them and they're small). 
* Makes a new helper function in imprinter to separate the database reads and database writes. Bookbinding involved a whole but of reads from the imprinter and g3tsmurf databases, but at the end we only write book.status and book.message. sqlite / sqlalchemy can handle multiple active sessions if only one active session is writing. 
* `imprinter.bind_book` still acts the same as it always has
* I tested this on ~3000 operation books on the LAT and the speed-up factor was basically `n_processes`. I also verified that the output books had `timestamps`, `signal` and `Z_smurf` files that were identical between the parallelly and serially written books.
* …

Parallelize make_book for operations books

---

sotodlib/hwp/hwp.py
sotodlib/preprocess/processes.py

This PR allows demodulation filter to have arguments `band_ratio` and `cutoff_ratio` so that we use actual HWP frequency for the filters.
An example config block
```
- name: "demodulate"
process:
trim_samps: 6000
demod_cfgs: {signal: "signal",
demod_mode: 4}
band_ratio: 3.8 # bandpass width ratio compared to HWP rotation frequeny
cutoff_ratio: 1.9 # cutoff frequency ratio compared to HWP rotation frequeny
```

modify so that band_ratio and cutoff_ratio works

---

sotodlib/preprocess/processes.py

The `fft_trim` function only trimmed the axis on `aman` and not `proc_aman`, leading to a miss matched samples error later in the processing stages.

Also trim on proc_aman in fft_trim

---

sotodlib/preprocess/processes.py
sotodlib/tod_ops/flags.py
tests/test_flags.py

Modified get_glitch_flags to allow 1d array input and added preprocess for getting common mode. Also added unit test.
The motivation is to find and remove the glitch which is common among detectors. We have physical motivation for this kind of glitches. We can also do this on hwp demodulated timestreams to find the glitch induced by hwp angle.
Example preprocess config for common mode glitch.
```
- name: "get_common_mode"
calc:
signal: "signal"
method: "median"
wrap: "signal_commonmode"
save: True
- name: "glitches"
skip_on_sim: False
glitch_name: "glitches_commonmode"
calc:
signal_name: 'signal_commonmode'
t_glitch: 0.007
buffer: 100
hp_fc: 6.0
n_sig: 10
save: True
```

Common mode glitch

---

sotodlib/mapmaking/demod_mapmaker.py
sotodlib/mapmaking/noise_model.py
sotodlib/site_pipeline/make_atomic_filterbin_map.py
tests/test_demod_mapmaker.py

This is not ready yet, I haven't tested either on real data, but I guess people can look at the code in the meantime.

adding the use of psd from preprocessing to use as mapmaking weights

---

sotodlib/core/context.py
sotodlib/io/load_book.py

- When "special_channel=True" is passed to get_obs, the "untracked" channels are loaded and populate a .tones sub-AxisMan.
- The smurfgaps flags are loaded from the per-stream frame data and put into `.flags.smurfgaps_{stream_id}`.
- When user passes "no_headers=True", the smurf header fields will not be unpacked (so there is no .primary).

load_book: support for fixed tones, smurfgaps flags, no_headers

---

sotodlib/site_pipeline/preprocess_obs.py

Adds bool argument to `preprocess_obs.py` for LAT observations. Since LAT obs_ids are split by optics tubes with timestamps within about 10 seconds of each other, we only need to run `preprocess_obs` on one of them since it loads the entire aman with no signal. Without this, `preprocess_obs` runs redundant processes.

preprocess_obs: filter obs list for LAT formatted obs_ids

---

sotodlib/preprocess/processes.py

This PR is for avoiding unnecesarry warning.
The first list of method should be '+' or 'union'. Otherwise warning show up.
In previous version this warning always show up if we set '*' or 'intersect' as method.

fix code that made unnecesarry warning

---

sotodlib/preprocess/processes.py

Update `FourierFilter` to allow for filter chaining.  Old input of `filter_function` is still supported for backwards compatibility.

Allow filter chaining

---

sotodlib/core/metadata/cli.py
sotodlib/core/metadata/obsdb.py
sotodlib/core/metadata/obsfiledb.py
tests/test_obsdb.py
tests/test_obsfiledb.py

Facilitate "in place" updates of ObsDb and ObsFileDb.  Basically if you have an upstream version that only contains new things, the code can cleanly add those new things into the downstream target.
Easiest usage is through the so-metadata cli. 
For ObsDb:
```
$ so-metadata obsdb-diff \
satp1-may14-snapshot/satp1_obsdb_240911m_local.sqlite \
satp1-may29-snapshot/satp1_obsdb_240911m_local.sqlite
```
which says:
```
Comparing to satp1-may29-snapshot/satp1_obsdb_240911m_local.sqlite ...
... upstream is different, but the target db can be patched to match.
```
and if you add `--patch`, it will modify the left one (may14) in place.
For ObsFileDb:
```
$ so-metadata obsfiledb satp1-may14-snapshot/satp1_obsfiledb.sqlite \
diff satp1-may29-snapshot/satp1_obsfiledb.sqlite
```
will similarly print: …

CLI support to patch ObsDb and ObsFileDb from an upstream copy

---

sotodlib/obs_ops/splits.py
sotodlib/preprocess/processes.py

This resolves https://github.com/simonsobs/sotodlib/issues/1263
Daniel confirmed by directly looking at the full wafer GDS and following traces to the labeled bond pads. because we did not find good document for this.
This split was not used in sat-iso null tests.

fix crossover split

---

sotodlib/preprocess/preprocess_util.py

Adds a check for the type of both the reference and loaded axis managers in multilayer preprocessing.  Note this will allow failed checks to pass (as they already do in some cases due to recursion), which will need to be fixed later.

update preproc config checker types

---

sotodlib/preprocess/processes.py

Adds the median of all detector white noise values as a QA metric for `record_qa`.

Add mean white noise QA metric

---

sotodlib/toast/workflows/sim_optical_pickup.py

Tiny update to use the new polarized SSS support in TOAST: https://github.com/hpc4cmb/toast/pull/833

TOAST Scan-Synchronous Signal now requires Stokes weights

---

sotodlib/tod_ops/flags.py

Optimizes the trending flags function.  On Nersc login this change makes the runtime go from 47 seconds (about 30 seconds of which were taken up by `hstack`) to 1.4 seconds.  Compared the outputs with `full_output=True` and find they are consistent between this and the older version.  Used `obs_1734313105_satp1_1111111` and `dets = {'wafer_slot': 'ws0', 'wafer.bandpass': 'f150'}` for testing.

Optimize trend flags

---

sotodlib/core/__init__.py
sotodlib/core/metadata/manifest.py
sotodlib/core/metadata/obsdb.py
sotodlib/core/metadata/resultset.py
sotodlib/site_pipeline/update_obsdb.py
tests/test_core.py
tests/test_metadata.py
tests/test_obsdb.py

- ObsDb will create indices on main tables.
- ObsDb.query will noisily replace double quotes with single quotes in
query strings.
- update_obsdb will populate LAT "detector_flavor" (previously was
leaving null).
- ResultSet -- if a column has a None value, some effort is made to
cast to the type of the other data in the column.
- core imports .metadata, to give easier access to those things and
simplify use alongside io.metadata
- ManifestDb.get_entries() will auto-quote fields, so colons in field
names are easier to work with.
Resolves #705, #1178, #1185.

Quality of life obsdb/manifestdb/resultset fixes

---

sotodlib/preprocess/processes.py
sotodlib/tod_ops/flags.py

This flag is very useful, and we need to use more.
The default buffer value is arbitrary, I chose this based on ws2 of obs_1727642777_satp3_1111111 and obs_1727991085_satp3_1111111
link to the presentation showing the effectiveness of this flag.
https://simonsobs.atlassian.net/wiki/spaces/PRO/pages/806846478/SAT+LAT+Analysis+Section+1+telecons#26-June-2025-(B-slot-%E2%80%93-8pm-ET)

add process for smurfgaps

---

sotodlib/mapmaking/noise_model.py
sotodlib/toast/ops/mlmapmaker.py

Also fix error when loading cached NmatUncorr in TOAST.

TOAST mlmapmaker: Add support NmatUnit and NmatWhite noise model

---

sotodlib/preprocess/processes.py
sotodlib/qa/metrics.py

Adds array NETs and effective per-detector NETs to `record_qa`.  Removes the median noise `gen_metric` since these should replace that.
Tested with dev `InfluxDb` and the config in this PR:
https://github.com/simonsobs/site-pipeline-configs/pull/142

Add NET metrics to record_qa

---

sotodlib/preprocess/pcore.py

When loading, `update_full_aman` is not called, so it will not contain `frequency_cutoffs` since it is added later.  Adds a check to the `frequency_cutoffs` move to make sure it won't fail.

Check if frequency cutoffs are in full aman

---

sotodlib/hwp/hwp.py

I suggest changing the indent from [line 261](https://github.com/simonsobs/sotodlib/blob/780191b4363bf42ca4bd29c38404b13157618d5b/sotodlib/hwp/hwp.py#L261) to line 265 in `hwp.py`. 
This `else` block should be related to the `if apodize_edges:` block, otherwise `weight_for_signal` will be never assigned.
This change is trivial since almost no one uses `get_hwpss` without the apodization, but I would be happy if someone can review this pull request.

Bug fix in get_binned_hwpss

---

sotodlib/site_pipeline/cli.py

Recent change made it only work if cli_main is defined.

Fix so-site-pipeline launcher bug

---

sotodlib/mapmaking/noise_model.py

This fix missing ivar entry when loading cached `NmatUnit` noise model in TOAST.

mlmapmaker: Fix missing ivar when loading NmatUnit

---

sotodlib/qa/quality_reports/plots.py
sotodlib/qa/quality_reports/report_data.py
sotodlib/site_pipeline/generate_reports.py

Fix to support `numpy` v2 when querying apex pwv data.  Adds per-band yields and a per-platform navigation dropdown to make it easier to go between quality reports.
Doesn't add any new dependencies.
Examples here: https://site.simonsobs.org/~mmccrackan/nav_test/

Generate_reports updates

---

sotodlib/coords/demod.py
sotodlib/preprocess/processes.py

I find this function helpful to study various statistics in ground (az/el) frame before map making.
If we run `rotate_focal_plane` and `rotate_demodQU`, we can get the focal plane and tod in ground frame.

rotate focal plane

---

sotodlib/site_pipeline/update_det_cal.py

- Replace multiprocessing.Pool with executor objects
- Switched from apply_async + callback model to submit + as_completed
- Avoid passing non-pickleable axismanager to subprocesses
I believe these updates will fix the hanging update_det_cal flows on prefect. Separate note that [sodetlib PR#468](https://github.com/simonsobs/sodetlib/pull/468) which similarly updates the multiprocessing code inside `tes_param_correction.py` is required to be merged as well to make these changes work.

update_det_cal: refactor multiprocessing logic to use concurrent.futures

---

sotodlib/preprocess/preprocess_util.py

Searches for `label` in addition to `name` in the `get_preprocess_context` function to prevent duplicate entries.

Also search for label key in get_preprocess_context

---

sotodlib/preprocess/processes.py

Clears out the frequency cutoffs in demodulate since they may already exist when loading from an existing database.

Check frequency cutoffs first in demodulate

---

sotodlib/tod_ops/fft_ops.py

Previously the entire fitting function was wrapped in a warnings to error conversion scope, but this causes problems since there can sometimes be warnings inside the minimizer and that the bounds inside `scipy.minimize` can be violated on some iterations, so having the warning conversion resulted in raising errors.  This just moves it to only wrap around the Hessian calculation which is where we want to actually convert them.  Don't see any performance issue with having this in the loop.
Also, just to note that it looks like we can avoid many Hessian evaluation errors by letting `low_f` go down to `freqs[1] `(default) for Q and U as the fit is better at recovering the shallow 1/f slope of the Q and U PSDs as opposed to cutting it off at say 0.1 or 0.01.
Tested on SATP2 obs_ids that were …

Prevent fit failures due to warnings

---

sotodlib/qa/metrics.py

Update hwp angle solution QA metrics to include new statistics of hwp_angles_250711m.
Also update `HWPSolSucces` to distinguish "failure" and "no data" (https://github.com/simonsobs/sotodlib/issues/1210)
Tested in daq-dev.
I needed to make breaking change for `HWPSolSucces` to express more than two states.
I considered keeping `HWPSolSucces` and adding `HWPSolDataExist`  and do some kind of math in grafana instead, but I found this approach difficult. If it is actually easy, I will take this approach.

update hwp qa metrics

---

sotodlib/site_pipeline/generate_reports.py

Reduces the buffer time for starting adding a time interval to the list of time intervals to run to 1 hour from 1 day.  This fixes an issue on Prefect where if you run on the last day of the final interval, it won't add that week.  Tested on site and confirmed it made up to the current date and did not add any future time periods (would happen if the buffer is zero).

Reduce generate_reports buffer time

---

sotodlib/toast/instrument.py
sotodlib/toast/ops/load_context.py

In toast, the azel -> radec transform makes use of weather information. For real data we currently have access to the "typical weather" at the site in terms of temperature, pressure, and humidity.  Construct the toast site weather using the best info we have, which is the median MERRA-2 data for day of year and time of day, along with the "typical weather" parameters.  This allows us to build consistent pointing in toast relative to what is done in so3g.
Eventually, it would be nice if temperature, pressure, PWV, etc were recorded in the metadata loaded from the context.

When loading data from a Context into toast, use consistent weather

---

sotodlib/preprocess/pcore.py
sotodlib/preprocess/processes.py
sotodlib/qa/metrics.py

There are errors in the `record_qa` flows on Prefect due to some obs_ids having a single band from a wafer missing from the preprocessing database so the `subsets` array is empty causing failures in the statistics calculations.  This adds in some checks to guard against that and does not add that wafer and band combo to the list if it fails.  Have tested with the `dev-db` and confirmed a failed obs_id now runs, but have not tested in Grafana.
Should note I think this is a LAT exclusive problem seemingly (but not really to any one obs tube I think), so it may go away with better preprocessing and detector setup.

Check if wafer and band exist for qa

---

.github/workflows/publish.yaml

Our Pypi release did not run because as it seems when we use `GITHUB_TOKEN` in a workflow any repository changes the workflow makes do not trigger a new workflow run.
This PR makes a change to the Pypi release to allow for a "workflow" based trigger. It checks the events and when the monthly release is run successfully, it gets triggered and releases to pypi.

Pypi release

---

tests/_helpers.py
tests/test_mapmaker_pointing.py

This improvement was used to pinpoint a pointing error in TOAST when using qpoint: https://github.com/hpc4cmb/toast/pull/853

Add boresight rotation to the pointing test

---

sotodlib/preprocess/pcore.py
sotodlib/preprocess/preprocess_util.py
sotodlib/site_pipeline/multilayer_preprocess_tod.py
sotodlib/site_pipeline/preprocess_tod.py

Adds a `dets` x `samps` `valid` `RangesMatrix` at the end of the preprocess pipeline that keeps track of the final number of valid detectors.  Some changes were made to the `load_and_preprocess` functions to accommodate and use this when available.  Tested running through first and second layers, loading only first layer and both first and second.  Loaded existing db from before this change to check for backwards compatibility.  Confirmed same det vals appear in all cases.

Add a valid ranges matrix to proc_aman

---

sotodlib/preprocess/processes.py

Docstring for the Fourier filter in preprocessing had some typos and didn't apply to the signal which caused some confusion when I was using it in the site-pipeline-configs preprocessing configurations.

Update preprocessing Fourier filter docstring

---

sotodlib/core/metadata/obsfiledb.py

With this implementation, peak memory should be driven by the size of the difference between two databases, not the size of the dbs.
In a test run on LAT obsfiledb this reduces peak memory usage from 5GB to 100MB.

ObsFileDb: update diff routine for memory efficiency

---

sotodlib/coords/helpers.py

Avoids huge maps when patch straddles geometry limits, and the geometry is being automatically built.

Fix angle wrapping in get_footprint

---

sotodlib/preprocess/pcore.py
sotodlib/preprocess/processes.py
sotodlib/qa/metrics.py

Updates `record_qa` and related functions to be able to parse preprocess_lite databases which do not have `wafer_info` and instead use `det_cal` bandpasses.
Also adds the ability to add a field name suffix to the end of the noise metric names so we can get out T, Q, and U.  Changes default noise units factor to 1 since we are interested in pW noise values.

Update record_qa for preprocess_lite
